In [1]:
install.packages(c(
  "tidyverse",
  "psych",
  "GPArotation",
  "nFactors",
  "corrplot",
  "reshape2",
  "lavaan",
  "semTools",
    "blavaan",
    "bayesplot",
    "posterior"
))

Instalando pacotes em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

package 'tidyverse' successfully unpacked and MD5 sums checked
package 'psych' successfully unpacked and MD5 sums checked
package 'GPArotation' successfully unpacked and MD5 sums checked
package 'nFactors' successfully unpacked and MD5 sums checked
package 'corrplot' successfully unpacked and MD5 sums checked
package 'reshape2' successfully unpacked and MD5 sums checked
package 'lavaan' successfully unpacked and MD5 sums checked
package 'semTools' successfully unpacked and MD5 sums checked
package 'blavaan' successfully unpacked and MD5 sums checked
package 'bayesplot' successfully unpacked and MD5 sums checked
package 'posterior' successfully unpacked and MD5 sums checked

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\RtmpsjQ3UC\downloaded_packages

In [2]:
install.packages("QuickJSR", type = "source")

Instalando pacote em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

In [4]:
library(tidyverse)

library(psych)
library(GPArotation)

library(nFactors)

library(corrplot)

library(reshape2)

library(lavaan)
library(semTools)

library(blavaan)
library(bayesplot)

Anexando pacote: 'psych'


Os seguintes objetos são mascarados por 'package:ggplot2':

    %+%, alpha



Anexando pacote: 'GPArotation'


Os seguintes objetos são mascarados por 'package:psych':

    equamax, varimin


corrplot 0.95 loaded


Anexando pacote: 'reshape2'


O seguinte objeto é mascarado por 'package:tidyr':

    smiths


This is lavaan 0.6-21
lavaan is FREE software! Please report any bugs.


Anexando pacote: 'lavaan'


O seguinte objeto é mascarado por 'package:psych':

    cor2cov




###############################################################################

This is semTools 0.5-8

All users of R (or SEM) are invited to submit functions or ideas for functions.

###############################################################################


Anexando pacote: 'semTools'


Os seguintes objetos são mascarados por 'package:psych':

    reliability, skew


O seguinte objeto é mascarado por 'package:readr':

    clipboard


Carregando pacotes exigidos: Rcpp

This is blavaan 0.5-10

On multicore systems, we suggest use of future::plan("multicore") or
  future::plan("multisession") for faster post-MCMC computations.

This is bayesplot version 1.15.0

- Online documentation and vignettes at mc-stan.org/bayesplot

- bayesplot theme set to bayesplot::theme_default()

   * Does _not_ affect other ggplot2 plots

   * See ?bayesplot_theme_set for details on theme setting

In [5]:
efa_data_raw <- read.delim(
  "adequacy-c.txt",
  check.names = FALSE
)

names(efa_data_raw) <- gsub(
  "\\.+",
  "_",
  names(efa_data_raw)
)

id_cols <- c(
  "O_NET_SOC_Code",
  "Title",
  "Version_Year"
)

skill_vars <- setdiff(
  names(efa_data_raw),
  id_cols
)

efa_global <- efa_data_raw %>%
  select(all_of(skill_vars))

### 1. Solução com 6 Fatores

In [6]:
efa6 <- fa(
  efa_global,
  nfactors = 6,
  fm = "minres",
  rotate = "promax"
)

print(
  efa6,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR4   MR1   MR2   MR3   MR6
Science_Level                              6  0.94
Programming_Level                         21  0.93
Mathematical_Reasoning_Level               5  0.87
Reading_Comprehension_Level                1  0.76
Complex_Problem_Solving_Level             17  0.70  0.32
Operations_Analysis_Level                 18  0.68
Technology_Design_Level                   19  0.66        0.34
Critical_Thinking_Level                    7  0.66  0.42
Active_Learning_Level                      8  0.66
Writing_Level                              3  0.62
Systems_Analysis_Level                    29  0.60
Judgment_and_Decision_Making_Level        28  0.58  0.39
Systems_Evaluation_Level                  30  0.55  0.36
Speaking_Level                             4  0.50  0.40
Persuasion_Level                          13        1.00
Negotiation_Level                         14        0.99
Social_Perceptiveness_Level               11        0.89
Service_Orientation_Level                 16        0.89
Coordination_Level                        12        0.80
Time_Management_Level                     31        0.58
Management_of_Personnel_Resources_Level   34        0.57        0.34
Active_Listening_Level                     2  0.52  0.52
Monitoring_Level                          10  0.33  0.48
Repairing_Level                           26              1.02
Equipment_Maintenance_Level               24              0.99
Troubleshooting_Level                     25              0.97
Equipment_Selection_Level                 35              0.94
Operations_Monitoring_Level               22              0.85
Operation_and_Control_Level               23              0.83
Quality_Control_Analysis_Level            27              0.77
Installation_Level                        20              0.71
Management_of_Financial_Resources_Level   32                    0.87
Management_of_Material_Resources_Level    33                    0.79
Instructing_Level                         15  0.32                    0.51
Learning_Strategies_Level                  9  0.37                    0.50
                                          MR5   h2    u2 com
Science_Level                                 0.69 0.311 1.3
Programming_Level                             0.60 0.404 1.3
Mathematical_Reasoning_Level                  0.71 0.294 1.4
Reading_Comprehension_Level                   0.92 0.080 1.3
Complex_Problem_Solving_Level                 0.89 0.105 1.4
Operations_Analysis_Level                     0.64 0.357 1.2
Technology_Design_Level                       0.54 0.463 1.8
Critical_Thinking_Level                       0.91 0.095 1.8
Active_Learning_Level                         0.92 0.078 1.5
Writing_Level                                 0.91 0.094 1.8
Systems_Analysis_Level                        0.86 0.137 1.7
Judgment_and_Decision_Making_Level            0.88 0.122 1.8
Systems_Evaluation_Level                      0.89 0.113 2.0
Speaking_Level                                0.92 0.083 2.7
Persuasion_Level                              0.91 0.089 1.1
Negotiation_Level                             0.87 0.127 1.1
Social_Perceptiveness_Level                   0.85 0.154 1.0
Service_Orientation_Level                     0.69 0.306 1.1
Coordination_Level                            0.71 0.289 1.3
Time_Management_Level                         0.81 0.189 1.7
Management_of_Personnel_Resources_Level       0.84 0.156 2.3
Active_Listening_Level                        0.90 0.103 2.5
Monitoring_Level                              0.87 0.134 2.8
Repairing_Level                               0.97 0.027 1.2
Equipment_Maintenance_Level                   0.95 0.053 1.2
Troubleshooting_Level                         0.94 0.060 1.0
Equipment_Selection_Level                     0.88 0.119 1.1
Operations_Monitoring_Level             -0.42 0.95 0.053 1.6
Operation_and_Control_Level             -0.32 0.86 0.136 1.4
Quality_Control_Analysis_Level                0.82 0.179 1.4
Installation_Level                       0.34 0.51 0.494 1.4
Management_of_Financial_Resources_Level       0.90 0.104 1.2
Management_of_Material_Resources_Level        0.83 0.166 1.1
Instructing_Level                             0.85 0.151 2.4
Learning_Strategies_Level                     0.87 0.130 2.3

                       MR4  MR1  MR2  MR3  MR6  MR5
SS loadings           9.30 8.43 6.78 2.07 1.76 0.71
Proportion Var        0.27 0.24 0.19 0.06 0.05 0.02
Cumulative Var        0.27 0.51 0.70 0.76 0.81 0.83
Proportion Explained  0.32 0.29 0.23 0.07 0.06 0.02
Cumulative Proportion 0.32 0.61 0.84 0.92 0.98 1.00

 With factor correlations of
      MR4   MR1   MR2   MR3   MR6   MR5
MR4  1.00  0.67 -0.13  0.41  0.48  0.07
MR1  0.67  1.00 -0.45  0.34  0.57  0.12
MR2 -0.13 -0.45  1.00  0.23 -0.22 -0.24
MR3  0.41  0.34  0.23  1.00  0.14 -0.26
MR6  0.48  0.57 -0.22  0.14  1.00 -0.09
MR5  0.07  0.12 -0.24 -0.26 -0.09  1.00

Mean item complexity =  1.6
Test of the hypothesis that 6 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 400  and the objective function was  5.39

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  3050 with the empirical chi square  486.01  with prob <  0.0021
The total n.obs was  3050  with Likelihood Chi Square =  16331.8  with prob <  0

Tucker Lewis Index of factoring reliability =  0.863
RMSEA index =  0.114  and the 90 % confidence intervals are  0.113 0.116
BIC =  13122.64
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR4  MR1  MR2  MR3  MR6 MR5
Correlation of (regression) scores with factors   0.99 0.99 0.99 0.97 0.97   1
Multiple R square of scores with factors          0.99 0.98 0.99 0.94 0.95   1
Minimum correlation of possible factor scores     0.97 0.97 0.98 0.87 0.90   1

### 2. Extrair cargas

In [7]:
loadings_6 <- as.data.frame(
  unclass(efa6$loadings)
)

round(loadings_6, 3)

                                        MR4    MR1    MR2    MR3    MR6
Reading_Comprehension_Level              0.758  0.188 -0.161 -0.154  0.101
Active_Listening_Level                   0.515  0.519 -0.144 -0.211 -0.007
Writing_Level                            0.622  0.219 -0.192 -0.105  0.185
Speaking_Level                           0.498  0.402 -0.194 -0.145  0.130
Mathematical_Reasoning_Level             0.866 -0.265 -0.111  0.247  0.004
Science_Level                            0.942 -0.143  0.123 -0.201  0.083
Critical_Thinking_Level                  0.658  0.423 -0.028 -0.123 -0.013
Active_Learning_Level                    0.658  0.246 -0.072 -0.037  0.174
Learning_Strategies_Level                0.369  0.201 -0.034  0.035  0.502
Monitoring_Level                         0.330  0.480  0.079  0.012  0.290
Social_Perceptiveness_Level              0.009  0.890 -0.067 -0.113  0.040
Coordination_Level                      -0.107  0.805  0.126  0.169  0.120
Persuasion_Level                         0.034  1.000 -0.033  0.047 -0.213
Negotiation_Level                       -0.056  0.995 -0.052  0.096 -0.175
Instructing_Level                        0.316  0.286  0.050 -0.019  0.510
Service_Orientation_Level               -0.094  0.889 -0.108 -0.015 -0.103
Complex_Problem_Solving_Level            0.698  0.315  0.079 -0.022  0.058
Operations_Analysis_Level                0.679  0.078 -0.026  0.169 -0.044
Technology_Design_Level                  0.660  0.041  0.339  0.115 -0.213
Installation_Level                       0.026 -0.006  0.713 -0.004  0.005
Programming_Level                        0.927 -0.258 -0.060  0.085 -0.161
Operations_Monitoring_Level              0.075  0.103  0.848 -0.098 -0.098
Operation_and_Control_Level             -0.124  0.084  0.828 -0.109 -0.043
Equipment_Maintenance_Level             -0.116 -0.048  0.991 -0.053  0.112
Troubleshooting_Level                   -0.004  0.040  0.970 -0.058 -0.037
Repairing_Level                         -0.125 -0.021  1.015 -0.030  0.112
Quality_Control_Analysis_Level           0.194 -0.041  0.772  0.083 -0.057
Judgment_and_Decision_Making_Level       0.583  0.392  0.003 -0.013  0.082
Systems_Analysis_Level                   0.601  0.291  0.076  0.124  0.098
Systems_Evaluation_Level                 0.552  0.362  0.102  0.119  0.110
Time_Management_Level                    0.171  0.576  0.062  0.195  0.193
Management_of_Financial_Resources_Level  0.041  0.183 -0.187  0.873 -0.053
Management_of_Material_Resources_Level   0.035  0.191  0.004  0.793  0.066
Management_of_Personnel_Resources_Level -0.004  0.566  0.079  0.342  0.287
Equipment_Selection_Level                0.029 -0.056  0.940  0.008  0.008
                                        MR5
Reading_Comprehension_Level              0.014
Active_Listening_Level                   0.021
Writing_Level                            0.081
Speaking_Level                           0.066
Mathematical_Reasoning_Level            -0.029
Science_Level                           -0.174
Critical_Thinking_Level                  0.006
Active_Learning_Level                    0.042
Learning_Strategies_Level                0.092
Monitoring_Level                        -0.152
Social_Perceptiveness_Level             -0.024
Coordination_Level                      -0.113
Persuasion_Level                         0.032
Negotiation_Level                        0.026
Instructing_Level                        0.042
Service_Orientation_Level                0.029
Complex_Problem_Solving_Level            0.003
Operations_Analysis_Level               -0.055
Technology_Design_Level                  0.024
Installation_Level                       0.343
Programming_Level                        0.074
Operations_Monitoring_Level             -0.422
Operation_and_Control_Level             -0.321
Equipment_Maintenance_Level              0.226
Troubleshooting_Level                   -0.076
Repairing_Level                          0.297
Quality_Control_Analysis_Level          -0.236
Judgment_and_Decision_Making_Level      -0.006
Systems_Analysis_Level                   0.042
Systems_Evaluation_Level                 0.036
Time_Management_Level                   -0.005
Management_of_Financial_Resources_Level  0.070
Management_of_Material_Resources_Level   0.008
Management_of_Personnel_Resources_Level -0.076
Equipment_Selection_Level                0.138

### 3. Comunalidades, R e Q

In [8]:
communalities_6 <- tibble(
  skill = rownames(loadings_6),
  h2 = efa6$communality
)

communalities_6 %>%
  arrange(h2)

                                        skill
Installation_Level                      Installation_Level
Technology_Design_Level                 Technology_Design_Level
Programming_Level                       Programming_Level
Operations_Analysis_Level               Operations_Analysis_Level
Science_Level                           Science_Level
Service_Orientation_Level               Service_Orientation_Level
Mathematical_Reasoning_Level            Mathematical_Reasoning_Level
Coordination_Level                      Coordination_Level
Time_Management_Level                   Time_Management_Level
Quality_Control_Analysis_Level          Quality_Control_Analysis_Level
Management_of_Material_Resources_Level  Management_of_Material_Resources_Level
Management_of_Personnel_Resources_Level Management_of_Personnel_Resources_Level
Social_Perceptiveness_Level             Social_Perceptiveness_Level
Instructing_Level                       Instructing_Level
Systems_Analysis_Level                  Systems_Analysis_Level
Operation_and_Control_Level             Operation_and_Control_Level
Monitoring_Level                        Monitoring_Level
Learning_Strategies_Level               Learning_Strategies_Level
Negotiation_Level                       Negotiation_Level
Judgment_and_Decision_Making_Level      Judgment_and_Decision_Making_Level
Equipment_Selection_Level               Equipment_Selection_Level
Systems_Evaluation_Level                Systems_Evaluation_Level
Complex_Problem_Solving_Level           Complex_Problem_Solving_Level
Management_of_Financial_Resources_Level Management_of_Financial_Resources_Level
Active_Listening_Level                  Active_Listening_Level
Critical_Thinking_Level                 Critical_Thinking_Level
Writing_Level                           Writing_Level
Persuasion_Level                        Persuasion_Level
Speaking_Level                          Speaking_Level
Reading_Comprehension_Level             Reading_Comprehension_Level
Active_Learning_Level                   Active_Learning_Level
Troubleshooting_Level                   Troubleshooting_Level
Operations_Monitoring_Level             Operations_Monitoring_Level
Equipment_Maintenance_Level             Equipment_Maintenance_Level
Repairing_Level                         Repairing_Level
                                        h2
Installation_Level                      0.5063172
Technology_Design_Level                 0.5369460
Programming_Level                       0.5958335
Operations_Analysis_Level               0.6427382
Science_Level                           0.6891837
Service_Orientation_Level               0.6938548
Mathematical_Reasoning_Level            0.7056810
Coordination_Level                      0.7108520
Time_Management_Level                   0.8108945
Quality_Control_Analysis_Level          0.8212692
Management_of_Material_Resources_Level  0.8340611
Management_of_Personnel_Resources_Level 0.8444350
Social_Perceptiveness_Level             0.8459306
Instructing_Level                       0.8493623
Systems_Analysis_Level                  0.8633226
Operation_and_Control_Level             0.8635538
Monitoring_Level                        0.8660054
Learning_Strategies_Level               0.8698208
Negotiation_Level                       0.8730356
Judgment_and_Decision_Making_Level      0.8781863
Equipment_Selection_Level               0.8812748
Systems_Evaluation_Level                0.8873193
Complex_Problem_Solving_Level           0.8949002
Management_of_Financial_Resources_Level 0.8958183
Active_Listening_Level                  0.8974963
Critical_Thinking_Level                 0.9054675
Writing_Level                           0.9055652
Persuasion_Level                        0.9113137
Speaking_Level                          0.9174687
Reading_Comprehension_Level             0.9204687
Active_Learning_Level                   0.9223328
Troubleshooting_Level                   0.9397200
Operations_Monitoring_Level             0.9465599
Equipment_Maintenance_Level             0.9467689
Repairing_Level                         0.9734383

In [9]:
efa6$r.scores

     [,1]        [,2]       [,3]       [,4]       [,5]        [,6]
[1,]  1.00000000  0.6969856 -0.1358527  0.4191381  0.54186613  0.06338093
[2,]  0.69698557  1.0000000 -0.4581848  0.3604419  0.61479387  0.12068706
[3,] -0.13585268 -0.4581848  1.0000000  0.2273377 -0.23066419 -0.24903036
[4,]  0.41913812  0.3604419  0.2273377  1.0000000  0.15521699 -0.27895019
[5,]  0.54186613  0.6147939 -0.2306642  0.1552170  1.00000000 -0.05081276
[6,]  0.06338093  0.1206871 -0.2490304 -0.2789502 -0.05081276  1.00000000

In [10]:
efa6$STATISTIC   # Qui-quadrado
efa6$dof         # Graus de liberdade
efa6$PVAL        # p-valor

[1] 16331.8

[1] 400

[1] 0

### 4. EFA longitudinal por ano

In [11]:
years <- sort(
  unique(efa_data_raw$Version_Year)
)

efa_by_year <- list()

for(y in years){

  temp <- efa_data_raw %>%
    filter(Version_Year == y) %>%
    select(all_of(skill_vars))

  efa_by_year[[as.character(y)]] <- fa(
    temp,
    nfactors = 6,
    fm = "minres",
    rotate = "promax"
  )

}

In [12]:
efa_by_year

$`2017`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR1   MR2   MR6   MR4   MR3   MR5
Reading_Comprehension_Level              0.82 -0.16  0.00  0.23 -0.16 -0.03
Active_Listening_Level                   0.71 -0.15  0.26  0.14 -0.21 -0.02
Writing_Level                            0.88 -0.18 -0.02  0.11 -0.11 -0.09
Speaking_Level                           0.82 -0.18  0.14  0.07 -0.15 -0.07
Mathematical_Reasoning_Level             0.34 -0.11 -0.20  0.52  0.24  0.02
Science_Level                            0.73  0.11 -0.23  0.32 -0.20  0.14
Critical_Thinking_Level                  0.73 -0.03  0.20  0.24 -0.14  0.01
Active_Learning_Level                    0.86 -0.06  0.00  0.18 -0.03 -0.04
Learning_Strategies_Level                1.07 -0.02 -0.17 -0.16  0.07 -0.11
Monitoring_Level                         0.97  0.08  0.01 -0.13  0.03  0.13
Social_Perceptiveness_Level              0.65 -0.07  0.44 -0.15 -0.08  0.03
Coordination_Level                       0.61  0.12  0.29 -0.22  0.20  0.11
Persuasion_Level                         0.38 -0.03  0.63  0.04  0.05  0.00
Negotiation_Level                        0.33 -0.04  0.64 -0.02  0.10  0.01
Instructing_Level                        1.14  0.06 -0.16 -0.23  0.01 -0.06
Service_Orientation_Level                0.31 -0.12  0.55 -0.06  0.02 -0.03
Complex_Problem_Solving_Level            0.77  0.09  0.08  0.26 -0.04  0.01
Operations_Analysis_Level                0.44 -0.04 -0.03  0.35  0.17  0.02
Technology_Design_Level                  0.03  0.36  0.14  0.51  0.13 -0.01
Installation_Level                       0.00  0.68  0.04  0.07 -0.01 -0.29
Programming_Level                        0.09 -0.04 -0.01  0.66  0.05 -0.03
Operations_Monitoring_Level             -0.07  0.80  0.05  0.05 -0.10  0.48
Operation_and_Control_Level             -0.10  0.77 -0.01 -0.08 -0.08  0.37
Equipment_Maintenance_Level              0.06  0.97 -0.07 -0.09 -0.06 -0.17
Troubleshooting_Level                   -0.05  0.93  0.02  0.03 -0.06  0.14
Repairing_Level                          0.06  1.00 -0.03 -0.08 -0.05 -0.24
Quality_Control_Analysis_Level           0.07  0.74 -0.10  0.12  0.07  0.25
Judgment_and_Decision_Making_Level       0.78  0.01  0.12  0.16 -0.01  0.00
Systems_Analysis_Level                   0.69  0.06  0.05  0.23  0.12 -0.03
Systems_Evaluation_Level                 0.74  0.11  0.10  0.17  0.12 -0.02
Time_Management_Level                    0.77  0.05  0.12 -0.10  0.21  0.01
Management_of_Financial_Resources_Level -0.11 -0.19  0.07  0.24  0.89 -0.06
Management_of_Material_Resources_Level   0.10 -0.01 -0.02  0.11  0.84 -0.03
Management_of_Personnel_Resources_Level  0.78  0.08  0.04 -0.24  0.36  0.06
Equipment_Selection_Level               -0.01  0.92 -0.04  0.03  0.02 -0.11
                                          h2    u2 com
Reading_Comprehension_Level             0.92 0.082 1.3
Active_Listening_Level                  0.90 0.098 1.7
Writing_Level                           0.91 0.094 1.2
Speaking_Level                          0.92 0.078 1.3
Mathematical_Reasoning_Level            0.69 0.305 2.7
Science_Level                           0.66 0.342 1.9
Critical_Thinking_Level                 0.91 0.093 1.5
Active_Learning_Level                   0.92 0.075 1.1
Learning_Strategies_Level               0.85 0.150 1.1
Monitoring_Level                        0.88 0.124 1.1
Social_Perceptiveness_Level             0.83 0.165 2.0
Coordination_Level                      0.72 0.283 2.2
Persuasion_Level                        0.91 0.087 1.7
Negotiation_Level                       0.88 0.124 1.6
Instructing_Level                       0.84 0.157 1.1
Service_Orientation_Level               0.69 0.309 1.7
Complex_Problem_Solving_Level           0.90 0.105 1.3
Operations_Analysis_Level               0.61 0.392 2.3
Technology_Design_Level                 0.51 0.486 2.1
Installation_Level                      0.48 0.517 1.4
Programming_Level                       0.52 0.476 1.1
Operations_Monitoring_Level             0.95 0.054 1.7
Operation_and_Control_Level             0.85 0.149 1.5
Equipment_Maintenance_Level             0.94 0.064 1.1
Troubleshooting_Level                   0.93 0.068 1.1
Repairing_Level                         0.97 0.031 1.1
Quality_Control_Analysis_Level          0.78 0.221 1.4
Judgment_and_Decision_Making_Level      0.88 0.121 1.1
Systems_Analysis_Level                  0.85 0.150 1.3
Systems_Evaluation_Level                0.88 0.118 1.3
Time_Management_Level                   0.82 0.179 1.2
Management_of_Financial_Resources_Level 0.87 0.126 1.3
Management_of_Material_Resources_Level  0.84 0.159 1.1
Management_of_Personnel_Resources_Level 0.85 0.147 1.7
Equipment_Selection_Level               0.89 0.114 1.0

                        MR1  MR2  MR6  MR4  MR3  MR5
SS loadings           14.13 6.48 2.65 2.51 2.26 0.73
Proportion Var         0.40 0.19 0.08 0.07 0.06 0.02
Cumulative Var         0.40 0.59 0.66 0.74 0.80 0.82
Proportion Explained   0.49 0.23 0.09 0.09 0.08 0.03
Cumulative Proportion  0.49 0.72 0.81 0.90 0.97 1.00

 With factor correlations of
      MR1   MR2   MR6  MR4  MR3   MR5
MR1  1.00 -0.30  0.59 0.56 0.47  0.14
MR2 -0.30  1.00 -0.45 0.07 0.10  0.14
MR6  0.59 -0.45  1.00 0.15 0.40 -0.01
MR4  0.56  0.07  0.15 1.00 0.28  0.07
MR3  0.47  0.10  0.40 0.28 1.00  0.35
MR5  0.14  0.14 -0.01 0.07 0.35  1.00

Mean item complexity =  1.5
Test of the hypothesis that 6 factors are sufficient.

df null model =  595  with the objective function =  56.51 with Chi Square =  33711.02
df of  the model are 400  and the objective function was  5.5

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  610 with the empirical chi square  106.34  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  3256.18  with prob <  0

Tucker Lewis Index of factoring reliability =  0.871
RMSEA index =  0.108  and the 90 % confidence intervals are  0.105 0.112
BIC =  690.8
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR1  MR2  MR6  MR4  MR3  MR5
Correlation of (regression) scores with factors   0.98 0.98 0.84 0.94 0.92 0.98
Multiple R square of scores with factors          0.96 0.96 0.70 0.89 0.84 0.95
Minimum correlation of possible factor scores     0.91 0.91 0.40 0.78 0.68 0.90

$`2019`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR4   MR1   MR2   MR3   MR6   MR5
Reading_Comprehension_Level              0.74  0.20 -0.16 -0.15  0.10  0.02
Active_Listening_Level                   0.50  0.53 -0.15 -0.21 -0.01  0.03
Writing_Level                            0.60  0.25 -0.19 -0.11  0.19  0.08
Speaking_Level                           0.47  0.42 -0.20 -0.14  0.13  0.07
Mathematical_Reasoning_Level             0.86 -0.26 -0.11  0.25  0.02 -0.03
Science_Level                            0.92 -0.13  0.13 -0.20  0.08 -0.17
Critical_Thinking_Level                  0.64  0.45 -0.03 -0.13 -0.02  0.00
Active_Learning_Level                    0.63  0.27 -0.07 -0.03  0.17  0.04
Learning_Strategies_Level                0.33  0.24 -0.04  0.05  0.50  0.09
Monitoring_Level                         0.32  0.51  0.08  0.02  0.27 -0.14
Social_Perceptiveness_Level             -0.01  0.89 -0.07 -0.10  0.04 -0.02
Coordination_Level                      -0.11  0.82  0.13  0.17  0.11 -0.11
Persuasion_Level                         0.05  1.00 -0.02  0.03 -0.23  0.04
Negotiation_Level                       -0.05  1.00 -0.05  0.08 -0.18  0.03
Instructing_Level                        0.29  0.31  0.04 -0.01  0.51  0.04
Service_Orientation_Level               -0.12  0.90 -0.11  0.00 -0.10  0.04
Complex_Problem_Solving_Level            0.69  0.34  0.09 -0.04  0.06  0.00
Operations_Analysis_Level                0.66  0.12 -0.02  0.15 -0.07 -0.06
Technology_Design_Level                  0.64  0.01  0.34  0.13 -0.18  0.04
Installation_Level                       0.03  0.00  0.71 -0.01  0.01  0.35
Programming_Level                        0.91 -0.25 -0.06  0.09 -0.14  0.08
Operations_Monitoring_Level              0.07  0.10  0.86 -0.10 -0.09 -0.40
Operation_and_Control_Level             -0.12  0.06  0.82 -0.10 -0.04 -0.31
Equipment_Maintenance_Level             -0.12 -0.05  0.99 -0.05  0.11  0.24
Troubleshooting_Level                   -0.01  0.04  0.97 -0.06 -0.03 -0.07
Repairing_Level                         -0.12 -0.01  1.01 -0.03  0.11  0.31
Quality_Control_Analysis_Level           0.19 -0.02  0.78  0.06 -0.07 -0.24
Judgment_and_Decision_Making_Level       0.58  0.42  0.01 -0.03  0.07 -0.01
Systems_Analysis_Level                   0.59  0.31  0.06  0.13  0.10  0.04
Systems_Evaluation_Level                 0.53  0.39  0.10  0.12  0.10  0.04
Time_Management_Level                    0.17  0.60  0.06  0.18  0.18 -0.02
Management_of_Financial_Resources_Level  0.05  0.18 -0.19  0.87 -0.04  0.06
Management_of_Material_Resources_Level   0.03  0.20  0.00  0.80  0.07  0.01
Management_of_Personnel_Resources_Level -0.01  0.60  0.09  0.33  0.27 -0.08
Equipment_Selection_Level                0.02 -0.05  0.94  0.02  0.02  0.15
                                          h2    u2 com
Reading_Comprehension_Level             0.92 0.082 1.4
Active_Listening_Level                  0.90 0.100 2.5
Writing_Level                           0.91 0.094 1.9
Speaking_Level                          0.92 0.082 2.8
Mathematical_Reasoning_Level            0.70 0.303 1.4
Science_Level                           0.68 0.323 1.3
Critical_Thinking_Level                 0.91 0.093 1.9
Active_Learning_Level                   0.92 0.079 1.6
Learning_Strategies_Level               0.88 0.118 2.4
Monitoring_Level                        0.86 0.136 2.5
Social_Perceptiveness_Level             0.84 0.159 1.0
Coordination_Level                      0.71 0.289 1.3
Persuasion_Level                        0.92 0.082 1.1
Negotiation_Level                       0.88 0.124 1.1
Instructing_Level                       0.86 0.138 2.3
Service_Orientation_Level               0.70 0.298 1.1
Complex_Problem_Solving_Level           0.90 0.102 1.5
Operations_Analysis_Level               0.63 0.370 1.2
Technology_Design_Level                 0.53 0.471 1.8
Installation_Level                      0.51 0.494 1.5
Programming_Level                       0.59 0.414 1.3
Operations_Monitoring_Level             0.94 0.058 1.5
Operation_and_Control_Level             0.85 0.147 1.4
Equipment_Maintenance_Level             0.94 0.059 1.2
Troubleshooting_Level                   0.94 0.063 1.0
Repairing_Level                         0.97 0.028 1.3
Quality_Control_Analysis_Level          0.81 0.185 1.3
Judgment_and_Decision_Making_Level      0.88 0.120 1.9
Systems_Analysis_Level                  0.86 0.142 1.7
Systems_Evaluation_Level                0.89 0.115 2.1
Time_Management_Level                   0.81 0.189 1.6
Management_of_Financial_Resources_Level 0.89 0.105 1.2
Management_of_Material_Resources_Level  0.84 0.162 1.1
Management_of_Personnel_Resources_Level 0.84 0.158 2.1
Equipment_Selection_Level               0.89 0.114 1.1

                       MR4  MR1  MR2  MR3  MR6  MR5
SS loadings           8.97 8.83 6.78 2.02 1.69 0.70
Proportion Var        0.26 0.25 0.19 0.06 0.05 0.02
Cumulative Var        0.26 0.51 0.70 0.76 0.81 0.83
Proportion Explained  0.31 0.30 0.23 0.07 0.06 0.02
Cumulative Proportion 0.31 0.61 0.85 0.92 0.98 1.00

 With factor correlations of
      MR4   MR1   MR2   MR3   MR6   MR5
MR4  1.00  0.68 -0.12  0.40  0.48  0.06
MR1  0.68  1.00 -0.44  0.33  0.55  0.08
MR2 -0.12 -0.44  1.00  0.24 -0.19 -0.23
MR3  0.40  0.33  0.24  1.00  0.11 -0.26
MR6  0.48  0.55 -0.19  0.11  1.00 -0.11
MR5  0.06  0.08 -0.23 -0.26 -0.11  1.00

Mean item complexity =  1.6
Test of the hypothesis that 6 factors are sufficient.

df null model =  595  with the objective function =  57.34 with Chi Square =  34201.2
df of  the model are 400  and the objective function was  5.46

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  610 with the empirical chi square  99.67  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  3233.75  with prob <  0

Tucker Lewis Index of factoring reliability =  0.874
RMSEA index =  0.108  and the 90 % confidence intervals are  0.104 0.111
BIC =  668.37
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR4  MR1  MR2  MR3  MR6 MR5
Correlation of (regression) scores with factors   0.99 0.96 0.99 0.95 0.94   1
Multiple R square of scores with factors          0.98 0.93 0.98 0.90 0.89   1
Minimum correlation of possible factor scores     0.96 0.86 0.96 0.80 0.77   1

$`2021`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR1   MR3   MR2   MR4   MR6   MR5
Reading_Comprehension_Level              0.78  0.16 -0.16 -0.15  0.11 -0.02
Active_Listening_Level                   0.53  0.50 -0.14 -0.21  0.00 -0.02
Writing_Level                            0.64  0.19 -0.19 -0.10  0.19 -0.09
Speaking_Level                           0.52  0.36 -0.20 -0.14  0.15 -0.07
Mathematical_Reasoning_Level             0.87 -0.28 -0.11  0.25  0.00  0.02
Science_Level                            0.96 -0.15  0.12 -0.20  0.07  0.18
Critical_Thinking_Level                  0.68  0.39 -0.04 -0.11  0.00 -0.02
Active_Learning_Level                    0.67  0.21 -0.07 -0.04  0.18 -0.05
Learning_Strategies_Level                0.40  0.15 -0.02  0.02  0.52 -0.09
Monitoring_Level                         0.34  0.43  0.08  0.01  0.32  0.16
Social_Perceptiveness_Level              0.02  0.88 -0.07 -0.12  0.05  0.03
Coordination_Level                      -0.09  0.77  0.12  0.17  0.13  0.12
Persuasion_Level                         0.04  1.01 -0.03  0.05 -0.22 -0.04
Negotiation_Level                       -0.05  0.98 -0.05  0.11 -0.17 -0.03
Instructing_Level                        0.35  0.23  0.05 -0.03  0.53 -0.03
Service_Orientation_Level               -0.08  0.90 -0.10 -0.03 -0.11 -0.03
Complex_Problem_Solving_Level            0.72  0.29  0.08 -0.02  0.06 -0.01
Operations_Analysis_Level                0.70  0.07 -0.02  0.17 -0.06  0.06
Technology_Design_Level                  0.69  0.06  0.34  0.09 -0.23 -0.01
Installation_Level                       0.03  0.00  0.72  0.00  0.00 -0.33
Programming_Level                        0.95 -0.26 -0.06  0.08 -0.16 -0.08
Operations_Monitoring_Level              0.07  0.09  0.83 -0.10 -0.08  0.44
Operation_and_Control_Level             -0.13  0.09  0.81 -0.12 -0.03  0.35
Equipment_Maintenance_Level             -0.12 -0.05  1.00 -0.05  0.12 -0.21
Troubleshooting_Level                    0.00  0.04  0.96 -0.06 -0.03  0.10
Repairing_Level                         -0.12 -0.03  1.02 -0.02  0.12 -0.28
Quality_Control_Analysis_Level           0.18 -0.05  0.76  0.09 -0.07  0.25
Judgment_and_Decision_Making_Level       0.60  0.35 -0.01  0.00  0.10  0.01
Systems_Analysis_Level                   0.61  0.27  0.08  0.12  0.11 -0.03
Systems_Evaluation_Level                 0.57  0.32  0.10  0.13  0.13 -0.03
Time_Management_Level                    0.18  0.55  0.06  0.20  0.21  0.00
Management_of_Financial_Resources_Level  0.03  0.17 -0.18  0.89 -0.06 -0.09
Management_of_Material_Resources_Level   0.04  0.18  0.01  0.79  0.06  0.00
Management_of_Personnel_Resources_Level  0.01  0.52  0.08  0.35  0.31  0.08
Equipment_Selection_Level                0.04 -0.05  0.94  0.01  0.00 -0.12
                                          h2    u2 com
Reading_Comprehension_Level             0.92 0.078 1.3
Active_Listening_Level                  0.90 0.105 2.5
Writing_Level                           0.91 0.094 1.7
Speaking_Level                          0.92 0.084 2.5
Mathematical_Reasoning_Level            0.71 0.286 1.4
Science_Level                           0.70 0.299 1.3
Critical_Thinking_Level                 0.90 0.096 1.7
Active_Learning_Level                   0.92 0.080 1.4
Learning_Strategies_Level               0.87 0.133 2.2
Monitoring_Level                        0.86 0.138 3.2
Social_Perceptiveness_Level             0.85 0.150 1.1
Coordination_Level                      0.71 0.294 1.3
Persuasion_Level                        0.91 0.087 1.1
Negotiation_Level                       0.87 0.130 1.1
Instructing_Level                       0.84 0.157 2.2
Service_Orientation_Level               0.70 0.304 1.1
Complex_Problem_Solving_Level           0.90 0.104 1.4
Operations_Analysis_Level               0.65 0.349 1.2
Technology_Design_Level                 0.56 0.436 1.8
Installation_Level                      0.50 0.497 1.4
Programming_Level                       0.62 0.376 1.2
Operations_Monitoring_Level             0.95 0.051 1.6
Operation_and_Control_Level             0.86 0.135 1.5
Equipment_Maintenance_Level             0.95 0.046 1.2
Troubleshooting_Level                   0.94 0.061 1.0
Repairing_Level                         0.97 0.025 1.2
Quality_Control_Analysis_Level          0.83 0.166 1.4
Judgment_and_Decision_Making_Level      0.88 0.124 1.7
Systems_Analysis_Level                  0.87 0.131 1.6
Systems_Evaluation_Level                0.89 0.113 1.9
Time_Management_Level                   0.81 0.188 1.8
Management_of_Financial_Resources_Level 0.91 0.094 1.2
Management_of_Material_Resources_Level  0.83 0.170 1.1
Management_of_Personnel_Resources_Level 0.84 0.160 2.6
Equipment_Selection_Level               0.88 0.123 1.0

                       MR1  MR3  MR2  MR4  MR6  MR5
SS loadings           9.68 7.93 6.75 2.11 1.91 0.76
Proportion Var        0.28 0.23 0.19 0.06 0.05 0.02
Cumulative Var        0.28 0.50 0.70 0.76 0.81 0.83
Proportion Explained  0.33 0.27 0.23 0.07 0.07 0.03
Cumulative Proportion 0.33 0.60 0.84 0.91 0.97 1.00

 With factor correlations of
      MR1   MR3   MR2  MR4   MR6   MR5
MR1  1.00  0.67 -0.14 0.42  0.50 -0.06
MR3  0.67  1.00 -0.45 0.36  0.61 -0.12
MR2 -0.14 -0.45  1.00 0.21 -0.26  0.25
MR4  0.42  0.36  0.21 1.00  0.17  0.28
MR6  0.50  0.61 -0.26 0.17  1.00  0.05
MR5 -0.06 -0.12  0.25 0.28  0.05  1.00

Mean item complexity =  1.6
Test of the hypothesis that 6 factors are sufficient.

df null model =  595  with the objective function =  57.81 with Chi Square =  34486.53
df of  the model are 400  and the objective function was  5.54

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  610 with the empirical chi square  96.04  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  3279.63  with prob <  0

Tucker Lewis Index of factoring reliability =  0.873
RMSEA index =  0.109  and the 90 % confidence intervals are  0.105 0.112
BIC =  714.24
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                  MR1 MR3 MR2 MR4 MR6 MR5
Correlation of (regression) scores with factors     1   1   1   1   1   1
Multiple R square of scores with factors            1   1   1   1   1   1
Minimum correlation of possible factor scores       1   1   1   1   1   1

$`2023`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR1   MR3   MR2   MR4   MR6   MR5
Reading_Comprehension_Level              0.78  0.16 -0.16 -0.16  0.10  0.01

### 5. Congruência de Tucker

In [14]:
factor.congruence(
  efa_by_year[["2017"]],
  efa_by_year[["2019"]]
)

factor.congruence(
  efa_by_year[["2019"]],
  efa_by_year[["2021"]]
)

factor.congruence(
  efa_by_year[["2021"]],
  efa_by_year[["2023"]]
)

factor.congruence(
  efa_by_year[["2023"]],
  efa_by_year[["2025"]]
)

    MR4   MR1   MR2   MR3   MR6   MR5
MR1  0.73  0.71 -0.03  0.01  0.67  0.01
MR2 -0.02 -0.02  1.00 -0.07  0.03  0.02
MR6  0.00  0.83 -0.07  0.04 -0.31  0.05
MR4  0.79 -0.09 -0.01  0.18 -0.29  0.03
MR3  0.01  0.18 -0.06  1.00  0.08  0.03
MR5  0.01  0.06  0.19 -0.09 -0.20 -0.97

    MR1   MR3   MR2   MR4   MR6  MR5
MR4  1.00  0.20 -0.03  0.02 0.26  0.02
MR1  0.27  1.00 -0.02  0.15 0.26  0.04
MR2 -0.03 -0.02  1.00 -0.06 0.02  0.10
MR3  0.01  0.13 -0.06  1.00 0.03 -0.08
MR6  0.28  0.15  0.02  0.04 1.00 -0.13
MR5 -0.01 -0.03  0.01  0.05 0.11 -0.99

    MR1   MR3   MR2   MR4   MR6   MR5
MR1  1.00  0.22 -0.03  0.02  0.26 -0.01
MR3  0.22  1.00 -0.03  0.14  0.18 -0.03
MR2 -0.03 -0.02  1.00 -0.06  0.01  0.01
MR4  0.02  0.14 -0.06  1.00  0.02  0.07
MR6  0.29  0.20  0.03  0.03  1.00  0.09
MR5  0.01  0.05  0.10 -0.07 -0.11 -0.99

    MR1   MR3   MR2   MR4   MR6  MR5
MR1  1.00  0.27 -0.03  0.02 0.30 -0.02
MR3  0.18  1.00 -0.02  0.15 0.15 -0.04
MR2 -0.02 -0.03  1.00 -0.06 0.01  0.02
MR4  0.03  0.15 -0.06  1.00 0.03  0.06
MR6  0.21  0.25  0.00  0.01 0.99  0.11
MR5 -0.02 -0.03  0.00  0.06 0.11  1.00

In [15]:
print(factor.congruence(efa_by_year))

      MR1   MR2   MR6   MR4   MR3   MR5   MR4   MR1   MR2   MR3   MR6   MR5
MR1  1.00 -0.02  0.27  0.19  0.04 -0.04  0.73  0.71 -0.03  0.01  0.67  0.01
MR2 -0.02  1.00 -0.07  0.00 -0.06  0.17 -0.02 -0.02  1.00 -0.07  0.03  0.02
MR6  0.27 -0.07  1.00 -0.03  0.06  0.01  0.00  0.83 -0.07  0.04 -0.31  0.05
MR4  0.19  0.00 -0.03  1.00  0.15 -0.01  0.79 -0.09 -0.01  0.18 -0.29  0.03
MR3  0.04 -0.06  0.06  0.15  1.00 -0.07  0.01  0.18 -0.06  1.00  0.08  0.03
MR5 -0.04  0.17  0.01 -0.01 -0.07  1.00  0.01  0.06  0.19 -0.09 -0.20 -0.97
MR4  0.73 -0.02  0.00  0.79  0.01  0.01  1.00  0.25 -0.03  0.01  0.26 -0.02
MR1  0.71 -0.02  0.83 -0.09  0.18  0.06  0.25  1.00 -0.02  0.14  0.22 -0.03
MR2 -0.03  1.00 -0.07 -0.01 -0.06  0.19 -0.03 -0.02  1.00 -0.07  0.01  0.00
MR3  0.01 -0.07  0.04  0.18  1.00 -0.09  0.01  0.14 -0.07  1.00  0.05  0.06
MR6  0.67  0.03 -0.31 -0.29  0.08 -0.20  0.26  0.22  0.01  0.05  1.00  0.14
MR5  0.01  0.02  0.05  0.03  0.03 -0.97 -0.02 -0.03  0.00  0.06  0.14  1.00
MR1  0.74 -0.02  0.01  0.77  0.01  0.00  1.00  0.27 -0.03  0.01  0.28 -0.01
MR3  0.65 -0.02  0.87 -0.11  0.17  0.06  0.20  1.00 -0.02  0.13  0.15 -0.03
MR2 -0.03  1.00 -0.07 -0.01 -0.06  0.18 -0.03 -0.02  1.00 -0.06  0.02  0.01
MR4  0.02 -0.06  0.05  0.18  1.00 -0.08  0.02  0.15 -0.06  1.00  0.04  0.05
MR6  0.69  0.03 -0.27 -0.31  0.06 -0.16  0.26  0.26  0.02  0.03  1.00  0.11
MR5 -0.01  0.08 -0.05 -0.04 -0.06  0.98  0.02  0.04  0.10 -0.08 -0.13 -0.99
MR1  0.75 -0.02  0.01  0.77  0.01  0.00  1.00  0.27 -0.03  0.01  0.29 -0.01
MR3  0.65 -0.02  0.87 -0.11  0.17  0.07  0.20  1.00 -0.02  0.13  0.16 -0.04
MR2 -0.03  1.00 -0.08 -0.01 -0.06  0.19 -0.03 -0.02  1.00 -0.06  0.02  0.00
MR4  0.03 -0.06  0.04  0.18  0.99 -0.07  0.02  0.15 -0.06  1.00  0.05  0.04
MR6  0.67  0.01 -0.28 -0.33  0.05 -0.17  0.24  0.25  0.00  0.02  0.99  0.11
MR5  0.00  0.01  0.06  0.04  0.05 -0.97 -0.02 -0.03 -0.01  0.07  0.11  1.00
MR1  0.71 -0.02  0.00  0.81  0.02  0.01  1.00  0.24 -0.02  0.02  0.24 -0.01
MR3  0.70 -0.02  0.83 -0.10  0.18  0.06  0.25  1.00 -0.02  0.13  0.22 -0.04
MR2 -0.03  1.00 -0.07 -0.01 -0.06  0.19 -0.03 -0.02  1.00 -0.07  0.01  0.00
MR4  0.02 -0.06  0.06  0.18  0.99 -0.07  0.02  0.16 -0.06  1.00  0.03  0.04
MR6  0.67  0.01 -0.31 -0.28  0.06 -0.19  0.27  0.21  0.00  0.03  1.00  0.13
MR5  0.01  0.04  0.05  0.03  0.05 -0.96 -0.02 -0.03  0.02  0.07  0.13  1.00
      MR1   MR3   MR2   MR4   MR6   MR5   MR1   MR3   MR2   MR4   MR6   MR5
MR1  0.74  0.65 -0.03  0.02  0.69 -0.01  0.75  0.65 -0.03  0.03  0.67  0.00
MR2 -0.02 -0.02  1.00 -0.06  0.03  0.08 -0.02 -0.02  1.00 -0.06  0.01  0.01
MR6  0.01  0.87 -0.07  0.05 -0.27 -0.05  0.01  0.87 -0.08  0.04 -0.28  0.06
MR4  0.77 -0.11 -0.01  0.18 -0.31 -0.04  0.77 -0.11 -0.01  0.18 -0.33  0.04
MR3  0.01  0.17 -0.06  1.00  0.06 -0.06  0.01  0.17 -0.06  0.99  0.05  0.05
MR5  0.00  0.06  0.18 -0.08 -0.16  0.98  0.00  0.07  0.19 -0.07 -0.17 -0.97
MR4  1.00  0.20 -0.03  0.02  0.26  0.02  1.00  0.20 -0.03  0.02  0.24 -0.02
MR1  0.27  1.00 -0.02  0.15  0.26  0.04  0.27  1.00 -0.02  0.15  0.25 -0.03
MR2 -0.03 -0.02  1.00 -0.06  0.02  0.10 -0.03 -0.02  1.00 -0.06  0.00 -0.01
MR3  0.01  0.13 -0.06  1.00  0.03 -0.08  0.01  0.13 -0.06  1.00  0.02  0.07
MR6  0.28  0.15  0.02  0.04  1.00 -0.13  0.29  0.16  0.02  0.05  0.99  0.11
MR5 -0.01 -0.03  0.01  0.05  0.11 -0.99 -0.01 -0.04  0.00  0.04  0.11  1.00
MR1  1.00  0.22 -0.03  0.02  0.28  0.01  1.00  0.22 -0.03  0.02  0.26 -0.01
MR3  0.22  1.00 -0.02  0.14  0.19  0.04  0.22  1.00 -0.03  0.14  0.18 -0.03
MR2 -0.03 -0.02  1.00 -0.06  0.02  0.08 -0.03 -0.02  1.00 -0.06  0.01  0.01
MR4  0.02  0.14 -0.06  1.00  0.03 -0.08  0.02  0.14 -0.06  1.00  0.02  0.07
MR6  0.28  0.19  0.02  0.03  1.00 -0.10  0.29  0.20  0.03  0.03  1.00  0.09
MR5  0.01  0.04  0.08 -0.08 -0.10  1.00  0.01  0.05  0.10 -0.07 -0.11 -0.99
MR1  1.00  0.22 -0.03  0.02  0.29  0.01  1.00  0.22 -0.03  0.02  0.26 -0.02
MR3  0.22  1.00 -0.02  0.14  0.20  0.05  0.22  1.00 -0.03  0.14  0.19 -0.04
MR2 -0.03 -0.03  1.00 -0.06  0.03  0.10 -0.03 -0.03  1.00 -0.06  0.01 -0.01
MR4  0.02  0.14 -0.06  1.00  0.03 -0.07  0.02  0.14 -0.06  1.00  0.03  0.06
MR6  0.26  0.18  0.01  0.02  1.00 -0.11  0.26  0.19  0.01  0.03  1.00  0.09
MR5 -0.01 -0.03  0.01  0.07  0.09 -0.99 -0.02 -0.04 -0.01  0.06  0.09  1.00
MR1  1.00  0.19 -0.02  0.03  0.23  0.01  1.00  0.18 -0.02  0.03  0.21 -0.02
MR3  0.27  1.00 -0.02  0.14  0.26  0.04  0.27  1.00 -0.03  0.15  0.25 -0.03
MR2 -0.03 -0.02  1.00 -0.07  0.02  0.09 -0.03 -0.02  1.00 -0.06  0.00  0.00
MR4  0.02  0.15 -0.06  1.00  0.02 -0.07  0.02  0.15 -0.06  1.00  0.01  0.06
MR6  0.29  0.14  0.01  0.02  0.99 -0.12  0.30  0.15  0.01  0.03  0.99  0.11
MR5 -0.02 -0.03  0.04  0.07  0.10 -0.99 -0.02 -0.04  0.02  0.06  0.11  1.00
      MR1   MR3   MR2   MR4   MR6   MR5
MR1  0.71  0.70 -0.03  0.02  0.67  0.01
MR2 -0.02 -0.02  1.00 -0.06  0.01  0.04
MR6  0.00  0.83 -0.07  0.06 -0.31  0.05
MR4  0.81 -0.10 -0.01  0.18 -0.28  0.03
MR3  0.02  0.18 -0.06  0.99  0.06  0.05
MR5  0.01  0.06  0.19 -0.07 -0.19 -0.96
MR4  1.00  0.25 -0.03  0.02  0.27 -0.02
MR1  0.24  1.00 -0.02  0.16  0.21 -0.03
MR2 -0.02 -0.02  1.00 -0.06  0.00  0.02
MR3  0.02  0.13 -0.07  1.00  0.03  0.07
MR6  0.24  0.22  0.01  0.03  1.00  0.13
MR5 -0.01 -0.04  0.00  0.04  0.13  1.00
MR1  1.00  0.27 -0.03  0.02  0.29 -0.02
MR3  0.19  1.00 -0.02  0.15  0.14 -0.03
MR2 -0.02 -0.02  1.00 -0.06  0.01  0.04
MR4  0.03  0.14 -0.07  1.00  0.02  0.07
MR6  0.23  0.26  0.02  0.02  0.99  0.10
MR5  0.01  0.04  0.09 -0.07 -0.12 -0.99
MR1  1.00  0.27 -0.03  0.02  0.30 -0.02
MR3  0.18  1.00 -0.02  0.15  0.15 -0.04
MR2 -0.02 -0.03  1.00 -0.06  0.01  0.02
MR4  0.03  0.15 -0.06  1.00  0.03  0.06
MR6  0.21  0.25  0.00  0.01  0.99  0.11
MR5 -0.02 -0.03  0.00  0.06  0.11  1.00
MR1  1.00  0.23 -0.02  0.03  0.24 -0.02
MR3  0.23  1.00 -0.02  0.15  0.21 -0.03
MR2 -0.02 -0.02  1.00 -0.06  0.00  0.03
MR4  0.03  0.15 -0.06  1.00  0.01  0.06
MR6  0.24  0.21  0.00  0.01  1.00  0.12
MR5 -0.02 -0.03  0.03  0.06  0.12  1.00

### 6. Carga Fatorial por Ano

In [17]:
loadings_year <- lapply(
  efa_by_year,
  function(x){
    as.data.frame(unclass(x$loadings))
  }
)

loadings_year

$`2017`
                                                 MR1          MR2          MR6
Reading_Comprehension_Level              0.821354990 -0.155191007 -0.004756655
Active_Listening_Level                   0.708787880 -0.153402730  0.260473508
Writing_Level                            0.877088971 -0.178408942 -0.020213036
Speaking_Level                           0.816048081 -0.182467518  0.140976235
Mathematical_Reasoning_Level             0.344357436 -0.108738753 -0.203668303
Science_Level                            0.728186852  0.108693656 -0.226354190
Critical_Thinking_Level                  0.725142721 -0.030069295  0.197737784
Active_Learning_Level                    0.855506721 -0.058246786 -0.002779419
Learning_Strategies_Level                1.068560005 -0.016503466 -0.167453492
Monitoring_Level                         0.970595763  0.075372513  0.008469489
Social_Perceptiveness_Level              0.646933946 -0.065472052  0.437953742
Coordination_Level                       0.608210965  0.118929936  0.294878097
Persuasion_Level                         0.379251207 -0.030120578  0.627742860
Negotiation_Level                        0.331003124 -0.043275931  0.636373327
Instructing_Level                        1.140863472  0.063972778 -0.164956413
Service_Orientation_Level                0.312535713 -0.120594828  0.552050381
Complex_Problem_Solving_Level            0.768101073  0.090113127  0.080813951
Operations_Analysis_Level                0.438425491 -0.036598761 -0.025272171
Technology_Design_Level                  0.032144825  0.357037550  0.135364605
Installation_Level                      -0.002286442  0.683518977  0.040551758
Programming_Level                        0.090905829 -0.039231883 -0.011872776
Operations_Monitoring_Level             -0.066614092  0.804927301  0.048766957
Operation_and_Control_Level             -0.102916972  0.771720829 -0.009156617
Equipment_Maintenance_Level              0.057205583  0.966362477 -0.065722673
Troubleshooting_Level                   -0.054583057  0.932680762  0.018141800
Repairing_Level                          0.059211193  0.998410335 -0.028709072
Quality_Control_Analysis_Level           0.073568448  0.736538500 -0.104876886
Judgment_and_Decision_Making_Level       0.780150794  0.008927700  0.115370494
Systems_Analysis_Level                   0.690926341  0.061037759  0.054142463
Systems_Evaluation_Level                 0.735669717  0.110261159  0.102611498
Time_Management_Level                    0.773070701  0.054708187  0.122369287
Management_of_Financial_Resources_Level -0.110671677 -0.185160265  0.071860306
Management_of_Material_Resources_Level   0.095230331 -0.006202348 -0.019512774
Management_of_Personnel_Resources_Level  0.775897638  0.079901202  0.043169816
Equipment_Selection_Level               -0.009106780  0.922945263 -0.044419575
                                                MR4          MR3          MR5
Reading_Comprehension_Level              0.23485216 -0.158321324 -0.026393410
Active_Listening_Level                   0.14204597 -0.210102709 -0.023889142
Writing_Level                            0.11410088 -0.112680651 -0.090099212
Speaking_Level                           0.06516428 -0.148965829 -0.071084926
Mathematical_Reasoning_Level             0.52081566  0.241454952  0.024742209
Science_Level                            0.32256753 -0.201962973  0.138592447
Critical_Thinking_Level                  0.24425545 -0.140901021  0.009094062
Active_Learning_Level                    0.17511589 -0.029144945 -0.043135977
Learning_Strategies_Level               -0.15664998  0.070436215 -0.107872038
Monitoring_Level                        -0.13142525  0.034692062  0.134130354
Social_Perceptiveness_Level             -0.15344494 -0.080787551  0.027268598
Coordination_Level                      -0.22152251  0.204632748  0.110321269
Persuasion_Level                         0.04063772  0.047149457 -0.001139938
Negotiation_Level                       -0.01910203  0.095519789  0.012664617
Instructing_Level                       -0.23126163  0.014643476 -0.058415227
Service_Orientation_Level               -0.05908507  0.020097440 -0.034931902
Complex_Problem_Solving_Level            0.25989930 -0.038709723  0.007901211
Operations_Analysis_Level                0.34759614  0.168246221  0.019426122
Technology_Design_Level                  0.51315398  0.133484449 -0.009216558
Installation_Level                       0.07292861 -0.008362665 -0.286796184
Programming_Level                        0.65818418  0.048646456 -0.032959776
Operations_Monitoring_Level              0.05421885 -0.097289270  0.478953764
Operation_and_Control_Level             -0.08372176 -0.082833985  0.366088853
Equipment_Maintenance_Level             -0.08631229 -0.061258158 -0.169137450
Troubleshooting_Level                    0.02939088 -0.060744869  0.139542900
Repairing_Level                         -0.07793781 -0.046783555 -0.238327696
Quality_Control_Analysis_Level           0.12387592  0.066142450  0.253988433
Judgment_and_Decision_Making_Level       0.15870157 -0.014480598  0.003903410
Systems_Analysis_Level                   0.23267695  0.124729620 -0.030417607
Systems_Evaluation_Level                 0.17121865  0.116039763 -0.022521556
Time_Management_Level                   -0.10264505  0.207720714  0.006353110
Management_of_Financial_Resources_Level  0.23960644  0.889680100 -0.060990964
Management_of_Material_Resources_Level   0.11083311  0.843972447 -0.028472308
Management_of_Personnel_Resources_Level -0.23904573  0.361798237  0.062854179
Equipment_Selection_Level                0.02922158  0.018799155 -0.109699462

$`2019`
                                                 MR4          MR1          MR2
Reading_Comprehension_Level              0.741381227  0.204465291 -0.161392820
Active_Listening_Level                   0.498383984  0.529125486 -0.150789196
Writing_Level                            0.601828884  0.245225124 -0.189014493
Speaking_Level                           0.471255587  0.424766738 -0.195510004
Mathematical_Reasoning_Level             0.858183574 -0.263213791 -0.114208916
Science_Level                            0.922140090 -0.127821526  0.127011819
Critical_Thinking_Level                  0.642063435  0.445969283 -0.028068467
Active_Learning_Level                    0.632549137  0.273363539 -0.073511860
Learning_Strategies_Level                0.332240354  0.244454220 -0.036568358
Monitoring_Level                         0.317367102  0.507795949  0.076143793
Social_Perceptiveness_Level             -0.012689180  0.894161144 -0.068898145
Coordination_Level                      -0.113335664  0.819380631  0.128583315
Persuasion_Level                         0.049917961  1.003970309 -0.020856023
Negotiation_Level                       -0.049780115  0.998698046 -0.046996750
Instructing_Level                        0.290143325  0.313736362  0.044943062
Service_Orientation_Level               -0.118908050  0.901137109 -0.108056770
Complex_Problem_Solving_Level            0.688050609  0.339494168  0.089079782
Operations_Analysis_Level                0.663444371  0.115600715 -0.020191575
Technology_Design_Level                  0.642075601  0.014131364  0.342857524
Installation_Level                       0.032025121 -0.003296157  0.710500934
Programming_Level                        0.913654166 -0.254470895 -0.062819717
Operations_Monitoring_Level              0.072054313  0.099770529  0.860273401
Operation_and_Control_Level             -0.119039046  0.063868852  0.823406169
Equipment_Maintenance_Level             -0.115581702 -0.046127629  0.985100902
Troubleshooting_Level                   -0.010234605  0.039954731  0.974648485
Repairing_Level                         -0.124861337 -0.013838417  1.012129905
Quality_Control_Analysis_Level           0.192694789 -0.024394231  0.783287293
Judgment_and_Decision_Making_Level       0.575276702  0.417233098  0.007663098
Systems_Analysis_Level                   0.586173427  0.305763885  0.061574475
Systems_Evaluation_Level                 0.530713023  0.393379528  0.099835917
Time_Management_Level                    0.168492323  0.602221132  0.062983562
Management_of_Financial_Resources_Level  0.045734124  0.178984105 -0.192640828
Management_of_Material_Resources_Level   0.026064721  0.198963672  0.003267275
Management_of_Personnel_Resources_Level -0.008934635  0.600713088  0.086594595
Equipment_Selection_Level                0.015203536 -0.050406007  0.943229795
                                                  MR3          MR6
Reading_Comprehension_Level             -0.1533685609  0.101862303
Active_Listening_Level                  -0.2100376435 -0.008386365
Writing_Level                           -0.1067616053  0.188693120
Speaking_Level                          -0.1429155825  0.133271385
Mathematical_Reasoning_Level             0.2465349608  0.018419162
Science_Level                           -0.2003020630  0.083874967
Critical_Thinking_Level                 -0.1263751378 -0.022442466
Active_Learning_Level                   -0.0327269767  0.174137841
Learning_Strategies_Level                0.0497443651  0.504697628
Monitoring_Level                         0.0159828297  0.267505693
Social_Perceptiveness_Level             -0.1001055647  0.044772950
Coordination_Level                       0.1655354654  0.109332580
Persuasion_Level                         0.0308895872 -0.225798049
Negotiation_Level                        0.0819606902 -0.178470430
Instructing_Level                       -0.0085211459  0.514187661
Service_Orientation_Level               -0.0006132533 -0.103639225
Complex_Problem_Solving_Level           -0.0404479726  0.055665689
Operations_Analysis_Level                0.1513928115 -0.065665481
Technology_Design_Level                  0.1325033458 -0.177499183
Installation_Level                      -0.0078592847  0.010093636
Programming_Level                        0.0886412385 -0.144378414
Operations_Monitoring_Level             -0.0993071585 -0.094724623
Operation_and_Control_Level             -0.0980130937 -0.042909193
Equipment_Maintenance_Level             -0.0459814748  0.111173501
Troubleshooting_Level                   -0.0605041117 -0.029977800
Repairing_Level                         -0.0319729385  0.111085154
Quality_Control_Analysis_Level           0.0620784138 -0.065420435
Judgment_and_Decision_Making_Level      -0.0262328228  0.069581651
Systems_Analysis_Level                   0.1259394116  0.095041652
Systems_Evaluation_Level                 0.1150377595  0.102156294
Time_Management_Level                    0.1782686195  0.178987969
Management_of_Financial_Resources_Level  0.8707440194 -0.038698612
Management_of_Material_Resources_Level   0.7971622742  0.072824165
Management_of_Personnel_Resources_Level  0.3262887573  0.271135529
Equipment_Selection_Level                0.0157658778  0.015148232
                                                  MR5
Reading_Comprehension_Level              0.0190575573
Active_Listening_Level                   0.0257216889
Writing_Level                            0.0782812074
Speaking_Level                           0.0731195186
Mathematical_Reasoning_Level            -0.0281521461
Science_Level                           -0.1685634825
Critical_Thinking_Level                 -0.0007873820
Active_Learning_Level                    0.0399655599
Learning_Strategies_Level                0.0898600316
Monitoring_Level                        -0.1423544169
Social_Perceptiveness_Level             -0.0162808189
Coordination_Level                      -0.1126426566
Persuasion_Level                         0.0355235810
Negotiation_Level                        0.0257785893
Instructing_Level                        0.0428886175
Service_Orientation_Level                0.0427088042
Complex_Problem_Solving_Level            0.0006563837
Operations_Analysis_Level               -0.0599906314
Technology_Design_Level                  0.0359859655
Installation_Level                       0.3496220962
Programming_Level                        0.0815319627
Operations_Monitoring_Level             -0.4047978110
Operation_and_Control_Level             -0.3078276249
Equipment_Maintenance_Level              0.2398718961
Troubleshooting_Level                   -0.0682248463
Repairing_Level                          0.3123573524
Quality_Control_Analysis_Level          -0.2355558498
Judgment_and_Decision_Making_Level      -0.0133645386
Systems_Analysis_Level                   0.0401993889
Systems_Evaluation_Level                 0.0393326171
Time_Management_Level                   -0.0225730841
Management_of_Financial_Resources_Level  0.0622237413
Management_of_Material_Resources_Level   0.0066154987
Management_of_Personnel_Resources_Level -0.0816313146
Equipment_Selection_Level                0.1498994170

$`2021`
                                                 MR1          MR3          MR2
Reading_Comprehension_Level              0.775229186  0.162093484 -0.161604629
Active_Listening_Level                   0.531163918  0.497977136 -0.144205079
Writing_Level                            0.639245112  0.191278795 -0.190607534
Speaking_Level                           0.520015452  0.364355729 -0.195173706
Mathematical_Reasoning_Level             0.870841365 -0.276703803 -0.111360282
Science_Level                            0.957702663 -0.150992967  0.120380640
Critical_Thinking_Level                  0.675211458  0.391836525 -0.035006827
Active_Learning_Level                    0.673411125  0.214485739 -0.070628207
Learning_Strategies_Level                0.397349401  0.153472192 -0.022208740
Monitoring_Level                         0.343628769  0.432659381  0.076249728
Social_Perceptiveness_Level              0.023358933  0.880122913 -0.069456260
Coordination_Level                      -0.093327926  0.774597131  0.117214137
Persuasion_Level                         0.038682462  1.008504262 -0.032160107
Negotiation_Level                       -0.047118606  0.984946961 -0.052328784
Instructing_Level                        0.345561292  0.227221628  0.052965914
Service_Orientation_Level               -0.077944412  0.899651317 -0.098697862
Complex_Problem_Solving_Level            0.715563398  0.286305957  0.075541728
Operations_Analysis_Level                0.700546768  0.066097517 -0.021350082
Technology_Design_Level                  0.693575515  0.057700675  0.343531437
Installation_Level                       0.031718634 -0.002915768  0.719294344
Programming_Level                        0.947571912 -0.256620085 -0.060383916
Operations_Monitoring_Level              0.073864155  0.091546798  0.826172721
Operation_and_Control_Level             -0.130562614  0.087547950  0.811983540
Equipment_Maintenance_Level             -0.118034281 -0.052316245  0.998181687
Troubleshooting_Level                   -0.001726293  0.040881902  0.962963339
Repairing_Level                         -0.120680525 -0.028859200  1.019983906
Quality_Control_Analysis_Level           0.184780238 -0.045244730  0.760538484
Judgment_and_Decision_Making_Level       0.595728509  0.354851630 -0.005513341
Systems_Analysis_Level                   0.612015822  0.272508910  0.078925225
Systems_Evaluation_Level                 0.568631766  0.322144934  0.097777833
Time_Management_Level                    0.176546698  0.548034447  0.055739599
Management_of_Financial_Resources_Level  0.033448102  0.174821531 -0.181050493
Management_of_Material_Resources_Level   0.043133794  0.175801014  0.008610103
Management_of_Personnel_Resources_Level  0.005846454  0.520926328  0.080905761
Equipment_Selection_Level                0.037591239 -0.053946122  0.937243746
                                                 MR4           MR6          MR5
Reading_Comprehension_Level             -0.152741599  0.1086327483 -0.019288103
Active_Listening_Level                  -0.206332535  0.0048916821 -0.023804967
Writing_Level                           -0.102646754  0.1914485369 -0.087879131
Speaking_Level                          -0.141004550  0.1473413623 -0.065448011
Mathematical_Reasoning_Level             0.254315407  0.0006130037  0.020136940
Science_Level                           -0.200258422  0.0746421930  0.179574435
Critical_Thinking_Level                 -0.111541608 -0.0027917008 -0.015487089
Active_Learning_Level                   -0.035436758  0.1841107185 -0.045120708
Learning_Strategies_Level                0.024490580  0.5161467357 -0.086405938
Monitoring_Level                         0.011189244  0.3170047776  0.160329688
Social_Perceptiveness_Level             -0.121861254  0.0479279702  0.028272819
Coordination_Level                       0.173045827  0.1268941409  0.120115889
Persuasion_Level                         0.052018001 -0.2225533298 -0.039332769
Negotiation_Level                        0.105755470 -0.1677757321 -0.034652191
Instructing_Level                       -0.027435579  0.5293289586 -0.034766536
Service_Orientation_Level               -0.032282260 -0.1105149565 -0.026370984
Complex_Problem_Solving_Level           -0.015421293  0.0632813636 -0.005421675
Operations_Analysis_Level                0.165920427 -0.0586567568  0.059329006
Technology_Design_Level                  0.093528170 -0.2315263474 -0.008023094
Installation_Level                      -0.001767056 -0.0026889021 -0.326187158
Programming_Level                        0.081456687 -0.1595763789 -0.078689080
Operations_Monitoring_Level             -0.097444189 -0.0774292415  0.441734045
Operation_and_Control_Level             -0.115897343 -0.0321472108  0.345616842
Equipment_Maintenance_Level             -0.048542343  0.1219799641 -0.214854381
Troubleshooting_Level                   -0.061375930 -0.0340662581  0.095026726
Repairing_Level                         -0.022744010  0.1207755587 -0.280579931
Quality_Control_Analysis_Level           0.091970529 -0.0688790273  0.251348643
Judgment_and_Decision_Making_Level      -0.002493220  0.0995003834  0.005916462
Systems_Analysis_Level                   0.123321977  0.1091747973 -0.034952971
Systems_Evaluation_Level                 0.127109333  0.1267445304 -0.034426153
Time_Management_Level                    0.202018285  0.2050858149  0.003517980
Management_of_Financial_Resources_Level  0.888549021 -0.0552018899 -0.085946909
Management_of_Material_Resources_Level   0.791275981  0.0579761826 -0.003932614
Management_of_Personnel_Resources_Level  0.349678344  0.3054130000  0.076812085
Equipment_Selection_Level                0.007011146 -0.0023792089 -0.116482873

$`2023`
                                                 MR1          MR3          MR2
Reading_Comprehension_Level              0.784413327  0.158066369 -0.163854182
Active_Listening_Level                   0.535105223  0.499117113 -0.143239189
Writing_Level                            0.648708091  0.178199419 -0.198809818
Speaking_Level                           0.529619612  0.360549487 -0.198438515
Mathematical_Reasoning_Level             0.880396164 -0.283311393 -0.108304499
Science_Level                            0.977511875 -0.157639890  0.130841842
Critical_Thinking_Level                  0.684653067  0.389320041 -0.032818455
Active_Learning_Level                    0.682535309  0.214646424 -0.071289050
Learning_Strategies_Level                0.412153755  0.152806003 -0.024634648
Monitoring_Level                         0.357836857  0.439735885  0.080535975
Social_Perceptiveness_Level              0.027474457  0.889848372 -0.067865901
Coordination_Level                      -0.095564912  0.796482764  0.130983917
Persuasion_Level                         0.028234006  0.995160323 -0.050757924
Negotiation_Level                       -0.052712360  0.970986920 -0.071344379
Instructing_Level                        0.353317788  0.247140373  0.057792258
Service_Orientation_Level               -0.084270452  0.901192871 -0.101700126

In [18]:
cargas_long <- bind_rows(
  lapply(names(loadings_year), function(y){

    loadings_year[[y]] %>%
      tibble::rownames_to_column("skill") %>%
      pivot_longer(
        starts_with("MR"),
        names_to = "factor",
        values_to = "loading"
      ) %>%
      mutate(year = y)

  })
)

print(cargas_long, n = Inf, width = Inf)

# A tibble: 1,050 × 4
     skill                                   factor    loading year
     <chr>                                   <chr>       <dbl> <chr>
   1 Reading_Comprehension_Level             MR1     0.821     2017
   2 Reading_Comprehension_Level             MR2    -0.155     2017
   3 Reading_Comprehension_Level             MR6    -0.00476   2017
   4 Reading_Comprehension_Level             MR4     0.235     2017
   5 Reading_Comprehension_Level             MR3    -0.158     2017
   6 Reading_Comprehension_Level             MR5    -0.0264    2017
   7 Active_Listening_Level                  MR1     0.709     2017
   8 Active_Listening_Level                  MR2    -0.153     2017
   9 Active_Listening_Level                  MR6     0.260     2017
  10 Active_Listening_Level                  MR4     0.142     2017
  11 Active_Listening_Level                  MR3    -0.210     2017
  12 Active_Listening_Level                  MR5    -0.0239    2017
  13 Writing_Level                           MR1     0.877     2017
  14 Writing_Level                           MR2    -0.178     2017
  15 Writing_Level                           MR6    -0.0202    2017
  16 Writing_Level                           MR4     0.114     2017
  17 Writing_Level                           MR3    -0.113     2017
  18 Writing_Level                           MR5    -0.0901    2017
  19 Speaking_Level                          MR1     0.816     2017
  20 Speaking_Level                          MR2    -0.182     2017
  21 Speaking_Level                          MR6     0.141     2017
  22 Speaking_Level                          MR4     0.0652    2017
  23 Speaking_Level                          MR3    -0.149     2017
  24 Speaking_Level                          MR5    -0.0711    2017
  25 Mathematical_Reasoning_Level            MR1     0.344     2017
  26 Mathematical_Reasoning_Level            MR2    -0.109     2017
  27 Mathematical_Reasoning_Level            MR6    -0.204     2017
  28 Mathematical_Reasoning_Level            MR4     0.521     2017
  29 Mathematical_Reasoning_Level            MR3     0.241     2017
  30 Mathematical_Reasoning_Level            MR5     0.0247    2017
  31 Science_Level                           MR1     0.728     2017
  32 Science_Level                           MR2     0.109     2017
  33 Science_Level                           MR6    -0.226     2017
  34 Science_Level                           MR4     0.323     2017
  35 Science_Level                           MR3    -0.202     2017
  36 Science_Level                           MR5     0.139     2017
  37 Critical_Thinking_Level                 MR1     0.725     2017
  38 Critical_Thinking_Level                 MR2    -0.0301    2017
  39 Critical_Thinking_Level                 MR6     0.198     2017
  40 Critical_Thinking_Level                 MR4     0.244     2017
  41 Critical_Thinking_Level                 MR3    -0.141     2017
  42 Critical_Thinking_Level                 MR5     0.00909   2017
  43 Active_Learning_Level                   MR1     0.856     2017
  44 Active_Learning_Level                   MR2    -0.0582    2017
  45 Active_Learning_Level                   MR6    -0.00278   2017
  46 Active_Learning_Level                   MR4     0.175     2017
  47 Active_Learning_Level                   MR3    -0.0291    2017
  48 Active_Learning_Level                   MR5    -0.0431    2017
  49 Learning_Strategies_Level               MR1     1.07      2017
  50 Learning_Strategies_Level               MR2    -0.0165    2017
  51 Learning_Strategies_Level               MR6    -0.167     2017
  52 Learning_Strategies_Level               MR4    -0.157     2017
  53 Learning_Strategies_Level               MR3     0.0704    2017
  54 Learning_Strategies_Level               MR5    -0.108     2017
  55 Monitoring_Level                        MR1     0.971     2017
  56 Monitoring_Level                        MR2     0.0754    2017
  57 Monitoring_Level                        MR6     0.00847   2017
  58 Monitoring_Level                        MR4    -0.131     2017
  59 Monitoring_Level                        MR3     0.0347    2017
  60 Monitoring_Level                        MR5     0.134     2017
  61 Social_Perceptiveness_Level             MR1     0.647     2017
  62 Social_Perceptiveness_Level             MR2    -0.0655    2017
  63 Social_Perceptiveness_Level             MR6     0.438     2017
  64 Social_Perceptiveness_Level             MR4    -0.153     2017
  65 Social_Perceptiveness_Level             MR3    -0.0808    2017
  66 Social_Perceptiveness_Level             MR5     0.0273    2017
  67 Coordination_Level                      MR1     0.608     2017
  68 Coordination_Level                      MR2     0.119     2017
  69 Coordination_Level                      MR6     0.295     2017
  70 Coordination_Level                      MR4    -0.222     2017
  71 Coordination_Level                      MR3     0.205     2017
  72 Coordination_Level                      MR5     0.110     2017
  73 Persuasion_Level                        MR1     0.379     2017
  74 Persuasion_Level                        MR2    -0.0301    2017
  75 Persuasion_Level                        MR6     0.628     2017
  76 Persuasion_Level                        MR4     0.0406    2017
  77 Persuasion_Level                        MR3     0.0471    2017
  78 Persuasion_Level                        MR5    -0.00114   2017
  79 Negotiation_Level                       MR1     0.331     2017
  80 Negotiation_Level                       MR2    -0.0433    2017
  81 Negotiation_Level                       MR6     0.636     2017
  82 Negotiation_Level                       MR4    -0.0191    2017
  83 Negotiation_Level                       MR3     0.0955    2017
  84 Negotiation_Level                       MR5     0.0127    2017
  85 Instructing_Level                       MR1     1.14      2017
  86 Instructing_Level                       MR2     0.0640    2017
  87 Instructing_Level                       MR6    -0.165     2017
  88 Instructing_Level                       MR4    -0.231     2017
  89 Instructing_Level                       MR3     0.0146    2017
  90 Instructing_Level                       MR5    -0.0584    2017
  91 Service_Orientation_Level               MR1     0.313     2017
  92 Service_Orientation_Level               MR2    -0.121     2017
  93 Service_Orientation_Level               MR6     0.552     2017
  94 Service_Orientation_Level               MR4    -0.0591    2017
  95 Service_Orientation_Level               MR3     0.0201    2017
  96 Service_Orientation_Level               MR5    -0.0349    2017
  97 Complex_Problem_Solving_Level           MR1     0.768     2017
  98 Complex_Problem_Solving_Level           MR2     0.0901    2017
  99 Complex_Problem_Solving_Level           MR6     0.0808    2017
 100 Complex_Problem_Solving_Level           MR4     0.260     2017
 101 Complex_Problem_Solving_Level           MR3    -0.0387    2017
 102 Complex_Problem_Solving_Level           MR5     0.00790   2017
 103 Operations_Analysis_Level               MR1     0.438     2017
 104 Operations_Analysis_Level               MR2    -0.0366    2017
 105 Operations_Analysis_Level               MR6    -0.0253    2017
 106 Operations_Analysis_Level               MR4     0.348     2017
 107 Operations_Analysis_Level               MR3     0.168     2017
 108 Operations_Analysis_Level               MR5     0.0194    2017
 109 Technology_Design_Level                 MR1     0.0321    2017
 110 Technology_Design_Level                 MR2     0.357     2017
 111 Technology_Design_Level                 MR6     0.135     2017
 112 Technology_Design_Level                 MR4     0.513     2017
 113 Technology_Design_Level                 MR3     0.133     2017
 114 Technology_Design_Level                 MR5    -0.00922   2017
 115 Installation_Level                      MR1    -0.00229   2017
 116 Installation_Level                      MR2     0.684     2017
 117 Installation_Level                      MR6     0.0406    2017
 118 Installation_Level                      MR4     0.0729    2017
 119 Installation_Level                      MR3    -0.00836   2017
 120 Installation_Level                      MR5    -0.287     2017
 121 Programming_Level                       MR1     0.0909    2017
 122 Programming_Level                       MR2    -0.0392    2017
 123 Programming_Level                       MR6    -0.0119    2017
 124 Programming_Level                       MR4     0.658     2017
 125 Programming_Level                       MR3     0.0486    2017
 126 Programming_Level                       MR5    -0.0330    2017
 127 Operations_Monitoring_Level             MR1    -0.0666    2017
 128 Operations_Monitoring_Level             MR2     0.805     2017
 129 Operations_Monitoring_Level             MR6     0.0488    2017
 130 Operations_Monitoring_Level             MR4     0.0542    2017
 131 Operations_Monitoring_Level             MR3    -0.0973    2017
 132 Operations_Monitoring_Level             MR5     0.479     2017
 133 Operation_and_Control_Level             MR1    -0.103     2017
 134 Operation_and_Control_Level             MR2     0.772     2017
 135 Operation_and_Control_Level             MR6    -0.00916   2017
 136 Operation_and_Control_Level             MR4    -0.0837    2017
 137 Operation_and_Control_Level             MR3    -0.0828    2017
 138 Operation_and_Control_Level             MR5     0.366     2017
 139 Equipment_Maintenance_Level             MR1     0.0572    2017
 140 Equipment_Maintenance_Level             MR2     0.966     2017
 141 Equipment_Maintenance_Level             MR6    -0.0657    2017
 142 Equipment_Maintenance_Level             MR4    -0.0863    2017
 143 Equipment_Maintenance_Level             MR3    -0.0613    2017
 144 Equipment_Maintenance_Level             MR5    -0.169     2017
 145 Troubleshooting_Level                   MR1    -0.0546    2017
 146 Troubleshooting_Level                   MR2     0.933     2017
 147 Troubleshooting_Level                   MR6     0.0181    2017
 148 Troubleshooting_Level                   MR4     0.0294    2017
 149 Troubleshooting_Level                   MR3    -0.0607    2017
 150 Troubleshooting_Level                   MR5     0.140     2017
 151 Repairing_Level                         MR1     0.0592    2017
 152 Repairing_Level                         MR2     0.998     2017
 153 Repairing_Level                         MR6    -0.0287    2017
 154 Repairing_Level                         MR4    -0.0779    2017
 155 Repairing_Level                         MR3    -0.0468    2017
 156 Repairing_Level                         MR5    -0.238     2017
 157 Quality_Control_Analysis_Level          MR1     0.0736    2017
 158 Quality_Control_Analysis_Level          MR2     0.737     2017
 159 Quality_Control_Analysis_Level          MR6    -0.105     2017
 160 Quality_Control_Analysis_Level          MR4     0.124     2017
 161 Quality_Control_Analysis_Level          MR3     0.0661    2017
 162 Quality_Control_Analysis_Level          MR5     0.254     2017
 163 Judgment_and_Decision_Making_Level      MR1     0.780     2017
 164 Judgment_and_Decision_Making_Level      MR2     0.00893   2017
 165 Judgment_and_Decision_Making_Level      MR6     0.115     2017
 166 Judgment_and_Decision_Making_Level      MR4     0.159     2017
 167 Judgment_and_Decision_Making_Level      MR3    -0.0145    2017
 168 Judgment_and_Decision_Making_Level      MR5     0.00390   2017
 169 Systems_Analysis_Level                  MR1     0.691     2017
 170 Systems_Analysis_Level                  MR2     0.0610    2017
 171 Systems_Analysis_Level                  MR6     0.0541    2017
 172 Systems_Analysis_Level                  MR4     0.233     2017
 173 Systems_Analysis_Level                  MR3     0.125     2017
 174 Systems_Analysis_Level                  MR5    -0.0304    2017
 175 Systems_Evaluation_Level                MR1     0.736     2017
 176 Systems_Evaluation_Level                MR2     0.110     2017
 177 Systems_Evaluation_Level                MR6     0.103     2017
 178 Systems_Evaluation_Level                MR4     0.171     2017
 179 Systems_Evaluation_Level                MR3     0.116     2017
 180 Systems_Evaluation_Level                MR5    -0.0225    2017
 181 Time_Management_Level                   MR1     0.773     2017
 182 Time_Management_Level                   MR2     0.0547    2017
 183 Time_Management_Level                   MR6     0.122     2017
 184 Time_Management_Level                   MR4    -0.103     2017
 185 Time_Management_Level                   MR3     0.208     2017
 186 Time_Management_Level                   MR5     0.00635   2017
 187 Management_of_Financial_Resources_Level MR1    -0.111     2017
 188 Management_of_Financial_Resources_Level MR2    -0.185     2017
 189 Management_of_Financial_Resources_Level MR6     0.0719    2017
 190 Management_of_Financial_Resources_Level MR4     0.240     2017
 191 Management_of_Financial_Resources_Level MR3     0.890     2017
 192 Management_of_Financial_Resources_Level MR5    -0.0610    2017
 193 Management_of_Material_Resources_Level  MR1     0.0952    2017
 194 Management_of_Material_Resources_Level  MR2    -0.00620   2017
 195 Management_of_Material_Resources_Level  MR6    -0.0195    2017
 196 Management_of_Material_Resources_Level  MR4     0.111     2017
 197 Management_of_Material_Resources_Level  MR3     0.844     2017
 198 Management_of_Material_Resources_Level  MR5    -0.0285    2017
 199 Management_of_Personnel_Resources_Level MR1     0.776     2017
 200 Management_of_Personnel_Resources_Level MR2     0.0799    2017
 201 Management_of_Personnel_Resources_Level MR6     0.0432    2017
 202 Management_of_Personnel_Resources_Level MR4    -0.239     2017
 203 Management_of_Personnel_Resources_Level MR3     0.362     2017
 204 Management_of_Personnel_Resources_Level MR5     0.0629    2017
 205 Equipment_Selection_Level               MR1    -0.00911   2017
 206 Equipment_Selection_Level               MR2     0.923     2017
 207 Equipment_Selection_Level               MR6    -0.0444    2017
 208 Equipment_Selection_Level               MR4     0.0292    2017
 209 Equipment_Selection_Level               MR3     0.0188    2017
 210 Equipment_Selection_Level               MR5    -0.110     2017
 211 Reading_Comprehension_Level             MR4     0.741     2019
 212 Reading_Comprehension_Level             MR1     0.204     2019
 213 Reading_Comprehension_Level             MR2    -0.161     2019
 214 Reading_Comprehension_Level             MR3    -0.153     2019
 215 Reading_Comprehension_Level             MR6     0.102     2019
 216 Reading_Comprehension_Level             MR5     0.0191    2019
 217 Active_Listening_Level                  MR4     0.498     2019
 218 Active_Listening_Level                  MR1     0.529     2019
 219 Active_Listening_Level                  MR2    -0.151     2019
 220 Active_Listening_Level                  MR3    -0.210     2019
 221 Active_Listening_Level                  MR6    -0.00839   2019
 222 Active_Listening_Level                  MR5     0.0257    2019
 223 Writing_Level                           MR4     0.602     2019
 224 Writing_Level                           MR1     0.245     2019
 225 Writing_Level                           MR2    -0.189     2019
 226 Writing_Level                           MR3    -0.107     2019
 227 Writing_Level                           MR6     0.189     2019
 228 Writing_Level                           MR5     0.0783    2019
 229 Speaking_Level                          MR4     0.471     2019
 230 Speaking_Level                          MR1     0.425     2019
 231 Speaking_Level                          MR2    -0.196     2019
 232 Speaking_Level                          MR3    -0.143     2019
 233 Speaking_Level                          MR6     0.133     2019
 234 Speaking_Level                          MR5     0.0731    2019
 235 Mathematical_Reasoning_Level            MR4     0.858     2019
 236 Mathematical_Reasoning_Level            MR1    -0.263     2019
 237 Mathematical_Reasoning_Level            MR2    -0.114     2019
 238 Mathematical_Reasoning_Level            MR3     0.247     2019
 239 Mathematical_Reasoning_Level            MR6     0.0184    2019
 240 Mathematical_Reasoning_Level            MR5    -0.0282    2019
 241 Science_Level                           MR4     0.922     2019
 242 Science_Level                           MR1    -0.128     2019
 243 Science_Level                           MR2     0.127     2019
 244 Science_Level                           MR3    -0.200     2019
 245 Science_Level                           MR6     0.0839    2019
 246 Science_Level                           MR5    -0.169     2019
 247 Critical_Thinking_Level                 MR4     0.642     2019
 248 Critical_Thinking_Level                 MR1     0.446     2019
 249 Critical_Thinking_Level                 MR2    -0.0281    2019
 250 Critical_Thinking_Level                 MR3    -0.126     2019
 251 Critical_Thinking_Level                 MR6    -0.0224    2019
 252 Critical_Thinking_Level                 MR5    -0.000787  2019
 253 Active_Learning_Level                   MR4     0.633     2019
 254 Active_Learning_Level                   MR1     0.273     2019
 255 Active_Learning_Level                   MR2    -0.0735    2019
 256 Active_Learning_Level                   MR3    -0.0327    2019
 257 Active_Learning_Level                   MR6     0.174     2019
 258 Active_Learning_Level                   MR5     0.0400    2019
 259 Learning_Strategies_Level               MR4     0.332     2019
 260 Learning_Strategies_Level               MR1     0.244     2019
 261 Learning_Strategies_Level               MR2    -0.0366    2019
 262 Learning_Strategies_Level               MR3     0.0497    2019
 263 Learning_Strategies_Level               MR6     0.505     2019
 264 Learning_Strategies_Level               MR5     0.0899    2019
 265 Monitoring_Level                        MR4     0.317     2019
 266 Monitoring_Level                        MR1     0.508     2019
 267 Monitoring_Level                        MR2     0.0761    2019
 268 Monitoring_Level                        MR3     0.0160    2019
 269 Monitoring_Level                        MR6     0.268     2019
 270 Monitoring_Level                        MR5    -0.142     2019
 271 Social_Perceptiveness_Level             MR4    -0.0127    2019
 272 Social_Perceptiveness_Level             MR1     0.894     2019
 273 Social_Perceptiveness_Level             MR2    -0.0689    2019
 274 Social_Perceptiveness_Level             MR3    -0.100     2019
 275 Social_Perceptiveness_Level             MR6     0.0448    2019
 276 Social_Perceptiveness_Level             MR5    -0.0163    2019
 277 Coordination_Level                      MR4    -0.113     2019
 278 Coordination_Level                      MR1     0.819     2019
 279 Coordination_Level                      MR2     0.129     2019
 280 Coordination_Level                      MR3     0.166     2019
 281 Coordination_Level                      MR6     0.109     2019
 282 Coordination_Level                      MR5    -0.113     2019
 283 Persuasion_Level                        MR4     0.0499    2019
 284 Persuasion_Level                        MR1     1.00      2019
 285 Persuasion_Level                        MR2    -0.0209    2019
 286 Persuasion_Level                        MR3     0.0309    2019
 287 Persuasion_Level                        MR6    -0.226     2019
 288 Persuasion_Level                        MR5     0.0355    2019
 289 Negotiation_Level                       MR4    -0.0498    2019
 290 Negotiation_Level                       MR1     0.999     2019
 291 Negotiation_Level                       MR2    -0.0470    2019

### 7. Modelo SEM 6 Fatores

In [19]:
model_esem6 <- '

efa("block1")*F1 +
efa("block1")*F2 +
efa("block1")*F3 +
efa("block1")*F4 +
efa("block1")*F5 +
efa("block1")*F6 =~

Science_Level +                        
Programming_Level +                      
Mathematical_Reasoning_Level +                   
Reading_Comprehension_Level +                  
Complex_Problem_Solving_Level +                
Operations_Analysis_Level +                      
Technology_Design_Level +          
Critical_Thinking_Level +                
Active_Learning_Level +                      
Writing_Level +                       
Systems_Analysis_Level +                    
Judgment_and_Decision_Making_Level +                 
Systems_Evaluation_Level +                
Speaking_Level +                 
Persuasion_Level +                
Negotiation_Level +                
Social_Perceptiveness_Level +                 
Service_Orientation_Level +                  
Coordination_Level +                 
Time_Management_Level +                
Management_of_Personnel_Resources_Level +    
Active_Listening_Level +                 
Monitoring_Level +               
Repairing_Level +          
Equipment_Maintenance_Level +            
Troubleshooting_Level +          
Equipment_Selection_Level +           
Operations_Monitoring_Level +           
Operation_and_Control_Level +          
Quality_Control_Analysis_Level +           
Installation_Level +           
Management_of_Financial_Resources_Level +   
Management_of_Material_Resources_Level +     
Instructing_Level +
Learning_Strategies_Level 

'

### 8. Ajuste Fatorial

In [20]:
fit_esem6 <- cfa(
    model_esem6,
    data = efa_global,
    estimator = "MLR",
    std.lv = TRUE
)

fitMeasures(
  fit_esem6,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     14573.634        400.000          0.000          0.919          0.879
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.108          0.106          0.109          0.018

### 9. Loadings

In [21]:
loadings <- parameterEstimates(fit_esem6)

loadings %>%
  filter(op == "=~") %>%
  as.data.frame() %>%
  print()

    lhs op                                     rhs    efa           est
1    F1 =~                           Science_Level block1  0.9155900457
2    F1 =~                       Programming_Level block1  0.3082889827
3    F1 =~            Mathematical_Reasoning_Level block1  0.4286132069
4    F1 =~             Reading_Comprehension_Level block1  0.6704754494
5    F1 =~           Complex_Problem_Solving_Level block1  0.4897173188
6    F1 =~               Operations_Analysis_Level block1  0.5266172940
7    F1 =~                 Technology_Design_Level block1  0.2385774036
8    F1 =~                 Critical_Thinking_Level block1  0.5026298844
9    F1 =~                   Active_Learning_Level block1  0.5772125643
10   F1 =~                           Writing_Level block1  0.6512248082
11   F1 =~                  Systems_Analysis_Level block1  0.5293200813
12   F1 =~      Judgment_and_Decision_Making_Level block1  0.4686031710
13   F1 =~                Systems_Evaluation_Level block1  0.5545996425
14   F1 =~                          Speaking_Level block1  0.5398870936
15   F1 =~                        Persuasion_Level block1  0.3378287527
16   F1 =~                       Negotiation_Level block1  0.2973940725
17   F1 =~             Social_Perceptiveness_Level block1  0.3409755693
18   F1 =~               Service_Orientation_Level block1  0.2287085349
19   F1 =~                      Coordination_Level block1  0.1784779658
20   F1 =~                   Time_Management_Level block1  0.2624486763
21   F1 =~ Management_of_Personnel_Resources_Level block1  0.2494011934
22   F1 =~                  Active_Listening_Level block1  0.4939822485
23   F1 =~                        Monitoring_Level block1  0.3556995872
24   F1 =~                         Repairing_Level block1 -0.0005065992
25   F1 =~             Equipment_Maintenance_Level block1 -0.0202266887
26   F1 =~                   Troubleshooting_Level block1 -0.0239947755
27   F1 =~               Equipment_Selection_Level block1 -0.0001985450
28   F1 =~             Operations_Monitoring_Level block1  0.0106880018
29   F1 =~             Operation_and_Control_Level block1 -0.1201332689
30   F1 =~          Quality_Control_Analysis_Level block1  0.0319656532
31   F1 =~                      Installation_Level block1  0.0442469441
32   F1 =~ Management_of_Financial_Resources_Level block1 -0.0100899934
33   F1 =~  Management_of_Material_Resources_Level block1  0.0117901450
34   F1 =~                       Instructing_Level block1  0.4787024240
35   F1 =~               Learning_Strategies_Level block1  0.4891267946
36   F2 =~                           Science_Level block1 -0.4397509230
37   F2 =~                       Programming_Level block1 -0.1145002902
38   F2 =~            Mathematical_Reasoning_Level block1 -0.0773724428
39   F2 =~             Reading_Comprehension_Level block1 -0.1163173800
40   F2 =~           Complex_Problem_Solving_Level block1  0.0060376509
41   F2 =~               Operations_Analysis_Level block1  0.0312843635
42   F2 =~                 Technology_Design_Level block1 -0.0085043551
43   F2 =~                 Critical_Thinking_Level block1  0.0023650121
44   F2 =~                   Active_Learning_Level block1 -0.0293710168
45   F2 =~                           Writing_Level block1 -0.0701828725
46   F2 =~                  Systems_Analysis_Level block1  0.0751296549
47   F2 =~      Judgment_and_Decision_Making_Level block1  0.0405751170
48   F2 =~                Systems_Evaluation_Level block1  0.1065679593
49   F2 =~                          Speaking_Level block1 -0.0041480135
50   F2 =~                        Persuasion_Level block1  0.3064483164
51   F2 =~                       Negotiation_Level block1  0.3348602249
52   F2 =~             Social_Perceptiveness_Level block1  0.1807373261
53   F2 =~               Service_Orientation_Level block1  0.2337361766
54   F2 =~                      Coordination_Level block1  0.2138136682
55   F2 =~                   Time_Management_Level block1  0.1478482420
56   F2 =~ Management_of_Personnel_Resources_Level block1  0.2756341098
57   F2 =~                  Active_Listening_Level block1  0.0061738927
58   F2 =~                        Monitoring_Level block1  0.0699511237
59   F2 =~                         Repairing_Level block1  0.0194969787
60   F2 =~             Equipment_Maintenance_Level block1 -0.0118218987
61   F2 =~                   Troubleshooting_Level block1 -0.0070984093
62   F2 =~               Equipment_Selection_Level block1 -0.0065819036
63   F2 =~             Operations_Monitoring_Level block1 -0.0041903814
64   F2 =~             Operation_and_Control_Level block1  0.0090127696
65   F2 =~          Quality_Control_Analysis_Level block1  0.0005309651
66   F2 =~                      Installation_Level block1 -0.0033367690
67   F2 =~ Management_of_Financial_Resources_Level block1  0.4904298964
68   F2 =~  Management_of_Material_Resources_Level block1  0.4059900067
69   F2 =~                       Instructing_Level block1  0.0074100072
70   F2 =~               Learning_Strategies_Level block1 -0.0071317604
71   F3 =~                           Science_Level block1 -0.1266847275
72   F3 =~                       Programming_Level block1 -0.0119972054
73   F3 =~            Mathematical_Reasoning_Level block1 -0.0572828541
74   F3 =~             Reading_Comprehension_Level block1 -0.0241828068
75   F3 =~           Complex_Problem_Solving_Level block1  0.0112535824
76   F3 =~               Operations_Analysis_Level block1 -0.0635613687
77   F3 =~                 Technology_Design_Level block1  0.0174310980
78   F3 =~                 Critical_Thinking_Level block1  0.0026538271
79   F3 =~                   Active_Learning_Level block1 -0.0012126735
80   F3 =~                           Writing_Level block1  0.0104669951
81   F3 =~                  Systems_Analysis_Level block1  0.0162109848
82   F3 =~      Judgment_and_Decision_Making_Level block1  0.0030947392
83   F3 =~                Systems_Evaluation_Level block1  0.0233121885
84   F3 =~                          Speaking_Level block1  0.0052643935
85   F3 =~                        Persuasion_Level block1  0.0116471718
86   F3 =~                       Negotiation_Level block1  0.0137328671
87   F3 =~             Social_Perceptiveness_Level block1 -0.0160458903
88   F3 =~               Service_Orientation_Level block1 -0.0124058707
89   F3 =~                      Coordination_Level block1 -0.0316278426
90   F3 =~                   Time_Management_Level block1  0.0024141981
91   F3 =~ Management_of_Personnel_Resources_Level block1 -0.0258455879
92   F3 =~                  Active_Listening_Level block1 -0.0009098228
93   F3 =~                        Monitoring_Level block1 -0.0470806746
94   F3 =~                         Repairing_Level block1  0.6019632846
95   F3 =~             Equipment_Maintenance_Level block1  0.5348151344
96   F3 =~                   Troubleshooting_Level block1  0.1935244157
97   F3 =~               Equipment_Selection_Level block1  0.3423384636
98   F3 =~             Operations_Monitoring_Level block1 -0.0676376332
99   F3 =~             Operation_and_Control_Level block1 -0.0057641405
100  F3 =~          Quality_Control_Analysis_Level block1 -0.0040205576
101  F3 =~                      Installation_Level block1  0.2878484390
102  F3 =~ Management_of_Financial_Resources_Level block1  0.0020093228
103  F3 =~  Management_of_Material_Resources_Level block1 -0.0022535851
104  F3 =~                       Instructing_Level block1  0.0052537050
105  F3 =~               Learning_Strategies_Level block1  0.0109039622
106  F4 =~                           Science_Level block1  0.1425370009
107  F4 =~                       Programming_Level block1  0.0026004916
108  F4 =~            Mathematical_Reasoning_Level block1 -0.0244840637
109  F4 =~             Reading_Comprehension_Level block1 -0.1303278033
110  F4 =~           Complex_Problem_Solving_Level block1  0.0298366715
111  F4 =~               Operations_Analysis_Level block1  0.0016034537
112  F4 =~                 Technology_Design_Level block1  0.1676851986
113  F4 =~                 Critical_Thinking_Level block1 -0.0069563310
114  F4 =~                   Active_Learning_Level block1 -0.1049927793
115  F4 =~                           Writing_Level block1 -0.1929222940
116  F4 =~                  Systems_Analysis_Level block1  0.0178548402
117  F4 =~      Judgment_and_Decision_Making_Level block1 -0.0060258906
118  F4 =~                Systems_Evaluation_Level block1  0.0273506630
119  F4 =~                          Speaking_Level block1 -0.1620147921
120  F4 =~                        Persuasion_Level block1 -0.0135678290
121  F4 =~                       Negotiation_Level block1 -0.0045712012
122  F4 =~             Social_Perceptiveness_Level block1 -0.0905913743
123  F4 =~               Service_Orientation_Level block1 -0.0858243033
124  F4 =~                      Coordination_Level block1  0.0325373185
125  F4 =~                   Time_Management_Level block1  0.0001258806
126  F4 =~ Management_of_Personnel_Resources_Level block1  0.0011364891
127  F4 =~                  Active_Listening_Level block1 -0.0792049747
128  F4 =~                        Monitoring_Level block1  0.0069492578
129  F4 =~                         Repairing_Level block1  0.8241344228
130  F4 =~             Equipment_Maintenance_Level block1  0.8228663213
131  F4 =~                   Troubleshooting_Level block1  0.8566183896
132  F4 =~               Equipment_Selection_Level block1  0.6594860826
133  F4 =~             Operations_Monitoring_Level block1  0.8200703763
134  F4 =~             Operation_and_Control_Level block1  0.9480843375
135  F4 =~          Quality_Control_Analysis_Level block1  0.6660392587
136  F4 =~                      Installation_Level block1  0.2989310462
137  F4 =~ Management_of_Financial_Resources_Level block1 -0.0660995243
138  F4 =~  Management_of_Material_Resources_Level block1  0.0083305327
139  F4 =~                       Instructing_Level block1 -0.1481023019
140  F4 =~               Learning_Strategies_Level block1 -0.2245705415
141  F5 =~                           Science_Level block1  0.0205336579
142  F5 =~                       Programming_Level block1  0.1410329456
143  F5 =~            Mathematical_Reasoning_Level block1  0.2927114285
144  F5 =~             Reading_Comprehension_Level block1 -0.0056952218
145  F5 =~           Complex_Problem_Solving_Level block1  0.0512708907
146  F5 =~               Operations_Analysis_Level block1  0.2665488569
147  F5 =~                 Technology_Design_Level block1  0.1348770631
148  F5 =~                 Critical_Thinking_Level block1 -0.0021219912
149  F5 =~                   Active_Learning_Level block1  0.0411106261
150  F5 =~                           Writing_Level block1 -0.0061803773
151  F5 =~                  Systems_Analysis_Level block1  0.1221403147
152  F5 =~      Judgment_and_Decision_Making_Level block1  0.0412224634
153  F5 =~                Systems_Evaluation_Level block1  0.1137573203
154  F5 =~                          Speaking_Level block1 -0.0476095745
155  F5 =~                        Persuasion_Level block1 -0.0032925648
156  F5 =~                       Negotiation_Level block1 -0.0023370953
157  F5 =~             Social_Perceptiveness_Level block1 -0.0859339896
158  F5 =~               Service_Orientation_Level block1 -0.0474683530
159  F5 =~                      Coordination_Level block1  0.0093128864
160  F5 =~                   Time_Management_Level block1  0.0540863962
161  F5 =~ Management_of_Personnel_Resources_Level block1  0.1103547652
162  F5 =~                  Active_Listening_Level block1 -0.0628892543
163  F5 =~                        Monitoring_Level block1 -0.0054531239
164  F5 =~                         Repairing_Level block1 -0.0038697139
165  F5 =~             Equipment_Maintenance_Level block1 -0.0270738641
166  F5 =~                   Troubleshooting_Level block1 -0.0171233335
167  F5 =~               Equipment_Selection_Level block1  0.0560187316
168  F5 =~             Operations_Monitoring_Level block1 -0.0612692592
169  F5 =~             Operation_and_Control_Level block1 -0.1230737641
170  F5 =~          Quality_Control_Analysis_Level block1  0.1038089010
171  F5 =~                      Installation_Level block1  0.0293157251
172  F5 =~ Management_of_Financial_Resources_Level block1  0.5769839065
173  F5 =~  Management_of_Material_Resources_Level block1  0.4824369299
174  F5 =~                       Instructing_Level block1 -0.0534594527
175  F5 =~               Learning_Strategies_Level block1  0.0007568072
176  F6 =~                           Science_Level block1  0.0422112192
177  F6 =~                       Programming_Level block1 -0.0617753943
178  F6 =~            Mathematical_Reasoning_Level block1  0.0010513375
179  F6 =~             Reading_Comprehension_Level block1 -0.0417051671
180  F6 =~           Complex_Problem_Solving_Level block1 -0.0331449352
181  F6 =~               Operations_Analysis_Level block1 -0.0263410029
182  F6 =~                 Technology_Design_Level block1 -0.0317119551
183  F6 =~                 Critical_Thinking_Level block1 -0.0861662066
184  F6 =~                   Active_Learning_Level block1  0.0361253363
185  F6 =~                           Writing_Level block1 -0.0009380681
186  F6 =~                  Systems_Analysis_Level block1  0.0198656020
187  F6 =~      Judgment_and_Decision_Making_Level block1 -0.0372797521
188  F6 =~                Systems_Evaluation_Level block1  0.0306556462
189  F6 =~                          Speaking_Level block1 -0.0215972578
190  F6 =~                        Persuasion_Level block1 -0.1112901930
191  F6 =~                       Negotiation_Level block1 -0.1132014037
192  F6 =~             Social_Perceptiveness_Level block1  0.0038511394
193  F6 =~               Service_Orientation_Level block1 -0.0313302552
194  F6 =~                      Coordination_Level block1  0.0466171834
195  F6 =~                   Time_Management_Level block1  0.0281307329
196  F6 =~ Management_of_Personnel_Resources_Level block1  0.1304399095
197  F6 =~                  Active_Listening_Level block1 -0.0921053733
198  F6 =~                        Monitoring_Level block1  0.0776154634
199  F6 =~                         Repairing_Level block1 -0.0026941643
200  F6 =~             Equipment_Maintenance_Level block1  0.0089489958
201  F6 =~                   Troubleshooting_Level block1  0.0112084805
202  F6 =~               Equipment_Selection_Level block1  0.0136344500
203  F6 =~             Operations_Monitoring_Level block1 -0.0069885636
204  F6 =~             Operation_and_Control_Level block1 -0.0229805952
205  F6 =~          Quality_Control_Analysis_Level block1  0.0297316006
206  F6 =~                      Installation_Level block1 -0.0082115685
207  F6 =~ Management_of_Financial_Resources_Level block1 -0.0041345322
208  F6 =~  Management_of_Material_Resources_Level block1  0.0902352023
209  F6 =~                       Instructing_Level block1  0.2883553728
210  F6 =~               Learning_Strategies_Level block1  0.3091477307
             se            z       pvalue      ci.lower      ci.upper
1   0.026511792  34.53520000 0.000000e+00  0.8636278878  0.9675522036
2   0.014863476  20.74137824 0.000000e+00  0.2791571045  0.3374208608
3   0.020697676  20.70827705 0.000000e+00  0.3880465076  0.4691799062
4   0.010260681  65.34414714 0.000000e+00  0.6503648842  0.6905860146
5   0.007900971  61.98191490 0.000000e+00  0.4742317000  0.5052029376
6   0.016904817  31.15190744 0.000000e+00  0.4934844615  0.5597501264
7   0.011499125  20.74743936 0.000000e+00  0.2160395323  0.2611152749
8   0.007981904  62.97118003 0.000000e+00  0.4869856410  0.5182741279
9   0.008627856  66.90104042 0.000000e+00  0.5603022767  0.5941228520
10  0.009418090  69.14616206 0.000000e+00  0.6327656901  0.6696839262
11  0.009790569  54.06428379 0.000000e+00  0.5101309194  0.5485092432
12  0.007102354  65.97857534 0.000000e+00  0.4546828138  0.4825235282
13  0.010141789  54.68459677 0.000000e+00  0.5347221013  0.5744771837
14  0.008349415  64.66166721 0.000000e+00  0.5235225409  0.5562516462
15  0.016213069  20.83681670 0.000000e+00  0.3060517208  0.3696057846
16  0.017311920  17.17857217 0.000000e+00  0.2634633322  0.3313248128
17  0.015657814  21.77670273 0.000000e+00  0.3102868170  0.3716643216
18  0.016817749  13.59923604 0.000000e+00  0.1957463531  0.2616707167
19  0.012862459  13.87588228 0.000000e+00  0.1532680095  0.2036879220
20  0.007551668  34.75373681 0.000000e+00  0.2476476794  0.2772496733
21  0.012227281  20.39710900 0.000000e+00  0.2254361621  0.2733662248
22  0.009753875  50.64471880 0.000000e+00  0.4748650051  0.5130994919
23  0.007500332  47.42451152 0.000000e+00  0.3409992064  0.3703999681
24  0.003810011  -0.13296527 8.942208e-01 -0.0079740842  0.0069608859
25  0.005092653  -3.97173869 7.134996e-05 -0.0302081060 -0.0102452713
26  0.007004549  -3.42559910 6.134451e-04 -0.0377234386 -0.0102661125
27  0.004500892  -0.04411236 9.648148e-01 -0.0090201309  0.0086230410
28  0.004728259   2.26045186 2.379322e-02  0.0014207845  0.0199552191
29  0.012574072  -9.55404623 0.000000e+00 -0.1447779979 -0.0954885399
30  0.011343801   2.81789607 4.833945e-03  0.0097322111  0.0541990954
31  0.009904064   4.46755450 7.911886e-06  0.0248353361  0.0636585521
32  0.003041495  -3.31744526 9.084471e-04 -0.0160512142 -0.0041287726
33  0.003807010   3.09695639 1.955186e-03  0.0043285418  0.0192517481
34  0.015856880  30.18894112 0.000000e+00  0.4476235098  0.5097813382
35  0.016646325  29.38346951 0.000000e+00  0.4565005963  0.5217529928
36  0.018286048 -24.04844016 0.000000e+00 -0.4755909178 -0.4039109281
37  0.011981251  -9.55662218 0.000000e+00 -0.1379831109 -0.0910174695
38  0.020372397  -3.79790574 1.459238e-04 -0.1173016069 -0.0374432788
39  0.005879348 -19.78406019 0.000000e+00 -0.1278406909 -0.1047940692
40  0.007390054   0.81699684 4.139302e-01 -0.0084465890  0.0205218907
41  0.017240784   1.81455576 6.959221e-02 -0.0025069517  0.0650756788
42  0.005000359  -1.70074894 8.899014e-02 -0.0183048783  0.0012961682
43  0.004342450   0.54462622 5.860106e-01 -0.0061460335  0.0108760578
44  0.006291787  -4.66815206 3.039209e-06 -0.0417026921 -0.0170393416
45  0.006482156 -10.82708865 0.000000e+00 -0.0828876638 -0.0574780811
46  0.011059287   6.79335405 1.095568e-11  0.0534538499  0.0968054600
47  0.007811605   5.19421031 2.055906e-07  0.0252646534  0.0558855806
48  0.010573022  10.07923331 0.000000e+00  0.0858452162  0.1272907024
49  0.003617564  -1.14663182 2.515338e-01 -0.0112383077  0.0029422808
50  0.010503765  29.17509330 0.000000e+00  0.2858613158  0.3270353170
51  0.011098976  30.17037149 0.000000e+00  0.3131066320  0.3566138179
52  0.008395861  21.52695674 0.000000e+00  0.1642817419  0.1971929104
53  0.010923567  21.39742194 0.000000e+00  0.2123263783  0.2551459749
54  0.008041144  26.58995728 0.000000e+00  0.1980533161  0.2295740204
55  0.008132916  18.17899608 0.000000e+00  0.1319080202  0.1637884638
56  0.013304539  20.71729851 0.000000e+00  0.2495576921  0.3017105274
57  0.002998410   2.05905583 3.948889e-02  0.0002971179  0.0120506674
58  0.007509384   9.31516118 0.000000e+00  0.0552330013  0.0846692462
59  0.004860639   4.01119693 6.041169e-05  0.0099703020  0.0290236553
60  0.004736370  -2.49598283 1.256087e-02 -0.0211050137 -0.0025387837
61  0.005997386  -1.18358394 2.365778e-01 -0.0188530692  0.0046562506
62  0.005983886  -1.09993807 2.713591e-01 -0.0183101038  0.0051462967
63  0.004991451  -0.83951173 4.011822e-01 -0.0139734451  0.0055926822
64  0.007486560   1.20386000 2.286437e-01 -0.0056606175  0.0236861568
65  0.008333105   0.06371755 9.491951e-01 -0.0158016215  0.0168635516
66  0.004953875  -0.67356748 5.005863e-01 -0.0130461853  0.0063726473
67  0.034465353  14.22964975 0.000000e+00  0.4228790466  0.5579807463