In [1]:
install.packages(c(
  "tidyverse",
  "psych",
  "GPArotation",
  "nFactors",
  "corrplot",
  "reshape2",
  "lavaan",
  "semTools"
))

Instalando pacotes em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

package 'tidyverse' successfully unpacked and MD5 sums checked
package 'psych' successfully unpacked and MD5 sums checked
package 'GPArotation' successfully unpacked and MD5 sums checked
package 'nFactors' successfully unpacked and MD5 sums checked
package 'corrplot' successfully unpacked and MD5 sums checked
package 'reshape2' successfully unpacked and MD5 sums checked
package 'lavaan' successfully unpacked and MD5 sums checked
package 'semTools' successfully unpacked and MD5 sums checked

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\Rtmp8CQU3t\downloaded_packages

In [44]:
install.packages("blavaan")
install.packages("bayesplot")
install.packages("posterior")

Instalando pacote em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

package 'blavaan' successfully unpacked and MD5 sums checked

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\Rtmp8CQU3t\downloaded_packages

Instalando pacote em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

package 'bayesplot' successfully unpacked and MD5 sums checked

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\Rtmp8CQU3t\downloaded_packages

Instalando pacote em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

package 'posterior' successfully unpacked and MD5 sums checked

Os pacotes binários baixados estão em
	C:\Users\Maxwell\AppData\Local\Temp\Rtmp8CQU3t\downloaded_packages

In [46]:
install.packages("QuickJSR", type = "source")

Instalando pacote em 'C:/Users/Maxwell/AppData/Local/R/win-library/4.6'
(como 'lib' não foi especificado)

In [47]:
library(blavaan)
library(bayesplot)

This is blavaan 0.5-10

On multicore systems, we suggest use of future::plan("multicore") or
  future::plan("multisession") for faster post-MCMC computations.

This is bayesplot version 1.15.0

- Online documentation and vignettes at mc-stan.org/bayesplot

- bayesplot theme set to bayesplot::theme_default()

   * Does _not_ affect other ggplot2 plots

   * See ?bayesplot_theme_set for details on theme setting

In [3]:
library(tidyverse)

library(psych)
library(GPArotation)

library(nFactors)

library(corrplot)

library(reshape2)

library(lavaan)
library(semTools)

library(blavaan)
library(bayesplot)

Anexando pacote: 'psych'


Os seguintes objetos são mascarados por 'package:ggplot2':

    %+%, alpha



Anexando pacote: 'GPArotation'


Os seguintes objetos são mascarados por 'package:psych':

    equamax, varimin


corrplot 0.95 loaded


Anexando pacote: 'reshape2'


O seguinte objeto é mascarado por 'package:tidyr':

    smiths


This is lavaan 0.6-21
lavaan is FREE software! Please report any bugs.


Anexando pacote: 'lavaan'


O seguinte objeto é mascarado por 'package:psych':

    cor2cov




###############################################################################

This is semTools 0.5-8

All users of R (or SEM) are invited to submit functions or ideas for functions.

###############################################################################


Anexando pacote: 'semTools'


Os seguintes objetos são mascarados por 'package:psych':

    reliability, skew


O seguinte objeto é mascarado por 'package:readr':

    clipboard

In [4]:
efa_data_raw <- read.delim(
  "adequacy-c.txt",
  check.names = FALSE
)

names(efa_data_raw) <- gsub(
  "\\.+",
  "_",
  names(efa_data_raw)
)

glimpse(efa_data_raw)

Rows: 3,050
Columns: 38
$ O_NET_SOC_Code                          <chr> "11-1011.00", "11-1021.00", "1…
$ Title                                   <chr> "Chief Executives", "General a…
$ Version_Year                            <int> 2017, 2017, 2017, 2017, 2017, …
$ Reading_Comprehension_Level             <dbl> 1.945577, 1.346769, 1.442579, …
$ Active_Listening_Level                  <dbl> 2.0493705, 1.3467694, 1.442578…
$ Writing_Level                           <dbl> 1.6501653, 1.2509602, 1.250960…
$ Speaking_Level                          <dbl> 2.049370, 1.346769, 1.650165, …
$ Mathematical_Reasoning_Level            <dbl> 1.0433735, 0.1491539, 0.644168…
$ Science_Level                           <dbl> -0.95265236, -0.95265236, -1.2…
$ Critical_Thinking_Level                 <dbl> 1.945577, 1.346769, 1.442579, …
$ Active_Learning_Level                   <dbl> 1.9455772, 1.0433735, 1.346769…
$ Learning_Strategies_Level               <dbl> 1.2509602, 0.7479617, 0.947564…
$ Monitoring_Level                        <dbl> 2.5443849, 1.3467694, 1.546372…
$ Social_Perceptiveness_Level             <dbl> 1.5463720, 1.3467694, 1.147166…
$ Coordination_Level                      <dbl> 2.2409890, 1.2509602, 1.650165…
$ Persuasion_Level                        <dbl> 2.1451797, 0.9475642, 1.043373…
$ Negotiation_Level                       <dbl> 1.8417838, 1.0433735, 1.147166…
$ Instructing_Level                       <dbl> 1.2509602, 0.7479617, 0.947564…
$ Service_Orientation_Level               <dbl> 0.8517550, 0.6441683, 0.747961…
$ Complex_Problem_Solving_Level           <dbl> 2.1451797, 1.1471668, 1.346769…
$ Operations_Analysis_Level               <dbl> 1.54637198, 0.64416831, 0.7479…
$ Technology_Design_Level                 <dbl> -1.2480642, -0.9526524, -1.144…
$ Installation_Level                      <dbl> -1.846872, -1.846872, -1.84687…
$ Programming_Level                       <dbl> -1.3518575, -1.3518575, -1.351…
$ Operations_Monitoring_Level             <dbl> -0.55344719, 0.24496314, -1.04…
$ Operation_and_Control_Level             <dbl> -0.6492564, -0.4496538, -1.543…
$ Equipment_Maintenance_Level             <dbl> -1.8468719, -1.8468719, -1.846…
$ Troubleshooting_Level                   <dbl> -1.84687193, -0.74506567, -1.7…
$ Repairing_Level                         <dbl> -1.846872, -1.846872, -1.84687…
$ Quality_Control_Analysis_Level          <dbl> -1.04846160, -0.15424203, -0.0…
$ Judgment_and_Decision_Making_Level      <dbl> 2.7439875, 1.1471668, 1.442578…
$ Systems_Analysis_Level                  <dbl> 2.44857566, 0.54835907, 0.8517…
$ Systems_Evaluation_Level                <dbl> 2.24098897, 0.64416831, 1.1471…
$ Time_Management_Level                   <dbl> 1.945577, 1.147167, 1.346769, …
$ Management_of_Financial_Resources_Level <dbl> 2.5443849, 0.8517550, 1.147166…
$ Management_of_Material_Resources_Level  <dbl> 1.94557715, 0.74796165, 0.2449…
$ Management_of_Personnel_Resources_Level <dbl> 2.4485757, 1.2509602, 1.346769…
$ Equipment_Selection_Level               <dbl> -1.1442708, -1.8468719, -1.447…

In [5]:
dim(efa_data_raw)

[1] 3050   38

In [6]:
id_cols <- c(
  "O_NET_SOC_Code",
  "Title",
  "Version_Year"
)

skill_vars <- setdiff(
  names(efa_data_raw),
  id_cols
)

length(skill_vars)

[1] 35

In [7]:
efa_global <- efa_data_raw %>%
  select(all_of(skill_vars))

### 6. Estimar solução 4 fatores

In [27]:
efa4 <- fa(
  efa_global,
  nfactors = 4,
  fm = "minres",
  rotate = "oblimin"
)

print(
  efa4,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR2   MR4   MR3   MR1   h2    u2
Reading_Comprehension_Level                1  0.96                   0.92 0.077
Active_Learning_Level                      8  0.94                   0.92 0.078
Writing_Level                              3  0.93                   0.90 0.096
Critical_Thinking_Level                    7  0.92                   0.89 0.107
Complex_Problem_Solving_Level             17  0.92                   0.89 0.106
Speaking_Level                             4  0.90                   0.92 0.081
Instructing_Level                         15  0.89                   0.76 0.239
Active_Listening_Level                     2  0.89                   0.88 0.117
Learning_Strategies_Level                  9  0.88                   0.78 0.220
Judgment_and_Decision_Making_Level        28  0.88                   0.88 0.121
Science_Level                              6  0.84             -0.30 0.65 0.354
Systems_Evaluation_Level                  30  0.83                   0.89 0.113
Systems_Analysis_Level                    29  0.82                   0.86 0.137
Monitoring_Level                          10  0.81                   0.82 0.182
Social_Perceptiveness_Level               11  0.67              0.39 0.84 0.161
Time_Management_Level                     31  0.66                   0.81 0.191
Operations_Analysis_Level                 18  0.60                   0.64 0.359
Mathematical_Reasoning_Level               5  0.57        0.31 -0.41 0.71 0.290
Programming_Level                         21  0.57             -0.46 0.57 0.430
Persuasion_Level                          13  0.55              0.31 0.82 0.181
Management_of_Personnel_Resources_Level   34  0.51        0.44       0.81 0.192
Negotiation_Level                         14  0.48        0.30  0.34 0.80 0.197
Coordination_Level                        12  0.47        0.34  0.39 0.71 0.292
Technology_Design_Level                   19  0.45  0.35             0.50 0.505
Service_Orientation_Level                 16  0.45              0.35 0.65 0.346
Troubleshooting_Level                     25        0.96             0.95 0.055
Equipment_Maintenance_Level               24        0.95             0.90 0.105
Repairing_Level                           26        0.94             0.88 0.125
Equipment_Selection_Level                 35        0.92             0.86 0.140
Operations_Monitoring_Level               22        0.86             0.79 0.207
Operation_and_Control_Level               23        0.83             0.78 0.220
Quality_Control_Analysis_Level            27        0.83             0.79 0.212
Installation_Level                        20        0.63             0.38 0.618
Management_of_Financial_Resources_Level   32              0.94       0.86 0.144
Management_of_Material_Resources_Level    33              0.87       0.81 0.190
                                        com
Reading_Comprehension_Level             1.1
Active_Learning_Level                   1.0
Writing_Level                           1.1
Critical_Thinking_Level                 1.0
Complex_Problem_Solving_Level           1.0
Speaking_Level                          1.2
Instructing_Level                       1.1
Active_Listening_Level                  1.2
Learning_Strategies_Level               1.0
Judgment_and_Decision_Making_Level      1.0
Science_Level                           1.4
Systems_Evaluation_Level                1.2
Systems_Analysis_Level                  1.2
Monitoring_Level                        1.2
Social_Perceptiveness_Level             1.8
Time_Management_Level                   1.7
Operations_Analysis_Level               1.7
Mathematical_Reasoning_Level            2.4
Programming_Level                       2.0
Persuasion_Level                        2.5
Management_of_Personnel_Resources_Level 2.6
Negotiation_Level                       3.1
Coordination_Level                      2.8
Technology_Design_Level                 3.2
Service_Orientation_Level               2.8
Troubleshooting_Level                   1.0
Equipment_Maintenance_Level             1.1
Repairing_Level                         1.1
Equipment_Selection_Level               1.0
Operations_Monitoring_Level             1.1
Operation_and_Control_Level             1.1
Quality_Control_Analysis_Level          1.2
Installation_Level                      1.1
Management_of_Financial_Resources_Level 1.0
Management_of_Material_Resources_Level  1.0

                        MR2  MR4  MR3  MR1
SS loadings           15.49 6.97 3.68 1.68
Proportion Var         0.44 0.20 0.11 0.05
Cumulative Var         0.44 0.64 0.75 0.79
Proportion Explained   0.56 0.25 0.13 0.06
Cumulative Proportion  0.56 0.81 0.94 1.00

 With factor correlations of
      MR2   MR4  MR3   MR1
MR2  1.00 -0.30 0.54  0.10
MR4 -0.30  1.00 0.02 -0.27
MR3  0.54  0.02 1.00  0.11
MR1  0.10 -0.27 0.11  1.00

Mean item complexity =  1.5
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 461  and the objective function was  9.3

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  3050 with the empirical chi square  1290.38  with prob <  1.3e-79
The total n.obs was  3050  with Likelihood Chi Square =  28206.45  with prob <  0

Tucker Lewis Index of factoring reliability =  0.794
RMSEA index =  0.14  and the 90 % confidence intervals are  0.139 0.142
BIC =  24507.9
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR2  MR4  MR3  MR1
Correlation of (regression) scores with factors   0.97 0.97 0.94 0.89
Multiple R square of scores with factors          0.93 0.95 0.88 0.79
Minimum correlation of possible factor scores     0.87 0.90 0.75 0.58

### 7. Estimar solução 5 fatores

In [12]:
efa5 <- fa(
  efa_global,
  nfactors = 5,
  fm = "minres",
  rotate = "promax"
)

print(
  efa5,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 5, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR1   MR4   MR2   MR3   MR5   h2
Coordination_Level                        12  0.94                         0.71
Social_Perceptiveness_Level               11  0.94                         0.84
Negotiation_Level                         14  0.86                         0.83
Management_of_Personnel_Resources_Level   34  0.86                         0.83
Persuasion_Level                          13  0.84                         0.85
Service_Orientation_Level                 16  0.81                         0.67
Time_Management_Level                     31  0.79                         0.81
Monitoring_Level                          10  0.78                         0.87
Instructing_Level                         15  0.74                         0.78
Learning_Strategies_Level                  9  0.66  0.34                   0.79
Speaking_Level                             4  0.56  0.40                   0.92
Active_Listening_Level                     2  0.55  0.39                   0.89
Systems_Evaluation_Level                  30  0.53  0.49                   0.89
Judgment_and_Decision_Making_Level        28  0.52  0.49                   0.88
Programming_Level                         21 -0.32  0.91                   0.59
Mathematical_Reasoning_Level               5        0.87                   0.71
Science_Level                              6        0.86                   0.69
Reading_Comprehension_Level                1  0.33  0.67                   0.92
Operations_Analysis_Level                 18        0.64                   0.64
Technology_Design_Level                   19        0.62  0.31             0.52
Complex_Problem_Solving_Level             17  0.43  0.61                   0.89
Active_Learning_Level                      8  0.46  0.58                   0.92
Writing_Level                              3  0.43  0.55                   0.90
Critical_Thinking_Level                    7  0.47  0.55                   0.89
Systems_Analysis_Level                    29  0.45  0.55                   0.86
Repairing_Level                           26              1.06        0.31 0.95
Equipment_Maintenance_Level               24              1.03             0.93
Troubleshooting_Level                     25              0.98             0.94
Equipment_Selection_Level                 35              0.97             0.88
Operations_Monitoring_Level               22              0.83             0.88
Operation_and_Control_Level               23              0.82             0.84
Quality_Control_Analysis_Level            27              0.78             0.81
Installation_Level                        20              0.74        0.38 0.50
Management_of_Financial_Resources_Level   32                    0.80       0.88
Management_of_Material_Resources_Level    33  0.33              0.69       0.80
                                           u2 com
Coordination_Level                      0.286 1.2
Social_Perceptiveness_Level             0.164 1.1
Negotiation_Level                       0.169 1.3
Management_of_Personnel_Resources_Level 0.175 1.3
Persuasion_Level                        0.148 1.2
Service_Orientation_Level               0.330 1.3
Time_Management_Level                   0.192 1.1
Monitoring_Level                        0.134 1.4
Instructing_Level                       0.222 1.5
Learning_Strategies_Level               0.212 1.6
Speaking_Level                          0.081 2.3
Active_Listening_Level                  0.115 2.3
Systems_Evaluation_Level                0.112 2.2
Judgment_and_Decision_Making_Level      0.122 2.0
Programming_Level                       0.408 1.3
Mathematical_Reasoning_Level            0.292 1.3
Science_Level                           0.311 1.2
Reading_Comprehension_Level             0.079 1.7
Operations_Analysis_Level               0.360 1.3
Technology_Design_Level                 0.484 1.8
Complex_Problem_Solving_Level           0.106 1.8
Active_Learning_Level                   0.079 1.9
Writing_Level                           0.097 2.3
Critical_Thinking_Level                 0.105 2.0
Systems_Analysis_Level                  0.136 2.1
Repairing_Level                         0.049 1.2
Equipment_Maintenance_Level             0.067 1.2
Troubleshooting_Level                   0.063 1.0
Equipment_Selection_Level               0.118 1.1
Operations_Monitoring_Level             0.116 1.2
Operation_and_Control_Level             0.157 1.2
Quality_Control_Analysis_Level          0.185 1.3
Installation_Level                      0.497 1.5
Management_of_Financial_Resources_Level 0.120 1.3
Management_of_Material_Resources_Level  0.198 1.5

                        MR1  MR4  MR2  MR3  MR5
SS loadings           11.10 7.97 6.94 1.90 0.59
Proportion Var         0.32 0.23 0.20 0.05 0.02
Cumulative Var         0.32 0.54 0.74 0.80 0.81
Proportion Explained   0.39 0.28 0.24 0.07 0.02
Cumulative Proportion  0.39 0.67 0.91 0.98 1.00

 With factor correlations of
      MR1   MR4   MR2   MR3   MR5
MR1  1.00  0.69 -0.43  0.22  0.09
MR4  0.69  1.00 -0.10  0.24  0.02
MR2 -0.43 -0.10  1.00  0.23 -0.31
MR3  0.22  0.24  0.23  1.00 -0.13
MR5  0.09  0.02 -0.31 -0.13  1.00

Mean item complexity =  1.5
Test of the hypothesis that 5 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 430  and the objective function was  7.21

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  3050 with the empirical chi square  763.51  with prob <  5.3e-21
The total n.obs was  3050  with Likelihood Chi Square =  21870.31  with prob <  0

Tucker Lewis Index of factoring reliability =  0.829
RMSEA index =  0.128  and the 90 % confidence intervals are  0.126 0.129
BIC =  18420.47
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR1  MR4  MR2  MR3  MR5
Correlation of (regression) scores with factors   0.94 0.96 0.99 0.92 1.00
Multiple R square of scores with factors          0.89 0.92 0.97 0.85 1.00
Minimum correlation of possible factor scores     0.78 0.83 0.95 0.70 0.99

### 8. Estimar solução 6 fatores

In [13]:
efa6 <- fa(
  efa_global,
  nfactors = 6,
  fm = "minres",
  rotate = "promax"
)

print(
  efa6,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 6, rotate = "promax", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR4   MR1   MR2   MR3   MR6
Science_Level                              6  0.94
Programming_Level                         21  0.93
Mathematical_Reasoning_Level               5  0.87
Reading_Comprehension_Level                1  0.76
Complex_Problem_Solving_Level             17  0.70  0.32
Operations_Analysis_Level                 18  0.68
Technology_Design_Level                   19  0.66        0.34
Critical_Thinking_Level                    7  0.66  0.42
Active_Learning_Level                      8  0.66
Writing_Level                              3  0.62
Systems_Analysis_Level                    29  0.60
Judgment_and_Decision_Making_Level        28  0.58  0.39
Systems_Evaluation_Level                  30  0.55  0.36
Speaking_Level                             4  0.50  0.40
Persuasion_Level                          13        1.00
Negotiation_Level                         14        0.99
Social_Perceptiveness_Level               11        0.89
Service_Orientation_Level                 16        0.89
Coordination_Level                        12        0.80
Time_Management_Level                     31        0.58
Management_of_Personnel_Resources_Level   34        0.57        0.34
Active_Listening_Level                     2  0.52  0.52
Monitoring_Level                          10  0.33  0.48
Repairing_Level                           26              1.02
Equipment_Maintenance_Level               24              0.99
Troubleshooting_Level                     25              0.97
Equipment_Selection_Level                 35              0.94
Operations_Monitoring_Level               22              0.85
Operation_and_Control_Level               23              0.83
Quality_Control_Analysis_Level            27              0.77
Installation_Level                        20              0.71
Management_of_Financial_Resources_Level   32                    0.87
Management_of_Material_Resources_Level    33                    0.79
Instructing_Level                         15  0.32                    0.51
Learning_Strategies_Level                  9  0.37                    0.50
                                          MR5   h2    u2 com
Science_Level                                 0.69 0.311 1.3
Programming_Level                             0.60 0.404 1.3
Mathematical_Reasoning_Level                  0.71 0.294 1.4
Reading_Comprehension_Level                   0.92 0.080 1.3
Complex_Problem_Solving_Level                 0.89 0.105 1.4
Operations_Analysis_Level                     0.64 0.357 1.2
Technology_Design_Level                       0.54 0.463 1.8
Critical_Thinking_Level                       0.91 0.095 1.8
Active_Learning_Level                         0.92 0.078 1.5
Writing_Level                                 0.91 0.094 1.8
Systems_Analysis_Level                        0.86 0.137 1.7
Judgment_and_Decision_Making_Level            0.88 0.122 1.8
Systems_Evaluation_Level                      0.89 0.113 2.0
Speaking_Level                                0.92 0.083 2.7
Persuasion_Level                              0.91 0.089 1.1
Negotiation_Level                             0.87 0.127 1.1
Social_Perceptiveness_Level                   0.85 0.154 1.0
Service_Orientation_Level                     0.69 0.306 1.1
Coordination_Level                            0.71 0.289 1.3
Time_Management_Level                         0.81 0.189 1.7
Management_of_Personnel_Resources_Level       0.84 0.156 2.3
Active_Listening_Level                        0.90 0.103 2.5
Monitoring_Level                              0.87 0.134 2.8
Repairing_Level                               0.97 0.027 1.2
Equipment_Maintenance_Level                   0.95 0.053 1.2
Troubleshooting_Level                         0.94 0.060 1.0
Equipment_Selection_Level                     0.88 0.119 1.1
Operations_Monitoring_Level             -0.42 0.95 0.053 1.6
Operation_and_Control_Level             -0.32 0.86 0.136 1.4
Quality_Control_Analysis_Level                0.82 0.179 1.4
Installation_Level                       0.34 0.51 0.494 1.4
Management_of_Financial_Resources_Level       0.90 0.104 1.2
Management_of_Material_Resources_Level        0.83 0.166 1.1
Instructing_Level                             0.85 0.151 2.4
Learning_Strategies_Level                     0.87 0.130 2.3

                       MR4  MR1  MR2  MR3  MR6  MR5
SS loadings           9.30 8.43 6.78 2.07 1.76 0.71
Proportion Var        0.27 0.24 0.19 0.06 0.05 0.02
Cumulative Var        0.27 0.51 0.70 0.76 0.81 0.83
Proportion Explained  0.32 0.29 0.23 0.07 0.06 0.02
Cumulative Proportion 0.32 0.61 0.84 0.92 0.98 1.00

 With factor correlations of
      MR4   MR1   MR2   MR3   MR6   MR5
MR4  1.00  0.67 -0.13  0.41  0.48  0.07
MR1  0.67  1.00 -0.45  0.34  0.57  0.12
MR2 -0.13 -0.45  1.00  0.23 -0.22 -0.24
MR3  0.41  0.34  0.23  1.00  0.14 -0.26
MR6  0.48  0.57 -0.22  0.14  1.00 -0.09
MR5  0.07  0.12 -0.24 -0.26 -0.09  1.00

Mean item complexity =  1.6
Test of the hypothesis that 6 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 400  and the objective function was  5.39

The root mean square of the residuals (RMSR) is  0.02
The df corrected root mean square of the residuals is  0.02

The harmonic n.obs is  3050 with the empirical chi square  486.01  with prob <  0.0021
The total n.obs was  3050  with Likelihood Chi Square =  16331.8  with prob <  0

Tucker Lewis Index of factoring reliability =  0.863
RMSEA index =  0.114  and the 90 % confidence intervals are  0.113 0.116
BIC =  13122.64
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR4  MR1  MR2  MR3  MR6 MR5
Correlation of (regression) scores with factors   0.99 0.99 0.99 0.97 0.97   1
Multiple R square of scores with factors          0.99 0.98 0.99 0.94 0.95   1
Minimum correlation of possible factor scores     0.97 0.97 0.98 0.87 0.90   1

### Estimar solução 2 fatores

In [32]:
efa2 <- fa(
  efa_global,
  nfactors = 2,
  fm = "minres",
  rotate = "oblimin"
)

print(
  efa2,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 2, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR1   MR2   h2   u2 com
Systems_Evaluation_Level                  30  0.97       0.89 0.11 1.0
Complex_Problem_Solving_Level             17  0.96       0.88 0.12 1.0
Systems_Analysis_Level                    29  0.95       0.86 0.14 1.0
Judgment_and_Decision_Making_Level        28  0.93       0.87 0.13 1.0
Active_Learning_Level                      8  0.92       0.89 0.11 1.0
Critical_Thinking_Level                    7  0.91       0.87 0.13 1.0
Monitoring_Level                          10  0.90       0.80 0.20 1.0
Time_Management_Level                     31  0.87       0.76 0.24 1.0
Reading_Comprehension_Level                1  0.86       0.84 0.16 1.1
Learning_Strategies_Level                  9  0.85       0.75 0.25 1.0
Instructing_Level                         15  0.84       0.71 0.29 1.0
Writing_Level                              3  0.83       0.85 0.15 1.1
Management_of_Personnel_Resources_Level   34  0.83       0.67 0.33 1.0
Speaking_Level                             4  0.81 -0.30 0.88 0.12 1.3
Active_Listening_Level                     2  0.80       0.84 0.16 1.3
Operations_Analysis_Level                 18  0.79       0.59 0.41 1.1
Mathematical_Reasoning_Level               5  0.76       0.54 0.46 1.2
Persuasion_Level                          13  0.75       0.74 0.26 1.2
Coordination_Level                        12  0.73       0.54 0.46 1.0
Science_Level                              6  0.72       0.48 0.52 1.3
Negotiation_Level                         14  0.71       0.68 0.32 1.3
Social_Perceptiveness_Level               11  0.70 -0.34 0.74 0.26 1.4
Management_of_Material_Resources_Level    33  0.68       0.44 0.56 1.3
Management_of_Financial_Resources_Level   32  0.65       0.40 0.60 1.1
Programming_Level                         21  0.62       0.36 0.64 1.2
Technology_Design_Level                   19  0.60  0.49 0.44 0.56 1.9
Service_Orientation_Level                 16  0.57 -0.36 0.56 0.44 1.7
Troubleshooting_Level                     25        0.95 0.93 0.07 1.0
Equipment_Selection_Level                 35        0.91 0.85 0.15 1.0
Quality_Control_Analysis_Level            27        0.91 0.78 0.22 1.1
Operations_Monitoring_Level               22        0.89 0.79 0.21 1.0
Equipment_Maintenance_Level               24        0.87 0.84 0.16 1.0
Repairing_Level                           26        0.87 0.82 0.18 1.0
Operation_and_Control_Level               23        0.82 0.75 0.25 1.1
Installation_Level                        20        0.60 0.36 0.64 1.0

                        MR1  MR2
SS loadings           17.72 7.25
Proportion Var         0.51 0.21
Cumulative Var         0.51 0.71
Proportion Explained   0.71 0.29
Cumulative Proportion  0.71 1.00

 With factor correlations of
      MR1   MR2
MR1  1.00 -0.26
MR2 -0.26  1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 526  and the objective function was  15.39

The root mean square of the residuals (RMSR) is  0.06
The df corrected root mean square of the residuals is  0.06

The harmonic n.obs is  3050 with the empirical chi square  6408.48  with prob <  0
The total n.obs was  3050  with Likelihood Chi Square =  46719.1  with prob <  0

Tucker Lewis Index of factoring reliability =  0.699
RMSEA index =  0.17  and the 90 % confidence intervals are  0.168 0.171
BIC =  42499.05
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy
                                                   MR1  MR2
Correlation of (regression) scores with factors   0.99 0.99
Multiple R square of scores with factors          0.99 0.97
Minimum correlation of possible factor scores     0.98 0.94

### Estimar solução 3 fatores

In [57]:
efa2 <- fa(
  efa_global,
  nfactors = 3,
  fm = "minres",
  rotate = "oblimin"
)

print(
  efa2,
  sort = TRUE,
  cut = .30
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 3, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR3   MR1   MR2   h2    u2 com
Science_Level                              6  0.97             0.65 0.350 1.3
Reading_Comprehension_Level                1  0.93             0.93 0.074 1.1
Active_Learning_Level                      8  0.85             0.92 0.078 1.1
Complex_Problem_Solving_Level             17  0.84             0.90 0.104 1.1
Writing_Level                              3  0.84             0.90 0.099 1.2
Programming_Level                         21  0.82             0.47 0.530 1.2
Critical_Thinking_Level                    7  0.82             0.89 0.109 1.1
Mathematical_Reasoning_Level               5  0.77             0.58 0.420 1.1
Judgment_and_Decision_Making_Level        28  0.75             0.88 0.121 1.2
Systems_Analysis_Level                    29  0.73             0.86 0.138 1.3
Speaking_Level                             4  0.73 -0.34       0.90 0.099 1.5
Active_Listening_Level                     2  0.71 -0.32       0.86 0.135 1.5
Systems_Evaluation_Level                  30  0.70        0.34 0.89 0.111 1.5
Operations_Analysis_Level                 18  0.67             0.60 0.404 1.2
Learning_Strategies_Level                  9  0.66             0.75 0.247 1.3
Instructing_Level                         15  0.63             0.71 0.289 1.4
Technology_Design_Level                   19  0.58  0.46       0.46 0.544 1.9
Monitoring_Level                          10  0.54        0.44 0.80 0.200 1.9
Troubleshooting_Level                     25        0.96       0.93 0.070 1.0
Equipment_Selection_Level                 35        0.92       0.85 0.152 1.0
Quality_Control_Analysis_Level            27        0.92       0.79 0.211 1.0
Operations_Monitoring_Level               22        0.90       0.80 0.203 1.0
Equipment_Maintenance_Level               24        0.88       0.84 0.162 1.0
Repairing_Level                           26        0.87       0.82 0.182 1.0
Operation_and_Control_Level               23        0.83       0.77 0.230 1.1
Installation_Level                        20        0.60       0.37 0.634 1.1
Management_of_Personnel_Resources_Level   34              0.79 0.82 0.182 1.1
Management_of_Material_Resources_Level    33              0.79 0.63 0.374 1.3
Coordination_Level                        12              0.79 0.70 0.300 1.0
Management_of_Financial_Resources_Level   32              0.77 0.57 0.427 1.0
Negotiation_Level                         14              0.71 0.80 0.198 1.4
Persuasion_Level                          13              0.65 0.82 0.184 1.6
Time_Management_Level                     31  0.36        0.61 0.81 0.192 1.6
Service_Orientation_Level                 16       -0.37  0.55 0.63 0.369 1.8
Social_Perceptiveness_Level               11       -0.36  0.51 0.77 0.229 2.4

                        MR3  MR1  MR2
SS loadings           12.39 7.48 6.78
Proportion Var         0.35 0.21 0.19
Cumulative Var         0.35 0.57 0.76
Proportion Explained   0.46 0.28 0.25
Cumulative Proportion  0.46 0.75 1.00

 With factor correlations of
      MR3   MR1   MR2
MR3  1.00 -0.23  0.67
MR1 -0.23  1.00 -0.22
MR2  0.67 -0.22  1.00

Mean item complexity =  1.3
Test of the hypothesis that 3 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 493  and the objective function was  11.54

The root mean square of the residuals (RMSR) is  0.04
The df corrected root mean square of the residuals is  0.04

The harmonic n.obs is  3050 with the empirical chi square  2749.23  with prob <  6.1e-309
The total n.obs was  3050  with Likelihood Chi Square =  35017.24  with prob <  0

Tucker Lewis Index of factoring reliability =  0.76
RMSEA index =  0.152  and the 90 % confidence intervals are  0.15 0.153
BIC =  31061.96
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR3  MR1  MR2
Correlation of (regression) scores with factors   0.99 0.99 0.94
Multiple R square of scores with factors          0.97 0.97 0.88
Minimum correlation of possible factor scores     0.94 0.95 0.76

### 9. Comparar modelos

In [14]:
fit_comparison <- tibble(

  Factors = c(4,5,6),

  RMSEA = c(
    efa4$RMSEA[1],
    efa5$RMSEA[1],
    efa6$RMSEA[1]
  ),

  RMSR = c(
    efa4$rms,
    efa5$rms,
    efa6$rms
  ),

  TLI = c(
    efa4$TLI,
    efa5$TLI,
    efa6$TLI
  ),

  BIC = c(
    efa4$BIC,
    efa5$BIC,
    efa6$BIC
  )
)

fit_comparison

  Factors RMSEA     RMSR       TLI       BIC
1 4       0.1404735 0.02666550 0.7937718 24507.90
2 5       0.1278586 0.02051157 0.8291104 18420.47
3 6       0.1142749 0.01636485 0.8634620 13122.64

### Solução de 6 Fatores

In [33]:
print(
  efa2,
  cut = .40,
  sort = TRUE
)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 2, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                        item   MR1   MR2   h2   u2 com
Systems_Evaluation_Level                  30  0.97       0.89 0.11 1.0
Complex_Problem_Solving_Level             17  0.96       0.88 0.12 1.0
Systems_Analysis_Level                    29  0.95       0.86 0.14 1.0
Judgment_and_Decision_Making_Level        28  0.93       0.87 0.13 1.0
Active_Learning_Level                      8  0.92       0.89 0.11 1.0
Critical_Thinking_Level                    7  0.91       0.87 0.13 1.0
Monitoring_Level                          10  0.90       0.80 0.20 1.0
Time_Management_Level                     31  0.87       0.76 0.24 1.0
Reading_Comprehension_Level                1  0.86       0.84 0.16 1.1
Learning_Strategies_Level                  9  0.85       0.75 0.25 1.0
Instructing_Level                         15  0.84       0.71 0.29 1.0
Writing_Level                              3  0.83       0.85 0.15 1.1
Management_of_Personnel_Resources_Level   34  0.83       0.67 0.33 1.0
Speaking_Level                             4  0.81       0.88 0.12 1.3
Active_Listening_Level                     2  0.80       0.84 0.16 1.3
Operations_Analysis_Level                 18  0.79       0.59 0.41 1.1
Mathematical_Reasoning_Level               5  0.76       0.54 0.46 1.2
Persuasion_Level                          13  0.75       0.74 0.26 1.2
Coordination_Level                        12  0.73       0.54 0.46 1.0
Science_Level                              6  0.72       0.48 0.52 1.3
Negotiation_Level                         14  0.71       0.68 0.32 1.3
Social_Perceptiveness_Level               11  0.70       0.74 0.26 1.4
Management_of_Material_Resources_Level    33  0.68       0.44 0.56 1.3
Management_of_Financial_Resources_Level   32  0.65       0.40 0.60 1.1
Programming_Level                         21  0.62       0.36 0.64 1.2
Technology_Design_Level                   19  0.60  0.49 0.44 0.56 1.9
Service_Orientation_Level                 16  0.57       0.56 0.44 1.7
Troubleshooting_Level                     25        0.95 0.93 0.07 1.0
Equipment_Selection_Level                 35        0.91 0.85 0.15 1.0
Quality_Control_Analysis_Level            27        0.91 0.78 0.22 1.1
Operations_Monitoring_Level               22        0.89 0.79 0.21 1.0
Equipment_Maintenance_Level               24        0.87 0.84 0.16 1.0
Repairing_Level                           26        0.87 0.82 0.18 1.0
Operation_and_Control_Level               23        0.82 0.75 0.25 1.1
Installation_Level                        20        0.60 0.36 0.64 1.0

                        MR1  MR2
SS loadings           17.72 7.25
Proportion Var         0.51 0.21
Cumulative Var         0.51 0.71
Proportion Explained   0.71 0.29
Cumulative Proportion  0.71 1.00

 With factor correlations of
      MR1   MR2
MR1  1.00 -0.26
MR2 -0.26  1.00

Mean item complexity =  1.1
Test of the hypothesis that 2 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 526  and the objective function was  15.39

The root mean square of the residuals (RMSR) is  0.06
The df corrected root mean square of the residuals is  0.06

The harmonic n.obs is  3050 with the empirical chi square  6408.48  with prob <  0
The total n.obs was  3050  with Likelihood Chi Square =  46719.1  with prob <  0

Tucker Lewis Index of factoring reliability =  0.699
RMSEA index =  0.17  and the 90 % confidence intervals are  0.168 0.171
BIC =  42499.05
Fit based upon off diagonal values = 0.99
Measures of factor score adequacy
                                                   MR1  MR2
Correlation of (regression) scores with factors   0.99 0.99
Multiple R square of scores with factors          0.99 0.97
Minimum correlation of possible factor scores     0.98 0.94

In [29]:
fa.sort(efa4)

Factor Analysis using method =  minres
Call: fa(r = efa_global, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR2   MR4   MR3   MR1   h2    u2 com
Reading_Comprehension_Level              0.96 -0.14 -0.10 -0.12 0.92 0.077 1.1
Active_Learning_Level                    0.94 -0.05  0.01 -0.05 0.92 0.078 1.0
Writing_Level                            0.93 -0.18 -0.10 -0.04 0.90 0.096 1.1
Critical_Thinking_Level                  0.92 -0.06  0.01 -0.03 0.89 0.107 1.0
Complex_Problem_Solving_Level            0.92  0.08  0.09 -0.07 0.89 0.106 1.0
Speaking_Level                           0.90 -0.23 -0.10  0.06 0.92 0.081 1.2
Instructing_Level                        0.89  0.08 -0.05  0.17 0.76 0.239 1.1
Active_Listening_Level                   0.89 -0.21 -0.09  0.07 0.88 0.117 1.2
Learning_Strategies_Level                0.88  0.01 -0.03  0.12 0.78 0.220 1.0
Judgment_and_Decision_Making_Level       0.88 -0.01  0.10  0.00 0.88 0.121 1.0
Science_Level                            0.84  0.22 -0.10 -0.30 0.65 0.354 1.4
Systems_Evaluation_Level                 0.83  0.10  0.21 -0.01 0.89 0.113 1.2
Systems_Analysis_Level                   0.82  0.09  0.21 -0.06 0.86 0.137 1.2
Monitoring_Level                         0.81  0.09  0.13  0.18 0.82 0.182 1.2
Social_Perceptiveness_Level              0.67 -0.20  0.04  0.39 0.84 0.161 1.8
Time_Management_Level                    0.66  0.04  0.29  0.23 0.81 0.191 1.7
Operations_Analysis_Level                0.60  0.02  0.29 -0.22 0.64 0.359 1.7
Mathematical_Reasoning_Level             0.57  0.01  0.31 -0.41 0.71 0.290 2.4
Programming_Level                        0.57  0.01  0.13 -0.46 0.57 0.430 2.0
Persuasion_Level                         0.55 -0.21  0.27  0.31 0.82 0.181 2.5
Management_of_Personnel_Resources_Level  0.51  0.08  0.44  0.29 0.81 0.192 2.6
Negotiation_Level                        0.48 -0.22  0.30  0.34 0.80 0.197 3.1
Coordination_Level                       0.47  0.05  0.34  0.39 0.71 0.292 2.8
Technology_Design_Level                  0.45  0.35  0.24 -0.27 0.50 0.505 3.2
Service_Orientation_Level                0.45 -0.27  0.15  0.35 0.65 0.346 2.8
Troubleshooting_Level                   -0.03  0.96  0.01  0.01 0.95 0.055 1.0
Equipment_Maintenance_Level             -0.01  0.95 -0.16  0.05 0.90 0.105 1.1
Repairing_Level                          0.01  0.94 -0.15  0.05 0.88 0.125 1.1
Equipment_Selection_Level                0.01  0.92 -0.03 -0.03 0.86 0.140 1.0
Operations_Monitoring_Level             -0.05  0.86  0.13 -0.01 0.79 0.207 1.1
Operation_and_Control_Level             -0.18  0.83  0.05  0.06 0.78 0.220 1.1
Quality_Control_Analysis_Level           0.01  0.83  0.23 -0.11 0.79 0.212 1.2
Installation_Level                       0.09  0.63 -0.11 -0.02 0.38 0.618 1.1
Management_of_Financial_Resources_Level -0.03 -0.14  0.94 -0.04 0.86 0.144 1.0
Management_of_Material_Resources_Level   0.05  0.07  0.87  0.01 0.81 0.190 1.0

                        MR2  MR4  MR3  MR1
SS loadings           15.49 6.97 3.68 1.68
Proportion Var         0.44 0.20 0.11 0.05
Cumulative Var         0.44 0.64 0.75 0.79
Proportion Explained   0.56 0.25 0.13 0.06
Cumulative Proportion  0.56 0.81 0.94 1.00

 With factor correlations of
      MR2   MR4  MR3   MR1
MR2  1.00 -0.30 0.54  0.10
MR4 -0.30  1.00 0.02 -0.27
MR3  0.54  0.02 1.00  0.11
MR1  0.10 -0.27 0.11  1.00

Mean item complexity =  1.5
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  57.43 with Chi Square =  174392.1
df of  the model are 461  and the objective function was  9.3

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  3050 with the empirical chi square  1290.38  with prob <  1.3e-79
The total n.obs was  3050  with Likelihood Chi Square =  28206.45  with prob <  0

Tucker Lewis Index of factoring reliability =  0.794
RMSEA index =  0.14  and the 90 % confidence intervals are  0.139 0.142
BIC =  24507.9
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR2  MR4  MR3  MR1
Correlation of (regression) scores with factors   0.97 0.97 0.94 0.89
Multiple R square of scores with factors          0.93 0.95 0.88 0.79
Minimum correlation of possible factor scores     0.87 0.90 0.75 0.58

### 10. Extrair cargas

In [31]:
loadings_4 <- as.data.frame(
  unclass(efa4$loadings)
)

round(loadings_4, 3)

                                        MR2    MR4    MR3    MR1
Reading_Comprehension_Level              0.961 -0.144 -0.096 -0.118
Active_Listening_Level                   0.886 -0.212 -0.095  0.066
Writing_Level                            0.929 -0.183 -0.095 -0.038
Speaking_Level                           0.899 -0.228 -0.099  0.063
Mathematical_Reasoning_Level             0.572  0.008  0.310 -0.415
Science_Level                            0.836  0.222 -0.097 -0.305
Critical_Thinking_Level                  0.924 -0.064  0.006 -0.030
Active_Learning_Level                    0.943 -0.054  0.008 -0.049
Learning_Strategies_Level                0.881  0.009 -0.027  0.119
Monitoring_Level                         0.813  0.094  0.133  0.182
Social_Perceptiveness_Level              0.667 -0.196  0.042  0.388
Coordination_Level                       0.470  0.055  0.344  0.388
Persuasion_Level                         0.547 -0.210  0.268  0.305
Negotiation_Level                        0.479 -0.222  0.304  0.343
Instructing_Level                        0.890  0.078 -0.052  0.175
Service_Orientation_Level                0.450 -0.265  0.148  0.354
Complex_Problem_Solving_Level            0.918  0.080  0.087 -0.075
Operations_Analysis_Level                0.604  0.024  0.291 -0.217
Technology_Design_Level                  0.454  0.349  0.237 -0.272
Installation_Level                       0.092  0.635 -0.108 -0.020
Programming_Level                        0.569  0.008  0.135 -0.461
Operations_Monitoring_Level             -0.054  0.863  0.129 -0.012
Operation_and_Control_Level             -0.179  0.831  0.048  0.062
Equipment_Maintenance_Level             -0.006  0.947 -0.158  0.049
Troubleshooting_Level                   -0.034  0.964  0.009  0.011
Repairing_Level                          0.012  0.945 -0.149  0.053
Quality_Control_Analysis_Level           0.009  0.825  0.225 -0.105
Judgment_and_Decision_Making_Level       0.880 -0.007  0.096  0.002
Systems_Analysis_Level                   0.822  0.087  0.208 -0.055
Systems_Evaluation_Level                 0.832  0.103  0.212 -0.006
Time_Management_Level                    0.660  0.035  0.293  0.227
Management_of_Financial_Resources_Level -0.033 -0.139  0.941 -0.039
Management_of_Material_Resources_Level   0.050  0.065  0.869  0.011
Management_of_Personnel_Resources_Level  0.512  0.080  0.438  0.290
Equipment_Selection_Level                0.011  0.921 -0.030 -0.035

### 11. Comunalidades

In [20]:
communalities_6 <- tibble(
  skill = rownames(loadings_6),
  h2 = efa6$communality
)

communalities_6 %>%
  arrange(h2)

                                        skill
Installation_Level                      Installation_Level
Technology_Design_Level                 Technology_Design_Level
Programming_Level                       Programming_Level
Operations_Analysis_Level               Operations_Analysis_Level
Science_Level                           Science_Level
Service_Orientation_Level               Service_Orientation_Level
Mathematical_Reasoning_Level            Mathematical_Reasoning_Level
Coordination_Level                      Coordination_Level
Time_Management_Level                   Time_Management_Level
Quality_Control_Analysis_Level          Quality_Control_Analysis_Level
Management_of_Material_Resources_Level  Management_of_Material_Resources_Level
Management_of_Personnel_Resources_Level Management_of_Personnel_Resources_Level
Social_Perceptiveness_Level             Social_Perceptiveness_Level
Instructing_Level                       Instructing_Level
Systems_Analysis_Level                  Systems_Analysis_Level
Operation_and_Control_Level             Operation_and_Control_Level
Monitoring_Level                        Monitoring_Level
Learning_Strategies_Level               Learning_Strategies_Level
Negotiation_Level                       Negotiation_Level
Judgment_and_Decision_Making_Level      Judgment_and_Decision_Making_Level
Equipment_Selection_Level               Equipment_Selection_Level
Systems_Evaluation_Level                Systems_Evaluation_Level
Complex_Problem_Solving_Level           Complex_Problem_Solving_Level
Management_of_Financial_Resources_Level Management_of_Financial_Resources_Level
Active_Listening_Level                  Active_Listening_Level
Critical_Thinking_Level                 Critical_Thinking_Level
Writing_Level                           Writing_Level
Persuasion_Level                        Persuasion_Level
Speaking_Level                          Speaking_Level
Reading_Comprehension_Level             Reading_Comprehension_Level
Active_Learning_Level                   Active_Learning_Level
Troubleshooting_Level                   Troubleshooting_Level
Operations_Monitoring_Level             Operations_Monitoring_Level
Equipment_Maintenance_Level             Equipment_Maintenance_Level
Repairing_Level                         Repairing_Level
                                        h2
Installation_Level                      0.5063172
Technology_Design_Level                 0.5369460
Programming_Level                       0.5958335
Operations_Analysis_Level               0.6427382
Science_Level                           0.6891837
Service_Orientation_Level               0.6938548
Mathematical_Reasoning_Level            0.7056810
Coordination_Level                      0.7108520
Time_Management_Level                   0.8108945
Quality_Control_Analysis_Level          0.8212692
Management_of_Material_Resources_Level  0.8340611
Management_of_Personnel_Resources_Level 0.8444350
Social_Perceptiveness_Level             0.8459306
Instructing_Level                       0.8493623
Systems_Analysis_Level                  0.8633226
Operation_and_Control_Level             0.8635538
Monitoring_Level                        0.8660054
Learning_Strategies_Level               0.8698208
Negotiation_Level                       0.8730356
Judgment_and_Decision_Making_Level      0.8781863
Equipment_Selection_Level               0.8812748
Systems_Evaluation_Level                0.8873193
Complex_Problem_Solving_Level           0.8949002
Management_of_Financial_Resources_Level 0.8958183
Active_Listening_Level                  0.8974963
Critical_Thinking_Level                 0.9054675
Writing_Level                           0.9055652
Persuasion_Level                        0.9113137
Speaking_Level                          0.9174687
Reading_Comprehension_Level             0.9204687
Active_Learning_Level                   0.9223328
Troubleshooting_Level                   0.9397200
Operations_Monitoring_Level             0.9465599
Equipment_Maintenance_Level             0.9467689
Repairing_Level                         0.9734383

### 12. Correlação entre fatores

In [22]:
round(
  efa6$Phi,
  3
)

    MR4    MR1    MR2    MR3    MR6    MR5
MR4  1.000  0.673 -0.130  0.408  0.481  0.069
MR1  0.673  1.000 -0.451  0.341  0.572  0.116
MR2 -0.130 -0.451  1.000  0.225 -0.220 -0.242
MR3  0.408  0.341  0.225  1.000  0.137 -0.264
MR6  0.481  0.572 -0.220  0.137  1.000 -0.090
MR5  0.069  0.116 -0.242 -0.264 -0.090  1.000

### 13. EFA longitudinal por ano

In [10]:
years <- sort(
  unique(efa_data_raw$Version_Year)
)

efa_by_year <- list()

for(y in years){

  temp <- efa_data_raw %>%
    filter(Version_Year == y) %>%
    select(all_of(skill_vars))

  efa_by_year[[as.character(y)]] <- fa(
    temp,
    nfactors = 4,
    fm = "minres",
    rotate = "oblimin"
  )

}

In [11]:
efa_by_year

$`2017`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR2   MR4   MR3   MR1   h2    u2 com
Reading_Comprehension_Level              0.95 -0.14 -0.09 -0.15 0.92 0.079 1.1
Active_Listening_Level                   0.90 -0.22 -0.11  0.03 0.89 0.112 1.1
Writing_Level                            0.93 -0.18 -0.10 -0.07 0.90 0.097 1.1
Speaking_Level                           0.91 -0.23 -0.11  0.03 0.92 0.078 1.2
Mathematical_Reasoning_Level             0.50  0.00  0.35 -0.42 0.70 0.299 2.8
Science_Level                            0.80  0.22 -0.09 -0.31 0.62 0.378 1.5
Critical_Thinking_Level                  0.93 -0.06 -0.01 -0.06 0.89 0.106 1.0
Active_Learning_Level                    0.94 -0.04  0.02 -0.09 0.92 0.076 1.0
Learning_Strategies_Level                0.89  0.01 -0.01  0.07 0.78 0.218 1.0
Monitoring_Level                         0.87  0.10  0.09  0.15 0.83 0.169 1.1
Social_Perceptiveness_Level              0.74 -0.18  0.01  0.34 0.83 0.173 1.6
Coordination_Level                       0.57  0.07  0.28  0.37 0.72 0.283 2.3
Persuasion_Level                         0.64 -0.19  0.21  0.29 0.83 0.169 1.8
Negotiation_Level                        0.56 -0.20  0.25  0.33 0.80 0.198 2.4
Instructing_Level                        0.92  0.09 -0.06  0.12 0.76 0.236 1.1
Service_Orientation_Level                0.50 -0.27  0.13  0.31 0.64 0.361 2.5
Complex_Problem_Solving_Level            0.93  0.10  0.07 -0.11 0.89 0.105 1.1
Operations_Analysis_Level                0.58  0.02  0.27 -0.21 0.61 0.392 1.7
Technology_Design_Level                  0.34  0.37  0.29 -0.26 0.46 0.541 3.7
Installation_Level                       0.06  0.61 -0.09 -0.04 0.37 0.635 1.1
Programming_Level                        0.43  0.01  0.20 -0.45 0.48 0.516 2.4
Operations_Monitoring_Level             -0.05  0.86  0.12  0.01 0.78 0.224 1.0
Operation_and_Control_Level             -0.17  0.82  0.04  0.07 0.76 0.236 1.1
Equipment_Maintenance_Level             -0.01  0.93 -0.16  0.03 0.88 0.116 1.1
Troubleshooting_Level                   -0.04  0.96  0.01  0.01 0.94 0.064 1.0
Repairing_Level                          0.00  0.93 -0.15  0.03 0.87 0.132 1.1
Quality_Control_Analysis_Level           0.07  0.83  0.18 -0.09 0.75 0.252 1.1
Judgment_and_Decision_Making_Level       0.90  0.00  0.08 -0.02 0.88 0.120 1.0
Systems_Analysis_Level                   0.81  0.08  0.21 -0.09 0.85 0.150 1.2
Systems_Evaluation_Level                 0.84  0.11  0.20 -0.02 0.88 0.118 1.1
Time_Management_Level                    0.73  0.04  0.24  0.20 0.82 0.184 1.4
Management_of_Financial_Resources_Level -0.03 -0.14  0.94 -0.04 0.86 0.145 1.1
Management_of_Material_Resources_Level   0.07  0.06  0.86  0.02 0.81 0.192 1.0
Management_of_Personnel_Resources_Level  0.61  0.10  0.36  0.27 0.81 0.191 2.1
Equipment_Selection_Level               -0.01  0.92 -0.03 -0.03 0.86 0.143 1.0

                        MR2  MR4  MR3  MR1
SS loadings           15.84 6.81 3.40 1.46
Proportion Var         0.45 0.19 0.10 0.04
Cumulative Var         0.45 0.65 0.74 0.79
Proportion Explained   0.58 0.25 0.12 0.05
Cumulative Proportion  0.58 0.82 0.95 1.00

 With factor correlations of
      MR2   MR4  MR3   MR1
MR2  1.00 -0.30 0.54  0.04
MR4 -0.30  1.00 0.03 -0.22
MR3  0.54  0.03 1.00  0.10
MR1  0.04 -0.22 0.10  1.00

Mean item complexity =  1.5
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  56.51 with Chi Square =  33711.02
df of  the model are 461  and the objective function was  9.18

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  610 with the empirical chi square  269.4  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  5448.5  with prob <  0

Tucker Lewis Index of factoring reliability =  0.805
RMSEA index =  0.133  and the 90 % confidence intervals are  0.13 0.136
BIC =  2491.89
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR2  MR4  MR3  MR1
Correlation of (regression) scores with factors   0.96 0.97 0.93 0.88
Multiple R square of scores with factors          0.92 0.94 0.87 0.78
Minimum correlation of possible factor scores     0.85 0.89 0.74 0.56

$`2019`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR4   MR1   MR2   MR3   h2    u2 com
Reading_Comprehension_Level              0.95 -0.14 -0.09 -0.14 0.92 0.079 1.1
Active_Listening_Level                   0.89 -0.22 -0.10  0.04 0.89 0.115 1.1
Writing_Level                            0.93 -0.17 -0.10 -0.06 0.90 0.096 1.1
Speaking_Level                           0.91 -0.23 -0.11  0.04 0.92 0.081 1.2
Mathematical_Reasoning_Level             0.53  0.00  0.33 -0.42 0.70 0.299 2.6
Science_Level                            0.80  0.22 -0.09 -0.32 0.63 0.368 1.5
Critical_Thinking_Level                  0.92 -0.06  0.01 -0.05 0.89 0.107 1.0
Active_Learning_Level                    0.94 -0.05  0.01 -0.07 0.92 0.079 1.0
Learning_Strategies_Level                0.90  0.02 -0.03  0.10 0.79 0.214 1.0
Monitoring_Level                         0.84  0.10  0.12  0.16 0.82 0.176 1.1
Social_Perceptiveness_Level              0.71 -0.19  0.02  0.37 0.84 0.163 1.7
Coordination_Level                       0.53  0.06  0.32  0.37 0.71 0.291 2.5
Persuasion_Level                         0.60 -0.20  0.24  0.28 0.82 0.180 2.0
Negotiation_Level                        0.54 -0.21  0.28  0.32 0.81 0.195 2.6
Instructing_Level                        0.92  0.09 -0.07  0.15 0.77 0.235 1.1
Service_Orientation_Level                0.49 -0.26  0.14  0.35 0.66 0.337 2.6
Complex_Problem_Solving_Level            0.93  0.09  0.07 -0.10 0.90 0.103 1.1
Operations_Analysis_Level                0.58  0.02  0.30 -0.22 0.62 0.376 1.8
Technology_Design_Level                  0.41  0.36  0.26 -0.28 0.50 0.503 3.5
Installation_Level                       0.09  0.63 -0.11 -0.04 0.38 0.619 1.1
Programming_Level                        0.51  0.00  0.16 -0.47 0.56 0.438 2.2
Operations_Monitoring_Level             -0.05  0.87  0.12  0.01 0.79 0.209 1.0
Operation_and_Control_Level             -0.17  0.83  0.05  0.07 0.77 0.228 1.1
Equipment_Maintenance_Level             -0.01  0.94 -0.15  0.03 0.89 0.114 1.1
Troubleshooting_Level                   -0.03  0.97  0.00  0.02 0.94 0.056 1.0
Repairing_Level                          0.01  0.94 -0.15  0.04 0.87 0.133 1.1
Quality_Control_Analysis_Level           0.01  0.83  0.21 -0.09 0.78 0.223 1.2
Judgment_and_Decision_Making_Level       0.89  0.00  0.09 -0.02 0.88 0.120 1.0
Systems_Analysis_Level                   0.81  0.08  0.21 -0.08 0.86 0.142 1.2
Systems_Evaluation_Level                 0.84  0.10  0.21 -0.02 0.88 0.115 1.2
Time_Management_Level                    0.70  0.04  0.27  0.21 0.81 0.191 1.5
Management_of_Financial_Resources_Level -0.03 -0.14  0.94 -0.04 0.86 0.144 1.1
Management_of_Material_Resources_Level   0.05  0.07  0.87  0.01 0.81 0.190 1.0
Management_of_Personnel_Resources_Level  0.57  0.09  0.40  0.28 0.81 0.192 2.4
Equipment_Selection_Level                0.00  0.92 -0.02 -0.03 0.86 0.136 1.0

                        MR4  MR1  MR2  MR3
SS loadings           15.73 6.91 3.55 1.56
Proportion Var         0.45 0.20 0.10 0.04
Cumulative Var         0.45 0.65 0.75 0.79
Proportion Explained   0.57 0.25 0.13 0.06
Cumulative Proportion  0.57 0.82 0.94 1.00

 With factor correlations of
      MR4   MR1  MR2   MR3
MR4  1.00 -0.30 0.53  0.05
MR1 -0.30  1.00 0.03 -0.24
MR2  0.53  0.03 1.00  0.10
MR3  0.05 -0.24 0.10  1.00

Mean item complexity =  1.5
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  57.34 with Chi Square =  34201.2
df of  the model are 461  and the objective function was  9.41

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  610 with the empirical chi square  263.49  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  5588.89  with prob <  0

Tucker Lewis Index of factoring reliability =  0.802
RMSEA index =  0.135  and the 90 % confidence intervals are  0.132 0.138
BIC =  2632.29
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR4  MR1  MR2  MR3
Correlation of (regression) scores with factors   0.96 0.97 0.93 0.89
Multiple R square of scores with factors          0.93 0.95 0.87 0.79
Minimum correlation of possible factor scores     0.85 0.89 0.74 0.58

$`2021`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR3   MR1   MR4   MR2   h2    u2 com
Reading_Comprehension_Level              0.97 -0.15 -0.10 -0.10 0.92 0.076 1.1
Active_Listening_Level                   0.88 -0.21 -0.09  0.08 0.88 0.118 1.2
Writing_Level                            0.93 -0.19 -0.09 -0.02 0.90 0.096 1.1
Speaking_Level                           0.89 -0.23 -0.09  0.08 0.92 0.082 1.2
Mathematical_Reasoning_Level             0.60  0.01  0.30 -0.41 0.72 0.281 2.3
Science_Level                            0.85  0.22 -0.10 -0.29 0.66 0.341 1.4
Critical_Thinking_Level                  0.92 -0.07  0.01 -0.02 0.89 0.107 1.0
Active_Learning_Level                    0.94 -0.06  0.01 -0.03 0.92 0.080 1.0
Learning_Strategies_Level                0.88  0.01 -0.03  0.14 0.78 0.218 1.1
Monitoring_Level                         0.79  0.09  0.14  0.20 0.81 0.190 1.2
Social_Perceptiveness_Level              0.64 -0.20  0.06  0.40 0.84 0.160 1.9
Coordination_Level                       0.43  0.05  0.37  0.39 0.70 0.298 3.0
Persuasion_Level                         0.51 -0.22  0.29  0.31 0.81 0.186 2.7
Negotiation_Level                        0.45 -0.23  0.33  0.35 0.80 0.199 3.3
Instructing_Level                        0.88  0.08 -0.05  0.19 0.76 0.244 1.1
Service_Orientation_Level                0.43 -0.27  0.16  0.36 0.65 0.348 3.0
Complex_Problem_Solving_Level            0.92  0.08  0.09 -0.06 0.90 0.105 1.0
Operations_Analysis_Level                0.61  0.03  0.29 -0.22 0.65 0.352 1.7
Technology_Design_Level                  0.50  0.35  0.22 -0.27 0.52 0.481 2.9
Installation_Level                       0.09  0.63 -0.11 -0.02 0.38 0.617 1.1
Programming_Level                        0.62  0.01  0.11 -0.46 0.60 0.398 1.9
Operations_Monitoring_Level             -0.05  0.86  0.13 -0.02 0.80 0.205 1.1
Operation_and_Control_Level             -0.18  0.83  0.05  0.06 0.78 0.223 1.1
Equipment_Maintenance_Level             -0.01  0.95 -0.16  0.06 0.90 0.102 1.1
Troubleshooting_Level                   -0.03  0.97  0.01  0.01 0.94 0.055 1.0
Repairing_Level                          0.01  0.95 -0.15  0.06 0.87 0.125 1.1
Quality_Control_Analysis_Level          -0.01  0.83  0.24 -0.11 0.80 0.197 1.2
Judgment_and_Decision_Making_Level       0.87 -0.01  0.11  0.01 0.88 0.123 1.0
Systems_Analysis_Level                   0.82  0.09  0.21 -0.04 0.87 0.132 1.2
Systems_Evaluation_Level                 0.83  0.10  0.22  0.00 0.89 0.113 1.2
Time_Management_Level                    0.63  0.02  0.31  0.24 0.81 0.190 1.8
Management_of_Financial_Resources_Level -0.03 -0.14  0.94 -0.04 0.86 0.144 1.0
Management_of_Material_Resources_Level   0.04  0.07  0.87  0.01 0.81 0.191 1.0
Management_of_Personnel_Resources_Level  0.48  0.08  0.46  0.30 0.80 0.197 2.7
Equipment_Selection_Level                0.02  0.92 -0.03 -0.04 0.86 0.144 1.0

                        MR3  MR1  MR4  MR2
SS loadings           15.34 7.01 3.79 1.76
Proportion Var         0.44 0.20 0.11 0.05
Cumulative Var         0.44 0.64 0.75 0.80
Proportion Explained   0.55 0.25 0.14 0.06
Cumulative Proportion  0.55 0.80 0.94 1.00

 With factor correlations of
      MR3   MR1  MR4   MR2
MR3  1.00 -0.29 0.54  0.12
MR1 -0.29  1.00 0.01 -0.28
MR4  0.54  0.01 1.00  0.12
MR2  0.12 -0.28 0.12  1.00

Mean item complexity =  1.5
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  57.81 with Chi Square =  34486.53
df of  the model are 461  and the objective function was  9.56

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  610 with the empirical chi square  259.76  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  5678.3  with prob <  0

Tucker Lewis Index of factoring reliability =  0.8
RMSEA index =  0.136  and the 90 % confidence intervals are  0.133 0.14
BIC =  2721.69
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR3  MR1  MR4  MR2
Correlation of (regression) scores with factors   0.97 0.98 0.94 0.89
Multiple R square of scores with factors          0.94 0.95 0.88 0.79
Minimum correlation of possible factor scores     0.88 0.90 0.76 0.59

$`2023`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR2   MR4   MR1   MR3   h2    u2 com
Reading_Comprehension_Level              0.97 -0.15 -0.10 -0.09 0.92 0.075 1.1
Active_Listening_Level                   0.87 -0.21 -0.09  0.10 0.88 0.118 1.2
Writing_Level                            0.92 -0.20 -0.09 -0.01 0.90 0.096 1.1
Speaking_Level                           0.88 -0.24 -0.09  0.09 0.92 0.081 1.2
Mathematical_Reasoning_Level             0.62  0.01  0.29 -0.40 0.72 0.284 2.2
Science_Level                            0.87  0.23 -0.10 -0.29 0.66 0.338 1.4
Critical_Thinking_Level                  0.92 -0.07  0.01  0.00 0.90 0.105 1.0
Active_Learning_Level                    0.94 -0.06  0.01 -0.02 0.92 0.078 1.0
Learning_Strategies_Level                0.86  0.00 -0.03  0.15 0.78 0.221 1.1
Monitoring_Level                         0.77  0.08  0.16  0.21 0.81 0.187 1.3
Social_Perceptiveness_Level              0.61 -0.21  0.07  0.42 0.85 0.155 2.1
Coordination_Level                       0.40  0.05  0.38  0.41 0.70 0.295 3.0
Persuasion_Level                         0.48 -0.23  0.30  0.33 0.82 0.184 3.1
Negotiation_Level                        0.41 -0.24  0.34  0.36 0.80 0.200 3.6
Instructing_Level                        0.86  0.07 -0.04  0.21 0.76 0.241 1.1
Service_Orientation_Level                0.40 -0.26  0.16  0.38 0.66 0.340 3.1
Complex_Problem_Solving_Level            0.91  0.07  0.10 -0.05 0.89 0.106 1.0
Operations_Analysis_Level                0.62  0.03  0.30 -0.21 0.66 0.339 1.7
Technology_Design_Level                  0.51  0.34  0.22 -0.26 0.52 0.485 2.8
Installation_Level                       0.10  0.64 -0.11 -0.01 0.39 0.611 1.1
Programming_Level                        0.64  0.01  0.11 -0.45 0.61 0.395 1.9
Operations_Monitoring_Level             -0.06  0.87  0.13 -0.02 0.80 0.198 1.1
Operation_and_Control_Level             -0.18  0.84  0.05  0.06 0.79 0.209 1.1
Equipment_Maintenance_Level             -0.01  0.95 -0.16  0.06 0.90 0.097 1.1
Troubleshooting_Level                   -0.03  0.97  0.02  0.01 0.95 0.048 1.0
Repairing_Level                          0.01  0.95 -0.15  0.06 0.88 0.120 1.1
Quality_Control_Analysis_Level           0.00  0.83  0.24 -0.11 0.81 0.189 1.2
Judgment_and_Decision_Making_Level       0.87 -0.01  0.10  0.03 0.88 0.121 1.0
Systems_Analysis_Level                   0.83  0.09  0.21 -0.03 0.87 0.130 1.2
Systems_Evaluation_Level                 0.83  0.10  0.22  0.01 0.89 0.109 1.2
Time_Management_Level                    0.61  0.03  0.33  0.25 0.81 0.192 1.9
Management_of_Financial_Resources_Level -0.04 -0.14  0.94 -0.04 0.86 0.140 1.0
Management_of_Material_Resources_Level   0.04  0.07  0.88  0.01 0.81 0.189 1.0
Management_of_Personnel_Resources_Level  0.44  0.07  0.49  0.31 0.81 0.192 2.7
Equipment_Selection_Level                0.03  0.92 -0.04 -0.03 0.86 0.140 1.0

                        MR2  MR4  MR1  MR3
SS loadings           15.14 7.08 3.88 1.89
Proportion Var         0.43 0.20 0.11 0.05
Cumulative Var         0.43 0.63 0.75 0.80
Proportion Explained   0.54 0.25 0.14 0.07
Cumulative Proportion  0.54 0.79 0.93 1.00

 With factor correlations of
      MR2   MR4  MR1   MR3
MR2  1.00 -0.29 0.54  0.15
MR4 -0.29  1.00 0.00 -0.30
MR1  0.54  0.00 1.00  0.13
MR3  0.15 -0.30 0.13  1.00

Mean item complexity =  1.6
Test of the hypothesis that 4 factors are sufficient.

df null model =  595  with the objective function =  58.44 with Chi Square =  34861.19
df of  the model are 461  and the objective function was  9.66

The root mean square of the residuals (RMSR) is  0.03
The df corrected root mean square of the residuals is  0.03

The harmonic n.obs is  610 with the empirical chi square  256.58  with prob <  1
The total n.obs was  610  with Likelihood Chi Square =  5734.7  with prob <  0

Tucker Lewis Index of factoring reliability =  0.8
RMSEA index =  0.137  and the 90 % confidence intervals are  0.134 0.14
BIC =  2778.1
Fit based upon off diagonal values = 1
Measures of factor score adequacy
                                                   MR2  MR4  MR1  MR3
Correlation of (regression) scores with factors   0.97 0.98 0.94 0.89
Multiple R square of scores with factors          0.94 0.95 0.89 0.80
Minimum correlation of possible factor scores     0.88 0.91 0.77 0.60

$`2025`
Factor Analysis using method =  minres
Call: fa(r = temp, nfactors = 4, rotate = "oblimin", fm = "minres")
Standardized loadings (pattern matrix) based upon correlation matrix
                                          MR2   MR1   MR4   MR3   h2    u2 com
Reading_Comprehension_Level              0.96 -0.15 -0.09 -0.09 0.92 0.077 1.1
Active_Listening_Level                   0.87 -0.21 -0.09  0.09 0.88 0.122 1.2
Writing_Level                            0.92 -0.19 -0.09 -0.01 0.90 0.095 1.1
Speaking_Level                           0.88 -0.23 -0.09  0.09 0.92 0.082 1.2
Mathematical_Reasoning_Level             0.62  0.01  0.28 -0.41 0.72 0.283 2.2
Science_Level                            0.87  0.22 -0.11 -0.31 0.66 0.339 1.4
Critical_Thinking_Level                  0.92 -0.06  0.01  0.00 0.89 0.111 1.0
Active_Learning_Level                    0.94 -0.06  0.00 -0.02 0.92 0.077 1.0
Learning_Strategies_Level                0.86  0.00 -0.03  0.15 0.78 0.224 1.1
Monitoring_Level                         0.78  0.09  0.16  0.20 0.81 0.188 1.2
Social_Perceptiveness_Level              0.62 -0.21  0.07  0.41 0.85 0.155 2.0
Coordination_Level                       0.40  0.04  0.39  0.40 0.71 0.295 3.0
Persuasion_Level                         0.48 -0.23  0.30  0.32 0.82 0.184 3.0
Negotiation_Level                        0.42 -0.23  0.34  0.35 0.81 0.193 3.5
Instructing_Level                        0.86  0.07 -0.04  0.21 0.76 0.238 1.1
Service_Orientation_Level                0.40 -0.27  0.17  0.37 0.66 0.339 3.1
Complex_Problem_Solving_Level            0.90  0.06  0.11 -0.05 0.89 0.108 1.0
Operations_Analysis_Level                0.63  0.03  0.29 -0.22 0.67 0.332 1.7
Technology_Design_Level                  0.51  0.33  0.20 -0.27 0.49 0.507 2.7
Installation_Level                       0.11  0.65 -0.12  0.01 0.39 0.605 1.1
Programming_Level                        0.64  0.01  0.09 -0.46 0.60 0.405 1.9
Operations_Monitoring_Level             -0.05  0.86  0.13 -0.04 0.80 0.200 1.1
Operation_and_Control_Level             -0.18  0.84  0.05  0.05 0.79 0.205 1.1
Equipment_Maintenance_Level             -0.01  0.96 -0.15  0.07 0.91 0.092 1.1

### 14. Congruência de Tucker

In [14]:
factor.congruence(
  efa_by_year[["2017"]],
  efa_by_year[["2019"]]
)

factor.congruence(
  efa_by_year[["2019"]],
  efa_by_year[["2021"]]
)

factor.congruence(
  efa_by_year[["2021"]],
  efa_by_year[["2023"]]
)

factor.congruence(
  efa_by_year[["2023"]],
  efa_by_year[["2025"]]
)

    MR4   MR1   MR2  MR3
MR2  1.00 -0.06 0.26  0.08
MR4 -0.05  1.00 0.00 -0.11
MR3  0.24  0.00 1.00  0.01
MR1  0.02 -0.11 0.07  1.00

    MR3   MR1   MR4  MR2
MR4  1.00 -0.07 0.28  0.17
MR1 -0.05  1.00 0.00 -0.12
MR2  0.24  0.00 1.00  0.07
MR3 -0.02 -0.12 0.13  0.99

    MR2   MR4   MR1   MR3
MR3  1.00 -0.07  0.27  0.15
MR1 -0.06  1.00 -0.01 -0.13
MR4  0.25 -0.01  1.00  0.15
MR2  0.08 -0.13  0.16  1.00

    MR2   MR1   MR4   MR3
MR2  1.00 -0.06  0.26  0.10
MR4 -0.06  1.00 -0.01 -0.14
MR1  0.26 -0.01  1.00  0.15
MR3  0.13 -0.13  0.18  1.00

### 15. Matriz completa de congruência

In [13]:
print(factor.congruence(efa_by_year))

      MR2   MR4   MR3   MR1   MR4   MR1   MR2   MR3   MR3   MR1   MR4   MR2
MR2  1.00 -0.06  0.24  0.05  1.00 -0.06  0.26  0.08  0.99 -0.07  0.28  0.20
MR4 -0.06  1.00  0.00 -0.11 -0.05  1.00  0.00 -0.11 -0.04  1.00  0.00 -0.12
MR3  0.24  0.00  1.00  0.03  0.24  0.00  1.00  0.01  0.23  0.00  0.99  0.03
MR1  0.05 -0.11  0.03  1.00  0.02 -0.11  0.07  1.00 -0.05 -0.12  0.14  0.99
MR4  1.00 -0.05  0.24  0.02  1.00 -0.06  0.25  0.05  1.00 -0.07  0.28  0.17
MR1 -0.06  1.00  0.00 -0.11 -0.06  1.00  0.00 -0.11 -0.05  1.00  0.00 -0.12
MR2  0.26  0.00  1.00  0.07  0.25  0.00  1.00  0.06  0.24  0.00  1.00  0.07
MR3  0.08 -0.11  0.01  1.00  0.05 -0.11  0.06  1.00 -0.02 -0.12  0.13  0.99
MR3  0.99 -0.04  0.23 -0.05  1.00 -0.05  0.24 -0.02  1.00 -0.06  0.26  0.10
MR1 -0.07  1.00  0.00 -0.12 -0.07  1.00  0.00 -0.12 -0.06  1.00 -0.01 -0.13
MR4  0.28  0.00  0.99  0.14  0.28  0.00  1.00  0.13  0.26 -0.01  1.00  0.14
MR2  0.20 -0.12  0.03  0.99  0.17 -0.12  0.07  0.99  0.10 -0.13  0.14  1.00
MR2  0.99 -0.04  0.23 -0.08  1.00 -0.05  0.24 -0.05  1.00 -0.06  0.25  0.08
MR4 -0.08  1.00 -0.01 -0.12 -0.08  1.00 -0.01 -0.13 -0.07  1.00 -0.01 -0.13
MR1  0.29  0.00  0.99  0.15  0.28  0.00  0.99  0.14  0.27 -0.01  1.00  0.16
MR3  0.24 -0.12  0.04  0.98  0.22 -0.12  0.08  0.98  0.15 -0.13  0.15  1.00
MR2  0.99 -0.04  0.23 -0.07  1.00 -0.05  0.24 -0.04  1.00 -0.06  0.25  0.08
MR1 -0.08  1.00 -0.01 -0.12 -0.07  1.00 -0.01 -0.12 -0.07  1.00 -0.01 -0.13
MR4  0.30  0.00  0.98  0.17  0.29  0.00  0.99  0.16  0.27 -0.01  1.00  0.17
MR3  0.22 -0.12  0.02  0.98  0.20 -0.12  0.06  0.99  0.13 -0.13  0.13  1.00
      MR2   MR4   MR1   MR3   MR2   MR1   MR4   MR3
MR2  0.99 -0.08  0.29  0.24  0.99 -0.08  0.30  0.22
MR4 -0.04  1.00  0.00 -0.12 -0.04  1.00  0.00 -0.12
MR3  0.23 -0.01  0.99  0.04  0.23 -0.01  0.98  0.02
MR1 -0.08 -0.12  0.15  0.98 -0.07 -0.12  0.17  0.98
MR4  1.00 -0.08  0.28  0.22  1.00 -0.07  0.29  0.20
MR1 -0.05  1.00  0.00 -0.12 -0.05  1.00  0.00 -0.12
MR2  0.24 -0.01  0.99  0.08  0.24 -0.01  0.99  0.06
MR3 -0.05 -0.13  0.14  0.98 -0.04 -0.12  0.16  0.99
MR3  1.00 -0.07  0.27  0.15  1.00 -0.07  0.27  0.13
MR1 -0.06  1.00 -0.01 -0.13 -0.06  1.00 -0.01 -0.13
MR4  0.25 -0.01  1.00  0.15  0.25 -0.01  1.00  0.13
MR2  0.08 -0.13  0.16  1.00  0.08 -0.13  0.17  1.00
MR2  1.00 -0.06  0.26  0.12  1.00 -0.06  0.26  0.10
MR4 -0.06  1.00 -0.01 -0.13 -0.06  1.00 -0.01 -0.14
MR1  0.26 -0.01  1.00  0.17  0.26 -0.01  1.00  0.15
MR3  0.12 -0.13  0.17  1.00  0.13 -0.13  0.18  1.00
MR2  1.00 -0.06  0.26  0.13  1.00 -0.06  0.26  0.11
MR1 -0.06  1.00 -0.01 -0.13 -0.06  1.00 -0.01 -0.13
MR4  0.26 -0.01  1.00  0.18  0.26 -0.01  1.00  0.16
MR3  0.10 -0.14  0.15  1.00  0.11 -0.13  0.16  1.00

### Carga Fatorial

In [15]:
loadings_year <- lapply(
  efa_by_year,
  function(x){
    as.data.frame(unclass(x$loadings))
  }
)

In [16]:
loadings_year

$`2017`
                                                 MR2          MR4          MR3
Reading_Comprehension_Level              0.947425752 -0.139316664 -0.090193501
Active_Listening_Level                   0.897246038 -0.218419318 -0.105313656
Writing_Level                            0.930940943 -0.176328860 -0.101629474
Speaking_Level                           0.913178558 -0.225279933 -0.108636076
Mathematical_Reasoning_Level             0.501940334  0.004955666  0.354157555
Science_Level                            0.799232009  0.216807218 -0.092366807
Critical_Thinking_Level                  0.931805975 -0.060145722 -0.009455074
Active_Learning_Level                    0.936341553 -0.041765976  0.021636708
Learning_Strategies_Level                0.886806679  0.010559374 -0.009563183
Monitoring_Level                         0.866796960  0.103340362  0.091735465
Social_Perceptiveness_Level              0.735870416 -0.180514953  0.009696638
Coordination_Level                       0.567841257  0.070248812  0.283387681
Persuasion_Level                         0.638209582 -0.185720342  0.211222476
Negotiation_Level                        0.558734125 -0.200450998  0.249819358
Instructing_Level                        0.916578674  0.088643578 -0.056757885
Service_Orientation_Level                0.496359671 -0.271274584  0.126898748
Complex_Problem_Solving_Level            0.925365243  0.099428323  0.071407007
Operations_Analysis_Level                0.584818571  0.017057846  0.273588875
Technology_Design_Level                  0.344709560  0.369083266  0.285506871
Installation_Level                       0.056657619  0.609404715 -0.086204843
Programming_Level                        0.431113170  0.013749746  0.197564545
Operations_Monitoring_Level             -0.050113639  0.858761433  0.119774445
Operation_and_Control_Level             -0.174199445  0.820511416  0.043586642
Equipment_Maintenance_Level             -0.012593571  0.933392701 -0.156550837
Troubleshooting_Level                   -0.038797983  0.957715109  0.006317024
Repairing_Level                          0.003313729  0.932728362 -0.151094548
Quality_Control_Analysis_Level           0.066622439  0.827424046  0.180315416
Judgment_and_Decision_Making_Level       0.896083647  0.002516702  0.076771938
Systems_Analysis_Level                   0.809609925  0.076180173  0.207250149
Systems_Evaluation_Level                 0.840569306  0.110204641  0.198657808
Time_Management_Level                    0.730415396  0.041833666  0.238260924
Management_of_Financial_Resources_Level -0.034648750 -0.143018273  0.942639709
Management_of_Material_Resources_Level   0.068069732  0.058875200  0.855888102
Management_of_Personnel_Resources_Level  0.609383441  0.095628189  0.362165747
Equipment_Selection_Level               -0.013794731  0.915465861 -0.026228313
                                                MR1
Reading_Comprehension_Level             -0.15437358
Active_Listening_Level                   0.02942005
Writing_Level                           -0.07400233
Speaking_Level                           0.03369954
Mathematical_Reasoning_Level            -0.42452461
Science_Level                           -0.30795647
Critical_Thinking_Level                 -0.05829285
Active_Learning_Level                   -0.09240903
Learning_Strategies_Level                0.07419127
Monitoring_Level                         0.15348719
Social_Perceptiveness_Level              0.34367477
Coordination_Level                       0.36694907
Persuasion_Level                         0.28520177
Negotiation_Level                        0.33466564
Instructing_Level                        0.12491893
Service_Orientation_Level                0.31392110
Complex_Problem_Solving_Level           -0.10910160
Operations_Analysis_Level               -0.21277511
Technology_Design_Level                 -0.25656039
Installation_Level                      -0.04014297
Programming_Level                       -0.44811863
Operations_Monitoring_Level              0.01323481
Operation_and_Control_Level              0.07382363
Equipment_Maintenance_Level              0.02741905
Troubleshooting_Level                    0.01187202
Repairing_Level                          0.03120104
Quality_Control_Analysis_Level          -0.08887039
Judgment_and_Decision_Making_Level      -0.01959463
Systems_Analysis_Level                  -0.09031422
Systems_Evaluation_Level                -0.02051058
Time_Management_Level                    0.19663195
Management_of_Financial_Resources_Level -0.03515521
Management_of_Material_Resources_Level   0.02196737
Management_of_Personnel_Resources_Level  0.26982971
Equipment_Selection_Level               -0.02734868

$`2019`
                                                 MR4           MR1          MR2
Reading_Comprehension_Level              0.951518164 -0.1416370212 -0.094416917
Active_Listening_Level                   0.893709070 -0.2156191801 -0.100159346
Writing_Level                            0.932481243 -0.1746721579 -0.099193963
Speaking_Level                           0.909710822 -0.2252136714 -0.107579700
Mathematical_Reasoning_Level             0.528737625  0.0045794881  0.325518999
Science_Level                            0.801725437  0.2249801401 -0.087095906
Critical_Thinking_Level                  0.919965373 -0.0637695496  0.010876438
Active_Learning_Level                    0.938404730 -0.0507865925  0.011866823
Learning_Strategies_Level                0.898076328  0.0174259914 -0.029767324
Monitoring_Level                         0.841542681  0.0957493101  0.118019309
Social_Perceptiveness_Level              0.711778530 -0.1880563430  0.023887775
Coordination_Level                       0.526994090  0.0640860317  0.315382035
Persuasion_Level                         0.602866762 -0.1975143740  0.243910692
Negotiation_Level                        0.536450618 -0.2138693201  0.277164692
Instructing_Level                        0.916305910  0.0874399521 -0.065202255
Service_Orientation_Level                0.487782401 -0.2627192827  0.139832564
Complex_Problem_Solving_Level            0.926011242  0.0912637291  0.072960876
Operations_Analysis_Level                0.578993891  0.0202721381  0.295375780
Technology_Design_Level                  0.409815919  0.3552759396  0.259558633
Installation_Level                       0.090825295  0.6307830477 -0.105200265
Programming_Level                        0.514094302 -0.0001437413  0.162244517
Operations_Monitoring_Level             -0.045075603  0.8676604362  0.119479852
Operation_and_Control_Level             -0.174251655  0.8259716703  0.045510837
Equipment_Maintenance_Level             -0.008869031  0.9381539409 -0.153458875
Troubleshooting_Level                   -0.031836711  0.9653884737  0.002317877
Repairing_Level                          0.012428305  0.9373794507 -0.152234393
Quality_Control_Analysis_Level           0.007539739  0.8257883156  0.212771597
Judgment_and_Decision_Making_Level       0.889516738 -0.0006981951  0.086925613
Systems_Analysis_Level                   0.812556136  0.0768233028  0.211687934
Systems_Evaluation_Level                 0.835014784  0.0999584844  0.207220793
Time_Management_Level                    0.699981738  0.0435462748  0.268904558
Management_of_Financial_Resources_Level -0.028141752 -0.1414314754  0.939603809
Management_of_Material_Resources_Level   0.054560276  0.0673639193  0.865133753
Management_of_Personnel_Resources_Level  0.566049069  0.0936862593  0.404948354
Equipment_Selection_Level               -0.003556466  0.9195030206 -0.020895383
                                                 MR3
Reading_Comprehension_Level             -0.142777951
Active_Listening_Level                   0.041111673
Writing_Level                           -0.060906531
Speaking_Level                           0.042208926
Mathematical_Reasoning_Level            -0.424890952
Science_Level                           -0.315237599
Critical_Thinking_Level                 -0.052191700
Active_Learning_Level                   -0.070451252
Learning_Strategies_Level                0.098412575
Monitoring_Level                         0.158358287
Social_Perceptiveness_Level              0.369473014
Coordination_Level                       0.374023649
Persuasion_Level                         0.278164549
Negotiation_Level                        0.323226211
Instructing_Level                        0.145732636
Service_Orientation_Level                0.345931259
Complex_Problem_Solving_Level           -0.095944182
Operations_Analysis_Level               -0.218271423
Technology_Design_Level                 -0.281890221
Installation_Level                      -0.036520682
Programming_Level                       -0.468346854
Operations_Monitoring_Level              0.005144108
Operation_and_Control_Level              0.068964110
Equipment_Maintenance_Level              0.034392664
Troubleshooting_Level                    0.017454318
Repairing_Level                          0.038003772
Quality_Control_Analysis_Level          -0.090004262
Judgment_and_Decision_Making_Level      -0.022227977
Systems_Analysis_Level                  -0.080262541
Systems_Evaluation_Level                -0.024245635
Time_Management_Level                    0.205159059
Management_of_Financial_Resources_Level -0.039251462
Management_of_Material_Resources_Level   0.013665825
Management_of_Personnel_Resources_Level  0.276457298
Equipment_Selection_Level               -0.034690938

$`2021`
                                                 MR3          MR1          MR4
Reading_Comprehension_Level              0.965117652 -0.147895080 -0.097960220
Active_Listening_Level                   0.876992128 -0.214572005 -0.086193099
Writing_Level                            0.926397557 -0.189108780 -0.094270306
Speaking_Level                           0.891468480 -0.231189331 -0.092431938
Mathematical_Reasoning_Level             0.596862784  0.007688677  0.300388649
Science_Level                            0.854363563  0.223332034 -0.096243941
Critical_Thinking_Level                  0.917535688 -0.071521357  0.013194644
Active_Learning_Level                    0.940086425 -0.057036946  0.008587853
Learning_Strategies_Level                0.875930131  0.011836258 -0.028803296
Monitoring_Level                         0.792240329  0.094173281  0.143451608
Social_Perceptiveness_Level              0.637085293 -0.204859156  0.056391613
Coordination_Level                       0.430319066  0.046514628  0.370323079
Persuasion_Level                         0.513127817 -0.217269936  0.289599511
Negotiation_Level                        0.447137693 -0.225692634  0.326616610
Instructing_Level                        0.876744483  0.076821475 -0.050623420
Service_Orientation_Level                0.429564156 -0.265091678  0.155170819
Complex_Problem_Solving_Level            0.916088760  0.076231476  0.091685328
Operations_Analysis_Level                0.614608459  0.030052006  0.288848811
Technology_Design_Level                  0.497452351  0.354049853  0.217115974
Installation_Level                       0.093791494  0.634880551 -0.109896677
Programming_Level                        0.622448996  0.008036955  0.111496984
Operations_Monitoring_Level             -0.050058972  0.863902247  0.132753449
Operation_and_Control_Level             -0.181586521  0.830726117  0.050298203
Equipment_Maintenance_Level             -0.005229899  0.949620533 -0.160630447
Troubleshooting_Level                   -0.030107839  0.965320414  0.006441948
Repairing_Level                          0.012661861  0.946122254 -0.148220369
Quality_Control_Analysis_Level          -0.005940020  0.825546400  0.236691496
Judgment_and_Decision_Making_Level       0.869306037 -0.014011125  0.105349254
Systems_Analysis_Level                   0.823052993  0.087488830  0.209580769
Systems_Evaluation_Level                 0.825581190  0.098625641  0.217533502
Time_Management_Level                    0.631676505  0.024120050  0.310639554
Management_of_Financial_Resources_Level -0.033149466 -0.136697929  0.941098628
Management_of_Material_Resources_Level   0.044452847  0.066881022  0.871917884
Management_of_Personnel_Resources_Level  0.479225060  0.081865113  0.457898484
Equipment_Selection_Level                0.015004607  0.918566244 -0.030682903
                                                 MR2
Reading_Comprehension_Level             -0.102420213
Active_Listening_Level                   0.079698267
Writing_Level                           -0.021229252
Speaking_Level                           0.075403896
Mathematical_Reasoning_Level            -0.408747508
Science_Level                           -0.294897114
Critical_Thinking_Level                 -0.022006007
Active_Learning_Level                   -0.032202337
Learning_Strategies_Level                0.138516217
Monitoring_Level                         0.197985969
Social_Perceptiveness_Level              0.401638615
Coordination_Level                       0.390173853
Persuasion_Level                         0.311869146
Negotiation_Level                        0.346693099
Instructing_Level                        0.191140593
Service_Orientation_Level                0.361221198
Complex_Problem_Solving_Level           -0.064070304
Operations_Analysis_Level               -0.219788401
Technology_Design_Level                 -0.274408821
Installation_Level                      -0.015567562
Programming_Level                       -0.456854797
Operations_Monitoring_Level             -0.017738305
Operation_and_Control_Level              0.060375654
Equipment_Maintenance_Level              0.058218131
Troubleshooting_Level                    0.009307924
Repairing_Level                          0.060011193
Quality_Control_Analysis_Level          -0.114127267
Judgment_and_Decision_Making_Level       0.014346618
Systems_Analysis_Level                  -0.036193571
Systems_Evaluation_Level                 0.004537183
Time_Management_Level                    0.242461145
Management_of_Financial_Resources_Level -0.040485614
Management_of_Material_Resources_Level   0.005131305
Management_of_Personnel_Resources_Level  0.297981677
Equipment_Selection_Level               -0.036846675

$`2023`
                                                  MR2          MR4          MR1
Reading_Comprehension_Level              0.9668995117 -0.150641045 -0.099189790
Active_Listening_Level                   0.8685612394 -0.212988023 -0.085726478
Writing_Level                            0.9195482289 -0.195044185 -0.088869324
Speaking_Level                           0.8825281534 -0.235171524 -0.091868796
Mathematical_Reasoning_Level             0.6229524137  0.010874560  0.286474136
Science_Level                            0.8720755214  0.225092581 -0.104897190
Critical_Thinking_Level                  0.9192083776 -0.068822823  0.010041705
Active_Learning_Level                    0.9400469677 -0.060562150  0.006213119
Learning_Strategies_Level                0.8615396741  0.002194899 -0.026388673
Monitoring_Level                         0.7715479816  0.084700391  0.157454497
Social_Perceptiveness_Level              0.6065703322 -0.207003861  0.065325414
Coordination_Level                       0.4011911187  0.048317093  0.375223188
Persuasion_Level                         0.4753788834 -0.226430558  0.304957728
Negotiation_Level                        0.4099949796 -0.237312710  0.337226127
Instructing_Level                        0.8553994682  0.068893831 -0.036171230
Service_Orientation_Level                0.4028056188 -0.262412043  0.161355483
Complex_Problem_Solving_Level            0.9092600016  0.069071034  0.101287798
Operations_Analysis_Level                0.6240429417  0.027714548  0.298363124
Technology_Design_Level                  0.5110507375  0.339686837  0.224140984
Installation_Level                       0.1032688603  0.642531492 -0.108803253
Programming_Level                        0.6445429926  0.009187351  0.111751179
Operations_Monitoring_Level             -0.0553097361  0.865713428  0.133782721
Operation_and_Control_Level             -0.1837533963  0.838179977  0.046638319
Equipment_Maintenance_Level             -0.0065200457  0.951835092 -0.159862834
Troubleshooting_Level                   -0.0327834311  0.968244255  0.015479088
Repairing_Level                          0.0108661248  0.949160168 -0.147644268
Quality_Control_Analysis_Level          -0.0004488889  0.831093490  0.238060776
Judgment_and_Decision_Making_Level       0.8687597906 -0.014693685  0.102521953
Systems_Analysis_Level                   0.8278067912  0.092502152  0.206279976
Systems_Evaluation_Level                 0.8260468281  0.096499204  0.218247568
Time_Management_Level                    0.6073241635  0.028923095  0.325496831
Management_of_Financial_Resources_Level -0.0366086957 -0.135868908  0.944943882
Management_of_Material_Resources_Level   0.0398476244  0.067626027  0.875627701
Management_of_Personnel_Resources_Level  0.4369107252  0.065184573  0.486566519
Equipment_Selection_Level                0.0305174864  0.924504145 -0.040146514
                                                 MR3
Reading_Comprehension_Level             -0.087298887
Active_Listening_Level                   0.099458262
Writing_Level                           -0.010331145
Speaking_Level                           0.089096857
Mathematical_Reasoning_Level            -0.403773531
Science_Level                           -0.290039204
Critical_Thinking_Level                 -0.004889200
Active_Learning_Level                   -0.015128014
Learning_Strategies_Level                0.150777204
Monitoring_Level                         0.209429696
Social_Perceptiveness_Level              0.419377861
Coordination_Level                       0.410938726
Persuasion_Level                         0.326989095
Negotiation_Level                        0.357463565
Instructing_Level                        0.210624257
Service_Orientation_Level                0.382951630
Complex_Problem_Solving_Level           -0.046670095
Operations_Analysis_Level               -0.212192189
Technology_Design_Level                 -0.263865923
Installation_Level                      -0.012184701
Programming_Level                       -0.451404241
Operations_Monitoring_Level             -0.021528768
Operation_and_Control_Level              0.057482814
Equipment_Maintenance_Level              0.059600763
Troubleshooting_Level                    0.009159674
Repairing_Level                          0.063649643
Quality_Control_Analysis_Level          -0.114097173
Judgment_and_Decision_Making_Level       0.029403113
Systems_Analysis_Level                  -0.026197506
Systems_Evaluation_Level                 0.013306687
Time_Management_Level                    0.252533259
Management_of_Financial_Resources_Level -0.042382468
Management_of_Material_Resources_Level   0.006276924
Management_of_Personnel_Resources_Level  0.305713124
Equipment_Selection_Level               -0.034412240

$`2025`
                                                 MR2          MR1          MR4
Reading_Comprehension_Level              0.963197110 -0.148947493 -0.093674203
Active_Listening_Level                   0.872437307 -0.207004468 -0.085227036
Writing_Level                            0.923048196 -0.188451944 -0.087419776
Speaking_Level                           0.883030004 -0.230926521 -0.087121319
Mathematical_Reasoning_Level             0.618599162  0.009604417  0.282245730
Science_Level                            0.865181287  0.217030828 -0.112881400
Critical_Thinking_Level                  0.916746787 -0.062807763  0.011273500
Active_Learning_Level                    0.944811349 -0.062102833 -0.002225738
Learning_Strategies_Level                0.863473859 -0.004274665 -0.030725157
Monitoring_Level                         0.776642150  0.088196110  0.161170216

In [38]:
cargas_long <- bind_rows(
  lapply(names(loadings_year), function(y){

    loadings_year[[y]] %>%
      tibble::rownames_to_column("skill") %>%
      pivot_longer(
        starts_with("MR"),
        names_to = "factor",
        values_to = "loading"
      ) %>%
      mutate(year = y)

  })
)

In [42]:
print(cargas_long, n = Inf, width = Inf)

# A tibble: 1,050 × 4
     skill                                   factor    loading year
     <chr>                                   <chr>       <dbl> <chr>
   1 Reading_Comprehension_Level             MR1     0.821     2017
   2 Reading_Comprehension_Level             MR2    -0.155     2017
   3 Reading_Comprehension_Level             MR6    -0.00476   2017
   4 Reading_Comprehension_Level             MR4     0.235     2017
   5 Reading_Comprehension_Level             MR3    -0.158     2017
   6 Reading_Comprehension_Level             MR5    -0.0264    2017
   7 Active_Listening_Level                  MR1     0.709     2017
   8 Active_Listening_Level                  MR2    -0.153     2017
   9 Active_Listening_Level                  MR6     0.260     2017
  10 Active_Listening_Level                  MR4     0.142     2017
  11 Active_Listening_Level                  MR3    -0.210     2017
  12 Active_Listening_Level                  MR5    -0.0239    2017
  13 Writing_Level                           MR1     0.877     2017
  14 Writing_Level                           MR2    -0.178     2017
  15 Writing_Level                           MR6    -0.0202    2017
  16 Writing_Level                           MR4     0.114     2017
  17 Writing_Level                           MR3    -0.113     2017
  18 Writing_Level                           MR5    -0.0901    2017
  19 Speaking_Level                          MR1     0.816     2017
  20 Speaking_Level                          MR2    -0.182     2017
  21 Speaking_Level                          MR6     0.141     2017
  22 Speaking_Level                          MR4     0.0652    2017
  23 Speaking_Level                          MR3    -0.149     2017
  24 Speaking_Level                          MR5    -0.0711    2017
  25 Mathematical_Reasoning_Level            MR1     0.344     2017
  26 Mathematical_Reasoning_Level            MR2    -0.109     2017
  27 Mathematical_Reasoning_Level            MR6    -0.204     2017
  28 Mathematical_Reasoning_Level            MR4     0.521     2017
  29 Mathematical_Reasoning_Level            MR3     0.241     2017
  30 Mathematical_Reasoning_Level            MR5     0.0247    2017
  31 Science_Level                           MR1     0.728     2017
  32 Science_Level                           MR2     0.109     2017
  33 Science_Level                           MR6    -0.226     2017
  34 Science_Level                           MR4     0.323     2017
  35 Science_Level                           MR3    -0.202     2017
  36 Science_Level                           MR5     0.139     2017
  37 Critical_Thinking_Level                 MR1     0.725     2017
  38 Critical_Thinking_Level                 MR2    -0.0301    2017
  39 Critical_Thinking_Level                 MR6     0.198     2017
  40 Critical_Thinking_Level                 MR4     0.244     2017
  41 Critical_Thinking_Level                 MR3    -0.141     2017
  42 Critical_Thinking_Level                 MR5     0.00909   2017
  43 Active_Learning_Level                   MR1     0.856     2017
  44 Active_Learning_Level                   MR2    -0.0582    2017
  45 Active_Learning_Level                   MR6    -0.00278   2017
  46 Active_Learning_Level                   MR4     0.175     2017
  47 Active_Learning_Level                   MR3    -0.0291    2017
  48 Active_Learning_Level                   MR5    -0.0431    2017
  49 Learning_Strategies_Level               MR1     1.07      2017
  50 Learning_Strategies_Level               MR2    -0.0165    2017
  51 Learning_Strategies_Level               MR6    -0.167     2017
  52 Learning_Strategies_Level               MR4    -0.157     2017
  53 Learning_Strategies_Level               MR3     0.0704    2017
  54 Learning_Strategies_Level               MR5    -0.108     2017
  55 Monitoring_Level                        MR1     0.971     2017
  56 Monitoring_Level                        MR2     0.0754    2017
  57 Monitoring_Level                        MR6     0.00847   2017
  58 Monitoring_Level                        MR4    -0.131     2017
  59 Monitoring_Level                        MR3     0.0347    2017
  60 Monitoring_Level                        MR5     0.134     2017
  61 Social_Perceptiveness_Level             MR1     0.647     2017
  62 Social_Perceptiveness_Level             MR2    -0.0655    2017
  63 Social_Perceptiveness_Level             MR6     0.438     2017
  64 Social_Perceptiveness_Level             MR4    -0.153     2017
  65 Social_Perceptiveness_Level             MR3    -0.0808    2017
  66 Social_Perceptiveness_Level             MR5     0.0273    2017
  67 Coordination_Level                      MR1     0.608     2017
  68 Coordination_Level                      MR2     0.119     2017
  69 Coordination_Level                      MR6     0.295     2017
  70 Coordination_Level                      MR4    -0.222     2017
  71 Coordination_Level                      MR3     0.205     2017
  72 Coordination_Level                      MR5     0.110     2017
  73 Persuasion_Level                        MR1     0.379     2017
  74 Persuasion_Level                        MR2    -0.0301    2017
  75 Persuasion_Level                        MR6     0.628     2017
  76 Persuasion_Level                        MR4     0.0406    2017
  77 Persuasion_Level                        MR3     0.0471    2017
  78 Persuasion_Level                        MR5    -0.00114   2017
  79 Negotiation_Level                       MR1     0.331     2017
  80 Negotiation_Level                       MR2    -0.0433    2017
  81 Negotiation_Level                       MR6     0.636     2017
  82 Negotiation_Level                       MR4    -0.0191    2017
  83 Negotiation_Level                       MR3     0.0955    2017
  84 Negotiation_Level                       MR5     0.0127    2017
  85 Instructing_Level                       MR1     1.14      2017
  86 Instructing_Level                       MR2     0.0640    2017
  87 Instructing_Level                       MR6    -0.165     2017
  88 Instructing_Level                       MR4    -0.231     2017
  89 Instructing_Level                       MR3     0.0146    2017
  90 Instructing_Level                       MR5    -0.0584    2017
  91 Service_Orientation_Level               MR1     0.313     2017
  92 Service_Orientation_Level               MR2    -0.121     2017
  93 Service_Orientation_Level               MR6     0.552     2017
  94 Service_Orientation_Level               MR4    -0.0591    2017
  95 Service_Orientation_Level               MR3     0.0201    2017
  96 Service_Orientation_Level               MR5    -0.0349    2017
  97 Complex_Problem_Solving_Level           MR1     0.768     2017
  98 Complex_Problem_Solving_Level           MR2     0.0901    2017
  99 Complex_Problem_Solving_Level           MR6     0.0808    2017
 100 Complex_Problem_Solving_Level           MR4     0.260     2017
 101 Complex_Problem_Solving_Level           MR3    -0.0387    2017
 102 Complex_Problem_Solving_Level           MR5     0.00790   2017
 103 Operations_Analysis_Level               MR1     0.438     2017
 104 Operations_Analysis_Level               MR2    -0.0366    2017
 105 Operations_Analysis_Level               MR6    -0.0253    2017
 106 Operations_Analysis_Level               MR4     0.348     2017
 107 Operations_Analysis_Level               MR3     0.168     2017
 108 Operations_Analysis_Level               MR5     0.0194    2017
 109 Technology_Design_Level                 MR1     0.0321    2017
 110 Technology_Design_Level                 MR2     0.357     2017
 111 Technology_Design_Level                 MR6     0.135     2017
 112 Technology_Design_Level                 MR4     0.513     2017
 113 Technology_Design_Level                 MR3     0.133     2017
 114 Technology_Design_Level                 MR5    -0.00922   2017
 115 Installation_Level                      MR1    -0.00229   2017
 116 Installation_Level                      MR2     0.684     2017
 117 Installation_Level                      MR6     0.0406    2017
 118 Installation_Level                      MR4     0.0729    2017
 119 Installation_Level                      MR3    -0.00836   2017
 120 Installation_Level                      MR5    -0.287     2017
 121 Programming_Level                       MR1     0.0909    2017
 122 Programming_Level                       MR2    -0.0392    2017
 123 Programming_Level                       MR6    -0.0119    2017
 124 Programming_Level                       MR4     0.658     2017
 125 Programming_Level                       MR3     0.0486    2017
 126 Programming_Level                       MR5    -0.0330    2017
 127 Operations_Monitoring_Level             MR1    -0.0666    2017
 128 Operations_Monitoring_Level             MR2     0.805     2017
 129 Operations_Monitoring_Level             MR6     0.0488    2017
 130 Operations_Monitoring_Level             MR4     0.0542    2017
 131 Operations_Monitoring_Level             MR3    -0.0973    2017
 132 Operations_Monitoring_Level             MR5     0.479     2017
 133 Operation_and_Control_Level             MR1    -0.103     2017
 134 Operation_and_Control_Level             MR2     0.772     2017
 135 Operation_and_Control_Level             MR6    -0.00916   2017
 136 Operation_and_Control_Level             MR4    -0.0837    2017
 137 Operation_and_Control_Level             MR3    -0.0828    2017
 138 Operation_and_Control_Level             MR5     0.366     2017
 139 Equipment_Maintenance_Level             MR1     0.0572    2017
 140 Equipment_Maintenance_Level             MR2     0.966     2017
 141 Equipment_Maintenance_Level             MR6    -0.0657    2017
 142 Equipment_Maintenance_Level             MR4    -0.0863    2017
 143 Equipment_Maintenance_Level             MR3    -0.0613    2017
 144 Equipment_Maintenance_Level             MR5    -0.169     2017
 145 Troubleshooting_Level                   MR1    -0.0546    2017
 146 Troubleshooting_Level                   MR2     0.933     2017
 147 Troubleshooting_Level                   MR6     0.0181    2017
 148 Troubleshooting_Level                   MR4     0.0294    2017
 149 Troubleshooting_Level                   MR3    -0.0607    2017
 150 Troubleshooting_Level                   MR5     0.140     2017
 151 Repairing_Level                         MR1     0.0592    2017
 152 Repairing_Level                         MR2     0.998     2017
 153 Repairing_Level                         MR6    -0.0287    2017
 154 Repairing_Level                         MR4    -0.0779    2017
 155 Repairing_Level                         MR3    -0.0468    2017
 156 Repairing_Level                         MR5    -0.238     2017
 157 Quality_Control_Analysis_Level          MR1     0.0736    2017
 158 Quality_Control_Analysis_Level          MR2     0.737     2017
 159 Quality_Control_Analysis_Level          MR6    -0.105     2017
 160 Quality_Control_Analysis_Level          MR4     0.124     2017
 161 Quality_Control_Analysis_Level          MR3     0.0661    2017
 162 Quality_Control_Analysis_Level          MR5     0.254     2017
 163 Judgment_and_Decision_Making_Level      MR1     0.780     2017
 164 Judgment_and_Decision_Making_Level      MR2     0.00893   2017
 165 Judgment_and_Decision_Making_Level      MR6     0.115     2017
 166 Judgment_and_Decision_Making_Level      MR4     0.159     2017
 167 Judgment_and_Decision_Making_Level      MR3    -0.0145    2017
 168 Judgment_and_Decision_Making_Level      MR5     0.00390   2017
 169 Systems_Analysis_Level                  MR1     0.691     2017
 170 Systems_Analysis_Level                  MR2     0.0610    2017
 171 Systems_Analysis_Level                  MR6     0.0541    2017
 172 Systems_Analysis_Level                  MR4     0.233     2017
 173 Systems_Analysis_Level                  MR3     0.125     2017
 174 Systems_Analysis_Level                  MR5    -0.0304    2017
 175 Systems_Evaluation_Level                MR1     0.736     2017
 176 Systems_Evaluation_Level                MR2     0.110     2017
 177 Systems_Evaluation_Level                MR6     0.103     2017
 178 Systems_Evaluation_Level                MR4     0.171     2017
 179 Systems_Evaluation_Level                MR3     0.116     2017
 180 Systems_Evaluation_Level                MR5    -0.0225    2017
 181 Time_Management_Level                   MR1     0.773     2017
 182 Time_Management_Level                   MR2     0.0547    2017
 183 Time_Management_Level                   MR6     0.122     2017
 184 Time_Management_Level                   MR4    -0.103     2017
 185 Time_Management_Level                   MR3     0.208     2017
 186 Time_Management_Level                   MR5     0.00635   2017
 187 Management_of_Financial_Resources_Level MR1    -0.111     2017
 188 Management_of_Financial_Resources_Level MR2    -0.185     2017
 189 Management_of_Financial_Resources_Level MR6     0.0719    2017
 190 Management_of_Financial_Resources_Level MR4     0.240     2017
 191 Management_of_Financial_Resources_Level MR3     0.890     2017
 192 Management_of_Financial_Resources_Level MR5    -0.0610    2017
 193 Management_of_Material_Resources_Level  MR1     0.0952    2017
 194 Management_of_Material_Resources_Level  MR2    -0.00620   2017
 195 Management_of_Material_Resources_Level  MR6    -0.0195    2017
 196 Management_of_Material_Resources_Level  MR4     0.111     2017
 197 Management_of_Material_Resources_Level  MR3     0.844     2017
 198 Management_of_Material_Resources_Level  MR5    -0.0285    2017
 199 Management_of_Personnel_Resources_Level MR1     0.776     2017
 200 Management_of_Personnel_Resources_Level MR2     0.0799    2017
 201 Management_of_Personnel_Resources_Level MR6     0.0432    2017
 202 Management_of_Personnel_Resources_Level MR4    -0.239     2017
 203 Management_of_Personnel_Resources_Level MR3     0.362     2017
 204 Management_of_Personnel_Resources_Level MR5     0.0629    2017
 205 Equipment_Selection_Level               MR1    -0.00911   2017
 206 Equipment_Selection_Level               MR2     0.923     2017
 207 Equipment_Selection_Level               MR6    -0.0444    2017
 208 Equipment_Selection_Level               MR4     0.0292    2017
 209 Equipment_Selection_Level               MR3     0.0188    2017
 210 Equipment_Selection_Level               MR5    -0.110     2017
 211 Reading_Comprehension_Level             MR4     0.741     2019
 212 Reading_Comprehension_Level             MR1     0.204     2019
 213 Reading_Comprehension_Level             MR2    -0.161     2019
 214 Reading_Comprehension_Level             MR3    -0.153     2019
 215 Reading_Comprehension_Level             MR6     0.102     2019
 216 Reading_Comprehension_Level             MR5     0.0191    2019
 217 Active_Listening_Level                  MR4     0.498     2019
 218 Active_Listening_Level                  MR1     0.529     2019
 219 Active_Listening_Level                  MR2    -0.151     2019
 220 Active_Listening_Level                  MR3    -0.210     2019
 221 Active_Listening_Level                  MR6    -0.00839   2019
 222 Active_Listening_Level                  MR5     0.0257    2019
 223 Writing_Level                           MR4     0.602     2019
 224 Writing_Level                           MR1     0.245     2019
 225 Writing_Level                           MR2    -0.189     2019
 226 Writing_Level                           MR3    -0.107     2019
 227 Writing_Level                           MR6     0.189     2019
 228 Writing_Level                           MR5     0.0783    2019
 229 Speaking_Level                          MR4     0.471     2019
 230 Speaking_Level                          MR1     0.425     2019
 231 Speaking_Level                          MR2    -0.196     2019
 232 Speaking_Level                          MR3    -0.143     2019
 233 Speaking_Level                          MR6     0.133     2019
 234 Speaking_Level                          MR5     0.0731    2019
 235 Mathematical_Reasoning_Level            MR4     0.858     2019
 236 Mathematical_Reasoning_Level            MR1    -0.263     2019
 237 Mathematical_Reasoning_Level            MR2    -0.114     2019
 238 Mathematical_Reasoning_Level            MR3     0.247     2019
 239 Mathematical_Reasoning_Level            MR6     0.0184    2019
 240 Mathematical_Reasoning_Level            MR5    -0.0282    2019
 241 Science_Level                           MR4     0.922     2019
 242 Science_Level                           MR1    -0.128     2019
 243 Science_Level                           MR2     0.127     2019
 244 Science_Level                           MR3    -0.200     2019
 245 Science_Level                           MR6     0.0839    2019
 246 Science_Level                           MR5    -0.169     2019
 247 Critical_Thinking_Level                 MR4     0.642     2019
 248 Critical_Thinking_Level                 MR1     0.446     2019
 249 Critical_Thinking_Level                 MR2    -0.0281    2019
 250 Critical_Thinking_Level                 MR3    -0.126     2019
 251 Critical_Thinking_Level                 MR6    -0.0224    2019
 252 Critical_Thinking_Level                 MR5    -0.000787  2019
 253 Active_Learning_Level                   MR4     0.633     2019
 254 Active_Learning_Level                   MR1     0.273     2019
 255 Active_Learning_Level                   MR2    -0.0735    2019
 256 Active_Learning_Level                   MR3    -0.0327    2019
 257 Active_Learning_Level                   MR6     0.174     2019
 258 Active_Learning_Level                   MR5     0.0400    2019
 259 Learning_Strategies_Level               MR4     0.332     2019
 260 Learning_Strategies_Level               MR1     0.244     2019
 261 Learning_Strategies_Level               MR2    -0.0366    2019
 262 Learning_Strategies_Level               MR3     0.0497    2019
 263 Learning_Strategies_Level               MR6     0.505     2019
 264 Learning_Strategies_Level               MR5     0.0899    2019
 265 Monitoring_Level                        MR4     0.317     2019
 266 Monitoring_Level                        MR1     0.508     2019
 267 Monitoring_Level                        MR2     0.0761    2019
 268 Monitoring_Level                        MR3     0.0160    2019
 269 Monitoring_Level                        MR6     0.268     2019
 270 Monitoring_Level                        MR5    -0.142     2019
 271 Social_Perceptiveness_Level             MR4    -0.0127    2019
 272 Social_Perceptiveness_Level             MR1     0.894     2019
 273 Social_Perceptiveness_Level             MR2    -0.0689    2019
 274 Social_Perceptiveness_Level             MR3    -0.100     2019
 275 Social_Perceptiveness_Level             MR6     0.0448    2019
 276 Social_Perceptiveness_Level             MR5    -0.0163    2019
 277 Coordination_Level                      MR4    -0.113     2019
 278 Coordination_Level                      MR1     0.819     2019
 279 Coordination_Level                      MR2     0.129     2019
 280 Coordination_Level                      MR3     0.166     2019
 281 Coordination_Level                      MR6     0.109     2019
 282 Coordination_Level                      MR5    -0.113     2019
 283 Persuasion_Level                        MR4     0.0499    2019
 284 Persuasion_Level                        MR1     1.00      2019
 285 Persuasion_Level                        MR2    -0.0209    2019
 286 Persuasion_Level                        MR3     0.0309    2019
 287 Persuasion_Level                        MR6    -0.226     2019
 288 Persuasion_Level                        MR5     0.0355    2019
 289 Negotiation_Level                       MR4    -0.0498    2019
 290 Negotiation_Level                       MR1     0.999     2019
 291 Negotiation_Level                       MR2    -0.0470    2019

### 16. Modelo CFA inicial

In [17]:
modelo_4f <- '

# Fator Cognitivo
Cognitive =~
  Reading_Comprehension_Level +
  Active_Listening_Level +
  Writing_Level +
  Speaking_Level +
  Science_Level +
  Critical_Thinking_Level +
  Active_Learning_Level +
  Learning_Strategies_Level +
  Instructing_Level +
  Complex_Problem_Solving_Level +
  Judgment_and_Decision_Making_Level +
  Systems_Analysis_Level +
  Systems_Evaluation_Level

# Fator Técnico
Technical =~
  Installation_Level +
  Operations_Monitoring_Level +
  Operation_and_Control_Level +
  Equipment_Maintenance_Level +
  Troubleshooting_Level +
  Repairing_Level +
  Quality_Control_Analysis_Level +
  Equipment_Selection_Level

# Gestão de Recursos
Resource_Management =~
  Management_of_Financial_Resources_Level +
  Management_of_Material_Resources_Level +
  Management_of_Personnel_Resources_Level

# Habilidades Sociais
Social =~
  Social_Perceptiveness_Level +
  Coordination_Level +
  Persuasion_Level +
  Negotiation_Level +
  Service_Orientation_Level +
  Time_Management_Level

'

In [38]:
model_cfa2 <- '

# Cognitivo
soft =~
 Systems_Evaluation_Level +
 Complex_Problem_Solving_Level +
 Systems_Analysis_Level +
 Judgment_and_Decision_Making_Level +
 Active_Learning_Level +
 Critical_Thinking_Level +
 Monitoring_Level +
 Time_Management_Level +
 Reading_Comprehension_Level +
 Learning_Strategies_Level +
 Instructing_Level +
 Writing_Level 


# Técnico-operacional
hard =~
 Troubleshooting_Level +
 Equipment_Selection_Level +
 Quality_Control_Analysis_Level +
 Operations_Monitoring_Level +
 Equipment_Maintenance_Level +
 Repairing_Level +
 Operation_and_Control_Level +
 Installation_Level

'

In [60]:
modelo_3f <- '

# Fator Cognitivo
Cognitive =~
    Science_Level +
    Reading_Comprehension_Level +
    Active_Learning_Level +
    Complex_Problem_Solving_Level +
    Writing_Level +
    Programming_Level +
    Critical_Thinking_Level  +
    Mathematical_Reasoning_Level +
    Judgment_and_Decision_Making_Level +
    Systems_Analysis_Level +
    Speaking_Level +
    Active_Listening_Level +
    Systems_Evaluation_Level

# Fator Técnico
Technical =~
    Troubleshooting_Level +
    Equipment_Selection_Level +
    Quality_Control_Analysis_Level +
    Operations_Monitoring_Level +
    Equipment_Maintenance_Level +
    Repairing_Level +
    Operation_and_Control_Level     

# Gestão
Management =~
    Management_of_Personnel_Resources_Level +
    Management_of_Material_Resources_Level +
    Coordination_Level +
    Management_of_Financial_Resources_Level +
    Negotiation_Level 

'

### 17. CFA Tradicional

In [18]:
fit_4f <- cfa(
  modelo_4f,
  data = efa_global,
  estimator = "MLR",
  std.lv = TRUE
)

fitMeasures(
  fit_4f,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     36115.350        399.000          0.000          0.770          0.750
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.171          0.170          0.173          0.113

In [61]:
fit_3f <- cfa(
  modelo_3f,
  data = efa_global,
  estimator = "MLR",
  std.lv = TRUE
)

fitMeasures(
  fit_3f,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     30084.192        272.000          0.000          0.763          0.739
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.190          0.188          0.191          0.118

In [ ]:
fit_cfa2 <- cfa(
  model_cfa2,
  data = efa_global,
  estimator = "MLR",
  std.lv = TRUE
)

fitMeasures(
  fit_cfa2,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

### CFA Bayesiano

In [48]:
model_cfa <- '

Cognitive =~
 Reading_Comprehension_Level +
 Active_Listening_Level +
 Writing_Level +
 Speaking_Level +
 Science_Level +
 Critical_Thinking_Level +
 Active_Learning_Level +
 Learning_Strategies_Level +
 Instructing_Level +
 Complex_Problem_Solving_Level +
 Judgment_and_Decision_Making_Level +
 Systems_Analysis_Level +
 Systems_Evaluation_Level

Technical =~
 Installation_Level +
 Operations_Monitoring_Level +
 Operation_and_Control_Level +
 Equipment_Maintenance_Level +
 Troubleshooting_Level +
 Repairing_Level +
 Quality_Control_Analysis_Level +
 Equipment_Selection_Level

Management =~
 Management_of_Financial_Resources_Level +
 Management_of_Material_Resources_Level +
 Management_of_Personnel_Resources_Level

Social =~
 Social_Perceptiveness_Level +
 Coordination_Level +
 Persuasion_Level +
 Negotiation_Level +
 Service_Orientation_Level +
 Time_Management_Level

'

In [50]:
fit_bayes <- bcfa(
  model_cfa,
  data = efa_global,
  std.lv = TRUE,

  burnin = 5000,
  sample = 20000,
  n.chains = 4
)

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 1).
Chain 1:
Chain 1: Gradient evaluation took 0.008587 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 85.87 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1:
Chain 1:
Chain 1: Iteration:     1 / 25000 [  0%]  (Warmup)
Chain 1: Iteration:  2500 / 25000 [ 10%]  (Warmup)
Chain 1: Iteration:  5000 / 25000 [ 20%]  (Warmup)
Chain 1: Iteration:  5001 / 25000 [ 20%]  (Sampling)
Chain 1: Iteration:  7500 / 25000 [ 30%]  (Sampling)
Chain 1: Iteration: 10000 / 25000 [ 40%]  (Sampling)
Chain 1: Iteration: 12500 / 25000 [ 50%]  (Sampling)
Chain 1: Iteration: 15000 / 25000 [ 60%]  (Sampling)
Chain 1: Iteration: 17500 / 25000 [ 70%]  (Sampling)
Chain 1: Iteration: 20000 / 25000 [ 80%]  (Sampling)
Chain 1: Iteration: 22500 / 25000 [ 90%]  (Sampling)
Chain 1: Iteration: 25000 / 25000 [100%]  (Sampling)
Chain 1:
Chain 1:  Elapsed Time: 578.087 seconds (Warm-up)
Chain 1:                2646.17 seconds (Sampling)
Chain 1:                3224.26 seconds (Total)
Chain 1:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 2).
Chain 2:
Chain 2: Gradient evaluation took 0.004465 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 44.65 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2:
Chain 2:
Chain 2: Iteration:     1 / 25000 [  0%]  (Warmup)
Chain 2: Iteration:  2500 / 25000 [ 10%]  (Warmup)
Chain 2: Iteration:  5000 / 25000 [ 20%]  (Warmup)
Chain 2: Iteration:  5001 / 25000 [ 20%]  (Sampling)
Chain 2: Iteration:  7500 / 25000 [ 30%]  (Sampling)
Chain 2: Iteration: 10000 / 25000 [ 40%]  (Sampling)
Chain 2: Iteration: 12500 / 25000 [ 50%]  (Sampling)
Chain 2: Iteration: 15000 / 25000 [ 60%]  (Sampling)
Chain 2: Iteration: 17500 / 25000 [ 70%]  (Sampling)
Chain 2: Iteration: 20000 / 25000 [ 80%]  (Sampling)
Chain 2: Iteration: 22500 / 25000 [ 90%]  (Sampling)
Chain 2: Iteration: 25000 / 25000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 678.628 seconds (Warm-up)
Chain 2:                3323.2 seconds (Sampling)
Chain 2:                4001.83 seconds (Total)
Chain 2:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 3).
Chain 3:
Chain 3: Gradient evaluation took 0.010931 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 109.31 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3:
Chain 3:
Chain 3: Iteration:     1 / 25000 [  0%]  (Warmup)
Chain 3: Iteration:  2500 / 25000 [ 10%]  (Warmup)
Chain 3: Iteration:  5000 / 25000 [ 20%]  (Warmup)
Chain 3: Iteration:  5001 / 25000 [ 20%]  (Sampling)
Chain 3: Iteration:  7500 / 25000 [ 30%]  (Sampling)
Chain 3: Iteration: 10000 / 25000 [ 40%]  (Sampling)
Chain 3: Iteration: 12500 / 25000 [ 50%]  (Sampling)
Chain 3: Iteration: 15000 / 25000 [ 60%]  (Sampling)
Chain 3: Iteration: 17500 / 25000 [ 70%]  (Sampling)
Chain 3: Iteration: 20000 / 25000 [ 80%]  (Sampling)
Chain 3: Iteration: 22500 / 25000 [ 90%]  (Sampling)
Chain 3: Iteration: 25000 / 25000 [100%]  (Sampling)
Chain 3:
Chain 3:  Elapsed Time: 721.794 seconds (Warm-up)
Chain 3:                2537.15 seconds (Sampling)
Chain 3:                3258.94 seconds (Total)
Chain 3:

SAMPLING FOR MODEL 'stanmarg' NOW (CHAIN 4).
Chain 4:
Chain 4: Gradient evaluation took 0.011446 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 114.46 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:     1 / 25000 [  0%]  (Warmup)
Chain 4: Iteration:  2500 / 25000 [ 10%]  (Warmup)
Chain 4: Iteration:  5000 / 25000 [ 20%]  (Warmup)
Chain 4: Iteration:  5001 / 25000 [ 20%]  (Sampling)
Chain 4: Iteration:  7500 / 25000 [ 30%]  (Sampling)
Chain 4: Iteration: 10000 / 25000 [ 40%]  (Sampling)
Chain 4: Iteration: 12500 / 25000 [ 50%]  (Sampling)
Chain 4: Iteration: 15000 / 25000 [ 60%]  (Sampling)
Chain 4: Iteration: 17500 / 25000 [ 70%]  (Sampling)
Chain 4: Iteration: 20000 / 25000 [ 80%]  (Sampling)
Chain 4: Iteration: 22500 / 25000 [ 90%]  (Sampling)
Chain 4: Iteration: 25000 / 25000 [100%]  (Sampling)
Chain 4:
Chain 4:  Elapsed Time: 687.522 seconds (Warm-up)
Chain 4:                3037.41 seconds (Sampling)
Chain 4:                3724.93 seconds (Total)
Chain 4:
Computing post-estimation metrics (including lvs if requested)...

In [52]:
summary(
  fit_bayes,
  standardized = TRUE
)

blavaan 0.5.10 ended normally after 20000 iterations

  Estimator                                      BAYES
  Optimization method                             MCMC
  Number of model parameters                        66

  Number of observations                          3050

  Statistic                                 MargLogLik         PPP
  Value                                     -31849.478       0.000

Parameter Estimates:


Latent Variables:
                   Estimate  Post.SD pi.lower pi.upper   Std.lv  Std.all
  Cognitive =~
    Rdng_Cmprhns_L    0.658    0.009    0.640    0.676    0.658    0.950
    Actv_Lstnng_Lv    0.491    0.007    0.477    0.506    0.491    0.921
    Writing_Level     0.673    0.010    0.654    0.692    0.673    0.942
    Speaking_Level    0.568    0.008    0.551    0.584    0.568    0.934
    Science_Level     0.721    0.017    0.688    0.755    0.721    0.669
    Crtcl_Thnkng_L    0.493    0.007    0.480    0.507    0.493    0.951
    Actv_Lrnng_Lvl    0.611    0.008    0.595    0.628    0.611    0.961
    Lrnng_Strtgs_L    0.578    0.010    0.560    0.597    0.578    0.867
    Instructng_Lvl    0.535    0.009    0.517    0.554    0.535    0.842
    Cmplx_Prbl_S_L    0.488    0.007    0.474    0.502    0.488    0.924
    Jdgmnt_n_D_M_L    0.493    0.007    0.479    0.507    0.493    0.937
    Systms_Anlys_L    0.581    0.009    0.563    0.599    0.581    0.885
    Systms_Evltn_L    0.613    0.010    0.594    0.632    0.613    0.895
  Technical =~
    Installatn_Lvl    0.396    0.010    0.377    0.415    0.396    0.659
    Oprtns_Mntrn_L    0.648    0.012    0.624    0.672    0.648    0.787
    Oprtn_nd_Cnt_L    0.810    0.015    0.781    0.839    0.810    0.808
    Eqpmnt_Mntnn_L    1.000    0.013    0.975    1.026    1.000    0.989
    Troblshtng_Lvl    0.846    0.013    0.821    0.872    0.846    0.912
    Repairing_Levl    1.008    0.013    0.982    1.035    1.008    0.985
    Qlty_Cntrl_A_L    0.591    0.012    0.567    0.615    0.591    0.743
    Eqpmnt_Slctn_L    0.769    0.011    0.747    0.791    0.769    0.930
  Management =~
    Mngmnt_f_F_R_L    0.665    0.010    0.646    0.684    0.665    0.940
    Mngmnt_f_M_R_L    0.602    0.009    0.585    0.620    0.602    0.936
    Mngmnt_f_P_R_L    0.419    0.009    0.402    0.436    0.419    0.751
  Social =~
    Scl_Prcptvns_L    0.469    0.008    0.454    0.484    0.469    0.875
    Coordinatn_Lvl    0.316    0.006    0.304    0.329    0.316    0.773
    Persuasion_Lvl    0.543    0.008    0.528    0.558    0.543    0.954
    Negotiatin_Lvl    0.521    0.008    0.507    0.537    0.521    0.938
    Srvc_Ornttn_Lv    0.424    0.008    0.409    0.439    0.424    0.820
    Tim_Mngmnt_Lvl    0.336    0.006    0.324    0.348    0.336    0.819
     Rhat    Prior

    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)

    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)

    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)

    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)
    1.000    normal(0,10)

Covariances:
                   Estimate  Post.SD pi.lower pi.upper   Std.lv  Std.all
  Cognitive ~~
    Technical        -0.403    0.015   -0.433   -0.373   -0.403   -0.403
    Management        0.570    0.013    0.544    0.595    0.570    0.570
    Social            0.841    0.006    0.830    0.853    0.841    0.841
  Technical ~~
    Management       -0.126    0.019   -0.163   -0.089   -0.126   -0.126
    Social           -0.507    0.014   -0.534   -0.480   -0.507   -0.507
  Management ~~
    Social            0.649    0.012    0.625    0.671    0.649    0.649
     Rhat    Prior

    1.000     lkj_corr(1)
    1.000     lkj_corr(1)
    1.000     lkj_corr(1)

    1.000     lkj_corr(1)
    1.000     lkj_corr(1)

    1.000     lkj_corr(1)

Variances:
                   Estimate  Post.SD pi.lower pi.upper   Std.lv  Std.all
   .Rdng_Cmprhns_L    0.047    0.001    0.044    0.050    0.047    0.098
   .Actv_Lstnng_Lv    0.043    0.001    0.041    0.045    0.043    0.151
   .Writing_Level     0.057    0.002    0.054    0.060    0.057    0.112
   .Speaking_Level    0.047    0.001    0.045    0.050    0.047    0.128
   .Science_Level     0.643    0.017    0.611    0.677    0.643    0.553
   .Crtcl_Thnkng_L    0.026    0.001    0.024    0.027    0.026    0.095
   .Actv_Lrnng_Lvl    0.031    0.001    0.029    0.033    0.031    0.076
   .Lrnng_Strtgs_L    0.111    0.003    0.105    0.117    0.111    0.249
   .Instructng_Lvl    0.118    0.003    0.112    0.124    0.118    0.291
   .Cmplx_Prbl_S_L    0.040    0.001    0.038    0.043    0.040    0.145
   .Jdgmnt_n_D_M_L    0.034    0.001    0.032    0.036    0.034    0.123
   .Systms_Anlys_L    0.093    0.003    0.088    0.098    0.093    0.216
   .Systms_Evltn_L    0.093    0.003    0.088    0.098    0.093    0.198
   .Installatn_Lvl    0.205    0.005    0.195    0.215    0.205    0.566
   .Oprtns_Mntrn_L    0.258    0.007    0.245    0.272    0.258    0.381
   .Oprtn_nd_Cnt_L    0.350    0.009    0.332    0.368    0.350    0.348
   .Eqpmnt_Mntnn_L    0.023    0.001    0.021    0.025    0.023    0.023
   .Troblshtng_Lvl    0.145    0.004    0.137    0.154    0.145    0.169
   .Repairing_Levl    0.030    0.001    0.028    0.033    0.030    0.029
   .Qlty_Cntrl_A_L    0.283    0.008    0.269    0.298    0.283    0.448
   .Eqpmnt_Slctn_L    0.093    0.003    0.088    0.098    0.093    0.135
   .Mngmnt_f_F_R_L    0.058    0.003    0.053    0.064    0.058    0.117
   .Mngmnt_f_M_R_L    0.051    0.002    0.046    0.056    0.051    0.124
   .Mngmnt_f_P_R_L    0.136    0.004    0.128    0.143    0.136    0.436
   .Scl_Prcptvns_L    0.067    0.002    0.063    0.071    0.067    0.234
   .Coordinatn_Lvl    0.068    0.002    0.064    0.071    0.068    0.403
   .Persuasion_Lvl    0.029    0.001    0.027    0.031    0.029    0.089
   .Negotiatin_Lvl    0.037    0.001    0.035    0.040    0.037    0.121
   .Srvc_Ornttn_Lv    0.088    0.002    0.083    0.092    0.088    0.328
   .Tim_Mngmnt_Lvl    0.055    0.002    0.052    0.059    0.055    0.329
    Cognitive         1.000                               1.000    1.000
    Technical         1.000                               1.000    1.000
    Management        1.000                               1.000    1.000
    Social            1.000                               1.000    1.000
     Rhat    Prior
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]
    1.000 gamma(1,.5)[sd]

### Diagnóstico de convergência

In [53]:
blavInspect(fit_bayes, "rhat")

                                          Cognitive=~Reading_Comprehension_Level
                                                                       1.0000473
                                               Cognitive=~Active_Listening_Level
                                                                       1.0000838
                                                        Cognitive=~Writing_Level
                                                                       1.0000731
                                                       Cognitive=~Speaking_Level
                                                                       1.0000467
                                                        Cognitive=~Science_Level
                                                                       0.9999934
                                              Cognitive=~Critical_Thinking_Level
                                                                       1.0000563
                                                Cognitive=~Active_Learning_Level
                                                                       1.0000406
                                            Cognitive=~Learning_Strategies_Level
                                                                       1.0000420
                                                    Cognitive=~Instructing_Level
                                                                       1.0000332
                                        Cognitive=~Complex_Problem_Solving_Level
                                                                       1.0000120
                                   Cognitive=~Judgment_and_Decision_Making_Level
                                                                       1.0001050
                                               Cognitive=~Systems_Analysis_Level
                                                                       1.0000700
                                             Cognitive=~Systems_Evaluation_Level
                                                                       1.0000461
                                                   Technical=~Installation_Level
                                                                       1.0000068
                                          Technical=~Operations_Monitoring_Level
                                                                       0.9999738
                                          Technical=~Operation_and_Control_Level
                                                                       1.0000059
                                          Technical=~Equipment_Maintenance_Level
                                                                       1.0000291
                                                Technical=~Troubleshooting_Level
                                                                       0.9999937
                                                      Technical=~Repairing_Level
                                                                       1.0000177
                                       Technical=~Quality_Control_Analysis_Level
                                                                       0.9999838
                                            Technical=~Equipment_Selection_Level
                                                                       1.0000405
                             Management=~Management_of_Financial_Resources_Level
                                                                       1.0000451
                              Management=~Management_of_Material_Resources_Level
                                                                       1.0000932
                             Management=~Management_of_Personnel_Resources_Level
                                                                       1.0000188
                                             Social=~Social_Perceptiveness_Level
                                                                       1.0000172
                                                      Social=~Coordination_Level
                                                                       1.0000057
                                                        Social=~Persuasion_Level
                                                                       1.0000396
                                                       Social=~Negotiation_Level
                                                                       1.0000218
                                               Social=~Service_Orientation_Level
                                                                       1.0000262
                                                   Social=~Time_Management_Level
                                                                       1.0000248
                        Reading_Comprehension_Level~~Reading_Comprehension_Level
                                                                       0.9999838
                                  Active_Listening_Level~~Active_Listening_Level
                                                                       0.9999722
                                                    Writing_Level~~Writing_Level
                                                                       0.9999797
                                                  Speaking_Level~~Speaking_Level
                                                                       0.9999875
                                                    Science_Level~~Science_Level
                                                                       0.9999949
                                Critical_Thinking_Level~~Critical_Thinking_Level
                                                                       0.9999905
                                    Active_Learning_Level~~Active_Learning_Level
                                                                       1.0000093
                            Learning_Strategies_Level~~Learning_Strategies_Level
                                                                       0.9999750
                                            Instructing_Level~~Instructing_Level
                                                                       0.9999713
                    Complex_Problem_Solving_Level~~Complex_Problem_Solving_Level
                                                                       0.9999817
          Judgment_and_Decision_Making_Level~~Judgment_and_Decision_Making_Level
                                                                       0.9999829
                                  Systems_Analysis_Level~~Systems_Analysis_Level
                                                                       0.9999960
                              Systems_Evaluation_Level~~Systems_Evaluation_Level
                                                                       0.9999714
                                          Installation_Level~~Installation_Level
                                                                       0.9999761
                        Operations_Monitoring_Level~~Operations_Monitoring_Level
                                                                       0.9999946
                        Operation_and_Control_Level~~Operation_and_Control_Level
                                                                       0.9999811
                        Equipment_Maintenance_Level~~Equipment_Maintenance_Level
                                                                       1.0000034
                                    Troubleshooting_Level~~Troubleshooting_Level
                                                                       0.9999536
                                                Repairing_Level~~Repairing_Level
                                                                       0.9999912
                  Quality_Control_Analysis_Level~~Quality_Control_Analysis_Level
                                                                       0.9999880
                            Equipment_Selection_Level~~Equipment_Selection_Level
                                                                       0.9999942
Management_of_Financial_Resources_Level~~Management_of_Financial_Resources_Level
                                                                       0.9999891
  Management_of_Material_Resources_Level~~Management_of_Material_Resources_Level
                                                                       0.9999728
Management_of_Personnel_Resources_Level~~Management_of_Personnel_Resources_Level
                                                                       0.9999661
                        Social_Perceptiveness_Level~~Social_Perceptiveness_Level
                                                                       1.0000357
                                          Coordination_Level~~Coordination_Level
                                                                       1.0000015
                                              Persuasion_Level~~Persuasion_Level
                                                                       0.9999995
                                            Negotiation_Level~~Negotiation_Level
                                                                       1.0000267
                            Service_Orientation_Level~~Service_Orientation_Level
                                                                       0.9999650
                                    Time_Management_Level~~Time_Management_Level
                                                                       1.0000194
                                                            Cognitive~~Technical
                                                                       0.9999675
                                                           Cognitive~~Management
                                                                       1.0000166
                                                               Cognitive~~Social
                                                                       1.0000527
                                                           Technical~~Management
                                                                       0.9999882
                                                               Technical~~Social
                                                                       1.0000041
                                                              Management~~Social
                                                                       1.0000439

### Effective Sample Size

In [54]:
blavInspect(fit_bayes, "neff")

                                          Cognitive=~Reading_Comprehension_Level
                                                                        10634.27
                                               Cognitive=~Active_Listening_Level
                                                                        11484.58
                                                        Cognitive=~Writing_Level
                                                                        10853.05
                                                       Cognitive=~Speaking_Level
                                                                        11004.18
                                                        Cognitive=~Science_Level
                                                                        25070.14
                                              Cognitive=~Critical_Thinking_Level
                                                                        10527.80
                                                Cognitive=~Active_Learning_Level
                                                                        10084.82
                                            Cognitive=~Learning_Strategies_Level
                                                                        13727.17
                                                    Cognitive=~Instructing_Level
                                                                        15083.91
                                        Cognitive=~Complex_Problem_Solving_Level
                                                                        11460.28
                                   Cognitive=~Judgment_and_Decision_Making_Level
                                                                        11135.22
                                               Cognitive=~Systems_Analysis_Level
                                                                        12755.35
                                             Cognitive=~Systems_Evaluation_Level
                                                                        12570.90
                                                   Technical=~Installation_Level
                                                                        39759.21
                                          Technical=~Operations_Monitoring_Level
                                                                        29561.02
                                          Technical=~Operation_and_Control_Level
                                                                        27704.22
                                          Technical=~Equipment_Maintenance_Level
                                                                        17948.80
                                                Technical=~Troubleshooting_Level
                                                                        21702.30
                                                      Technical=~Repairing_Level
                                                                        18046.05
                                       Technical=~Quality_Control_Analysis_Level
                                                                        32453.97
                                            Technical=~Equipment_Selection_Level
                                                                        20596.14
                             Management=~Management_of_Financial_Resources_Level
                                                                        30595.22
                              Management=~Management_of_Material_Resources_Level
                                                                        30473.99
                             Management=~Management_of_Personnel_Resources_Level
                                                                        44302.74
                                             Social=~Social_Perceptiveness_Level
                                                                        16610.62
                                                      Social=~Coordination_Level
                                                                        23060.89
                                                        Social=~Persuasion_Level
                                                                        13177.53
                                                       Social=~Negotiation_Level
                                                                        13822.74
                                               Social=~Service_Orientation_Level
                                                                        19723.86
                                                   Social=~Time_Management_Level
                                                                        19817.73
                        Reading_Comprehension_Level~~Reading_Comprehension_Level
                                                                        86872.76
                                  Active_Listening_Level~~Active_Listening_Level
                                                                        94246.76
                                                    Writing_Level~~Writing_Level
                                                                        87890.72
                                                  Speaking_Level~~Speaking_Level
                                                                        91000.63
                                                    Science_Level~~Science_Level
                                                                       102246.94
                                Critical_Thinking_Level~~Critical_Thinking_Level
                                                                       102573.44
                                    Active_Learning_Level~~Active_Learning_Level
                                                                       101184.78
                            Learning_Strategies_Level~~Learning_Strategies_Level
                                                                       102170.82
                                            Instructing_Level~~Instructing_Level
                                                                       107529.32
                    Complex_Problem_Solving_Level~~Complex_Problem_Solving_Level
                                                                        87172.99
          Judgment_and_Decision_Making_Level~~Judgment_and_Decision_Making_Level
                                                                        92828.34
                                  Systems_Analysis_Level~~Systems_Analysis_Level
                                                                        95979.56
                              Systems_Evaluation_Level~~Systems_Evaluation_Level
                                                                        93442.81
                                          Installation_Level~~Installation_Level
                                                                       105551.66
                        Operations_Monitoring_Level~~Operations_Monitoring_Level
                                                                        95514.42
                        Operation_and_Control_Level~~Operation_and_Control_Level
                                                                        97300.32
                        Equipment_Maintenance_Level~~Equipment_Maintenance_Level
                                                                        77584.28
                                    Troubleshooting_Level~~Troubleshooting_Level
                                                                        86821.79
                                                Repairing_Level~~Repairing_Level
                                                                        79641.80
                  Quality_Control_Analysis_Level~~Quality_Control_Analysis_Level
                                                                        98940.83
                            Equipment_Selection_Level~~Equipment_Selection_Level
                                                                        93438.75
Management_of_Financial_Resources_Level~~Management_of_Financial_Resources_Level
                                                                        77622.45
  Management_of_Material_Resources_Level~~Management_of_Material_Resources_Level
                                                                        79745.57
Management_of_Personnel_Resources_Level~~Management_of_Personnel_Resources_Level
                                                                        99627.89
                        Social_Perceptiveness_Level~~Social_Perceptiveness_Level
                                                                        90864.66
                                          Coordination_Level~~Coordination_Level
                                                                       100587.27
                                              Persuasion_Level~~Persuasion_Level
                                                                        81897.23
                                            Negotiation_Level~~Negotiation_Level
                                                                        82975.83
                            Service_Orientation_Level~~Service_Orientation_Level
                                                                        99746.42
                                    Time_Management_Level~~Time_Management_Level
                                                                        91963.45
                                                            Cognitive~~Technical
                                                                        38504.83
                                                           Cognitive~~Management
                                                                        29945.64
                                                               Cognitive~~Social
                                                                        20375.59
                                                           Technical~~Management
                                                                        42620.76
                                                               Technical~~Social
                                                                        41600.93
                                                              Management~~Social
                                                                        36347.86

### Credible Intervals

In [55]:
parameterEstimates(
  fit_bayes,
  standardized = TRUE,
  ci = TRUE
)

   lhs                                     op
1  Cognitive                               =~
2  Cognitive                               =~
3  Cognitive                               =~
4  Cognitive                               =~
5  Cognitive                               =~
6  Cognitive                               =~
7  Cognitive                               =~
8  Cognitive                               =~
9  Cognitive                               =~
10 Cognitive                               =~
11 Cognitive                               =~
12 Cognitive                               =~
13 Cognitive                               =~
14 Technical                               =~
15 Technical                               =~
16 Technical                               =~
17 Technical                               =~
18 Technical                               =~
19 Technical                               =~
20 Technical                               =~
21 Technical                               =~
22 Management                              =~
23 Management                              =~
24 Management                              =~
25 Social                                  =~
26 Social                                  =~
27 Social                                  =~
28 Social                                  =~
29 Social                                  =~
30 Social                                  =~
⋮  ⋮                                       ⋮
41 Judgment_and_Decision_Making_Level      ~~
42 Systems_Analysis_Level                  ~~
43 Systems_Evaluation_Level                ~~
44 Installation_Level                      ~~
45 Operations_Monitoring_Level             ~~
46 Operation_and_Control_Level             ~~
47 Equipment_Maintenance_Level             ~~
48 Troubleshooting_Level                   ~~
49 Repairing_Level                         ~~
50 Quality_Control_Analysis_Level          ~~
51 Equipment_Selection_Level               ~~
52 Management_of_Financial_Resources_Level ~~
53 Management_of_Material_Resources_Level  ~~
54 Management_of_Personnel_Resources_Level ~~
55 Social_Perceptiveness_Level             ~~
56 Coordination_Level                      ~~
57 Persuasion_Level                        ~~
58 Negotiation_Level                       ~~
59 Service_Orientation_Level               ~~
60 Time_Management_Level                   ~~
61 Cognitive                               ~~
62 Technical                               ~~
63 Management                              ~~
64 Social                                  ~~
65 Cognitive                               ~~
66 Cognitive                               ~~
67 Cognitive                               ~~
68 Technical                               ~~
69 Technical                               ~~
70 Management                              ~~
   rhs                                     est         std.lv      std.all
1  Reading_Comprehension_Level             0.6576965   0.6576965   0.9495732
2  Active_Listening_Level                  0.4912878   0.4912878   0.9214816
3  Writing_Level                           0.6732087   0.6732087   0.9424837
4  Speaking_Level                          0.5675251   0.5675251   0.9335824
5  Science_Level                           0.7208780   0.7208780   0.6685714
6  Critical_Thinking_Level                 0.4933855   0.4933855   0.9512270
7  Active_Learning_Level                   0.6111803   0.6111803   0.9611643
8  Learning_Strategies_Level               0.5783717   0.5783717   0.8666009
9  Instructing_Level                       0.5352943   0.5352943   0.8418939
10 Complex_Problem_Solving_Level           0.4877958   0.4877958   0.9244470
11 Judgment_and_Decision_Making_Level      0.4928868   0.4928868   0.9365502
12 Systems_Analysis_Level                  0.5809930   0.5809930   0.8852363
13 Systems_Evaluation_Level                0.6130386   0.6130386   0.8954570
14 Installation_Level                      0.3960249   0.3960249   0.6586365
15 Operations_Monitoring_Level             0.6476604   0.6476604   0.7869821
16 Operation_and_Control_Level             0.8096162   0.8096162   0.8075856
17 Equipment_Maintenance_Level             1.0001658   1.0001658   0.9886770
18 Troubleshooting_Level                   0.8461333   0.8461333   0.9117192
19 Repairing_Level                         1.0078592   1.0078592   0.9853330
20 Quality_Control_Analysis_Level          0.5908641   0.5908641   0.7432699
21 Equipment_Selection_Level               0.7687024   0.7687024   0.9297926
22 Management_of_Financial_Resources_Level 0.6652427   0.6652427   0.9398551
23 Management_of_Material_Resources_Level  0.6024929   0.6024929   0.9361749
24 Management_of_Personnel_Resources_Level 0.4189564   0.4189564   0.7511512
25 Social_Perceptiveness_Level             0.4687465   0.4687465   0.8751480
26 Coordination_Level                      0.3164770   0.3164770   0.7727441
27 Persuasion_Level                        0.5425378   0.5425378   0.9542102
28 Negotiation_Level                       0.5214494   0.5214494   0.9378067
29 Service_Orientation_Level               0.4239063   0.4239063   0.8198516
30 Time_Management_Level                   0.3362880   0.3362880   0.8191597
⋮  ⋮                                       ⋮           ⋮           ⋮
41 Judgment_and_Decision_Making_Level       0.03403230  0.03403230  0.12287372
42 Systems_Analysis_Level                   0.09319524  0.09319524  0.21635673
43 Systems_Evaluation_Level                 0.09287417  0.09287417  0.19815674
44 Installation_Level                       0.20470182  0.20470182  0.56619797
45 Operations_Monitoring_Level              0.25781102  0.25781102  0.38065925
46 Operation_and_Control_Level              0.34955687  0.34955687  0.34780557
47 Equipment_Maintenance_Level              0.02304416  0.02304416  0.02251779
48 Troubleshooting_Level                    0.14536020  0.14536020  0.16876802
49 Repairing_Level                          0.03046550  0.03046550  0.02911888
50 Quality_Control_Analysis_Level           0.28282871  0.28282871  0.44754980
51 Equipment_Selection_Level                0.09260578  0.09260578  0.13548578
52 Management_of_Financial_Resources_Level  0.05845293  0.05845293  0.11667233
53 Management_of_Material_Resources_Level   0.05118304  0.05118304  0.12357660
54 Management_of_Personnel_Resources_Level  0.13556326  0.13556326  0.43577185
55 Social_Perceptiveness_Level              0.06716517  0.06716517  0.23411599
56 Coordination_Level                       0.06757314  0.06757314  0.40286655
57 Persuasion_Level                         0.02892758  0.02892758  0.08948293
58 Negotiation_Level                        0.03726077  0.03726077  0.12051862
59 Service_Orientation_Level                0.08764674  0.08764674  0.32784340
60 Time_Management_Level                    0.05544361  0.05544361  0.32897735
61 Cognitive                                1.00000000  1.00000000  1.00000000
62 Technical                                1.00000000  1.00000000  1.00000000
63 Management                               1.00000000  1.00000000  1.00000000
64 Social                                   1.00000000  1.00000000  1.00000000
65 Technical                               -0.40340652 -0.40340652 -0.40340652
66 Management                               0.56984920  0.56984920  0.56984920
67 Social                                   0.84137445  0.84137445  0.84137445
68 Management                              -0.12631503 -0.12631503 -0.12631503
69 Social                                  -0.50741759 -0.50741759 -0.50741759
70 Social                                   0.64854073  0.64854073  0.64854073

### Posterior Predictive P-value (PPP)

In [ ]:
fitMeasures(fit_bayes)

### Método ESEM

In [62]:
model_esem <- '

efa("block1")*F1 +
efa("block1")*F2 +
efa("block1")*F3 +
efa("block1")*F4 =~

Reading_Comprehension_Level +
Active_Listening_Level +
Writing_Level +
Speaking_Level +
Science_Level +
Critical_Thinking_Level +
Active_Learning_Level +
Learning_Strategies_Level +
Instructing_Level +
Complex_Problem_Solving_Level +
Judgment_and_Decision_Making_Level +
Systems_Analysis_Level +
Systems_Evaluation_Level +
Installation_Level +
Operations_Monitoring_Level +
Operation_and_Control_Level +
Equipment_Maintenance_Level +
Troubleshooting_Level +
Repairing_Level +
Quality_Control_Analysis_Level +
Equipment_Selection_Level +
Management_of_Financial_Resources_Level +
Management_of_Material_Resources_Level +
Management_of_Personnel_Resources_Level +
Social_Perceptiveness_Level +
Coordination_Level +
Persuasion_Level +
Negotiation_Level +
Service_Orientation_Level +
Time_Management_Level

'

In [63]:
fit_esem <- sem(
  model_esem,
  data = efa_global,
  estimator = "MLR",
  rotation = "geomin",
  std.lv = TRUE
)

In [64]:
summary(
  fit_esem,
  standardized = TRUE,
  fit.measures = TRUE
)

lavaan 0.6-21 ended normally after 11 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                       156
  Row rank of the constraints matrix                12

  Rotation method                       GEOMIN OBLIQUE
  Geomin epsilon                                 0.001
  Rotation algorithm (rstarts)                GPA (30)
  Standardized metric                             TRUE
  Row weights                                     None

  Number of observations                          3050

Model Test User Model:
                                               Standard      Scaled
  Test Statistic                              19606.210   19132.867
  Degrees of freedom                                321         321
  P-value (Chi-square)                            0.000       0.000
  Scaling correction factor                                   1.025
    Yuan-Bentler correction (Mplus variant)

Model Test Baseline Model:

  Test statistic                            155969.003  139091.859
  Degrees of freedom                               435         435
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.121

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.876       0.864
  Tucker-Lewis Index (TLI)                       0.832       0.816

  Robust Comparative Fit Index (CFI)                         0.876
  Robust Tucker-Lewis Index (TLI)                            0.832

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -23172.437  -23172.437
  Scaling correction factor                                  1.295
      for the MLR correction
  Loglikelihood unrestricted model (H1)     -13369.333  -13369.333
  Scaling correction factor                                  1.108
      for the MLR correction

  Akaike (AIC)                               46632.875   46632.875
  Bayesian (BIC)                             47500.172   47500.172
  Sample-size adjusted Bayesian (SABIC)      47042.627   47042.627

Root Mean Square Error of Approximation:

  RMSEA                                          0.140       0.139
  90 Percent confidence interval - lower         0.139       0.137
  90 Percent confidence interval - upper         0.142       0.140
  P-value H_0: RMSEA <= 0.050                    0.000       0.000
  P-value H_0: RMSEA >= 0.080                    1.000       1.000

  Robust RMSEA                                               0.140
  90 Percent confidence interval - lower                     0.139
  90 Percent confidence interval - upper                     0.142
  P-value H_0: Robust RMSEA <= 0.050                         0.000
  P-value H_0: Robust RMSEA >= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.028       0.028

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  F1 =~ block1
    Rdng_Cmprhns_L    0.780    0.013   60.171    0.000    0.780    1.129
    Actv_Lstnng_Lv    0.450    0.009   47.414    0.000    0.450    0.847
    Writing_Level     0.722    0.016   45.591    0.000    0.722    1.013
    Speaking_Level    0.524    0.012   44.209    0.000    0.524    0.864
    Science_Level     1.325    0.032   41.145    0.000    1.325    1.231
    Crtcl_Thnkng_L    0.483    0.013   37.793    0.000    0.483    0.933
    Actv_Lrnng_Lvl    0.625    0.017   36.195    0.000    0.625    0.986
    Lrnng_Strtgs_L    0.521    0.021   24.249    0.000    0.521    0.783
    Instructng_Lvl    0.472    0.020   23.466    0.000    0.472    0.743
    Cmplx_Prbl_S_L    0.495    0.016   30.384    0.000    0.495    0.940
    Jdgmnt_n_D_M_L    0.445    0.015   29.559    0.000    0.445    0.848
    Systms_Anlys_L    0.508    0.020   24.852    0.000    0.508    0.775
    Systms_Evltn_L    0.502    0.021   23.711    0.000    0.502    0.734
    Installatn_Lvl    0.015    0.015    1.012    0.312    0.015    0.025
    Oprtns_Mntrn_L    0.012    0.021    0.588    0.557    0.012    0.015
    Oprtn_nd_Cnt_L   -0.149    0.027   -5.580    0.000   -0.149   -0.149
    Eqpmnt_Mntnn_L   -0.059    0.020   -3.041    0.002   -0.059   -0.059
    Troblshtng_Lvl   -0.019    0.014   -1.374    0.169   -0.019   -0.020
    Repairing_Levl   -0.067    0.022   -3.011    0.003   -0.067   -0.065
    Qlty_Cntrl_A_L    0.116    0.018    6.599    0.000    0.116    0.146
    Eqpmnt_Slctn_L    0.013    0.006    2.054    0.040    0.013    0.015
    Mngmnt_f_F_R_L   -0.057    0.024   -2.385    0.017   -0.057   -0.080
    Mngmnt_f_M_R_L   -0.003    0.019   -0.162    0.872   -0.003   -0.005
    Mngmnt_f_P_R_L    0.104    0.016    6.433    0.000    0.104    0.187
    Scl_Prcptvns_L    0.152    0.010   15.833    0.000    0.152    0.284
    Coordinatn_Lvl    0.005    0.010    0.536    0.592    0.005    0.013
    Persuasion_Lvl    0.059    0.012    4.740    0.000    0.059    0.104
    Negotiatin_Lvl   -0.001    0.011   -0.088    0.930   -0.001   -0.002
    Srvc_Ornttn_Lv    0.006    0.007    0.804    0.421    0.006    0.011
    Tim_Mngmnt_Lvl    0.174    0.012   14.959    0.000    0.174    0.426
  F2 =~ block1
    Rdng_Cmprhns_L   -0.012    0.037   -0.317    0.752   -0.012   -0.017
    Actv_Lstnng_Lv   -0.116    0.017   -6.772    0.000   -0.116   -0.217
    Writing_Level    -0.101    0.013   -7.574    0.000   -0.101   -0.142
    Speaking_Level   -0.143    0.018   -7.846    0.000   -0.143   -0.235
    Science_Level     0.507    0.180    2.817    0.005    0.507    0.471
    Crtcl_Thnkng_L   -0.025    0.017   -1.466    0.143   -0.025   -0.048
    Actv_Lrnng_Lvl   -0.004    0.012   -0.299    0.765   -0.004   -0.006
    Lrnng_Strtgs_L   -0.042    0.042   -0.997    0.319   -0.042   -0.063
    Instructng_Lvl   -0.025    0.045   -0.564    0.573   -0.025   -0.040
    Cmplx_Prbl_S_L    0.043    0.023    1.882    0.060    0.043    0.081
    Jdgmnt_n_D_M_L    0.002    0.035    0.065    0.948    0.002    0.004
    Systms_Anlys_L    0.055    0.064    0.847    0.397    0.055    0.083
    Systms_Evltn_L    0.041    0.081    0.503    0.615    0.041    0.060
    Installatn_Lvl   -0.042    0.010   -4.218    0.000   -0.042   -0.069
    Oprtns_Mntrn_L    0.627    0.036   17.205    0.000    0.627    0.763
    Oprtn_nd_Cnt_L    0.619    0.048   12.883    0.000    0.619    0.619
    Eqpmnt_Mntnn_L    0.070    0.026    2.645    0.008    0.070    0.069
    Troblshtng_Lvl    0.462    0.034   13.800    0.000    0.462    0.499
    Repairing_Levl    0.001    0.008    0.070    0.944    0.001    0.001
    Qlty_Cntrl_A_L    0.598    0.026   22.665    0.000    0.598    0.754
    Eqpmnt_Slctn_L    0.195    0.020    9.551    0.000    0.195    0.237
    Mngmnt_f_F_R_L    0.050    0.194    0.257    0.797    0.050    0.071
    Mngmnt_f_M_R_L    0.134    0.162    0.827    0.408    0.134    0.208
    Mngmnt_f_P_R_L    0.024    0.142    0.171    0.864    0.024    0.043
    Scl_Prcptvns_L   -0.167    0.101   -1.658    0.097   -0.167   -0.313
    Coordinatn_Lvl   -0.011    0.113   -0.101    0.919   -0.011   -0.028
    Persuasion_Lvl   -0.192    0.153   -1.251    0.211   -0.192   -0.338
    Negotiatin_Lvl   -0.205    0.163   -1.260    0.208   -0.205   -0.369
    Srvc_Ornttn_Lv   -0.185    0.120   -1.546    0.122   -0.185   -0.359
    Tim_Mngmnt_Lvl   -0.016    0.078   -0.205    0.838   -0.016   -0.039
  F3 =~ block1
    Rdng_Cmprhns_L   -0.172    0.010  -17.789    0.000   -0.172   -0.248
    Actv_Lstnng_Lv    0.005    0.006    0.842    0.400    0.005    0.009
    Writing_Level    -0.101    0.010   -9.968    0.000   -0.101   -0.141
    Speaking_Level   -0.003    0.005   -0.533    0.594   -0.003   -0.005
    Science_Level    -0.585    0.039  -15.173    0.000   -0.585   -0.543
    Crtcl_Thnkng_L    0.010    0.009    1.191    0.234    0.010    0.020
    Actv_Lrnng_Lvl   -0.018    0.014   -1.285    0.199   -0.018   -0.029
    Lrnng_Strtgs_L    0.070    0.019    3.665    0.000    0.070    0.105
    Instructng_Lvl    0.093    0.018    5.127    0.000    0.093    0.146
    Cmplx_Prbl_S_L    0.029    0.015    1.906    0.057    0.029    0.056
    Jdgmnt_n_D_M_L    0.071    0.014    5.057    0.000    0.071    0.135
    Systms_Anlys_L    0.146    0.020    7.456    0.000    0.146    0.222
    Systms_Evltn_L    0.195    0.019   10.285    0.000    0.195    0.286
    Installatn_Lvl    0.009    0.009    0.969    0.333    0.009    0.015
    Oprtns_Mntrn_L    0.010    0.011    0.961    0.337    0.010    0.013
    Oprtn_nd_Cnt_L    0.008    0.013    0.593    0.553    0.008    0.008
    Eqpmnt_Mntnn_L   -0.029    0.008   -3.706    0.000   -0.029   -0.029
    Troblshtng_Lvl   -0.008    0.008   -1.116    0.264   -0.008   -0.009
    Repairing_Levl    0.013    0.008    1.559    0.119    0.013    0.013
    Qlty_Cntrl_A_L   -0.001    0.013   -0.044    0.965   -0.001   -0.001
    Eqpmnt_Slctn_L   -0.017    0.009   -1.830    0.067   -0.017   -0.021
    Mngmnt_f_F_R_L    0.556    0.029   19.312    0.000    0.556    0.787
    Mngmnt_f_M_R_L    0.473    0.026   18.480    0.000    0.473    0.736
    Mngmnt_f_P_R_L    0.410    0.017   23.424    0.000    0.410    0.735
    Scl_Prcptvns_L    0.272    0.011   24.356    0.000    0.272    0.509
    Coordinatn_Lvl    0.334    0.009   35.277    0.000    0.334    0.816
    Persuasion_Lvl    0.432    0.013   34.504    0.000    0.432    0.761
    Negotiatin_Lvl    0.466    0.014   34.204    0.000    0.466    0.840
    Srvc_Ornttn_Lv    0.338    0.015   22.338    0.000    0.338    0.654
    Tim_Mngmnt_Lvl    0.218    0.011   20.689    0.000    0.218    0.532
  F4 =~ block1
    Rdng_Cmprhns_L   -0.024    0.005   -4.615    0.000   -0.024   -0.035
    Actv_Lstnng_Lv   -0.008    0.005   -1.637    0.102   -0.008   -0.015
    Writing_Level     0.001    0.006    0.122    0.903    0.001    0.001
    Speaking_Level   -0.010    0.006   -1.649    0.099   -0.010   -0.016
    Science_Level    -0.009    0.018   -0.522    0.601   -0.009   -0.009
    Crtcl_Thnkng_L    0.020    0.006    3.688    0.000    0.020    0.040
    Actv_Lrnng_Lvl    0.013    0.007    1.937    0.053    0.013    0.021
    Lrnng_Strtgs_L    0.034    0.009    3.679    0.000    0.034    0.051
    Instructng_Lvl    0.048    0.010    4.670    0.000    0.048    0.075
    Cmplx_Prbl_S_L    0.052    0.008    6.467    0.000    0.052    0.099
    Jdgmnt_n_D_M_L    0.025    0.007    3.442    0.001    0.025    0.048
    Systms_Anlys_L    0.066    0.011    6.073    0.000    0.066    0.100
    Systms_Evltn_L    0.079    0.011    7.010    0.000    0.079    0.116
    Installatn_Lvl    0.440    0.017   25.385    0.000    0.440    0.732
    Oprtns_Mntrn_L    0.209    0.045    4.687    0.000    0.209    0.254
    Oprtn_nd_Cnt_L    0.308    0.049    6.269    0.000    0.308    0.307
    Eqpmnt_Mntnn_L    0.919    0.018   51.929    0.000    0.919    0.911
    Troblshtng_Lvl    0.510    0.035   14.626    0.000    0.510    0.551
    Repairing_Levl    0.995    0.014   70.448    0.000    0.995    0.975
    Qlty_Cntrl_A_L    0.214    0.036    5.953    0.000    0.214    0.270
    Eqpmnt_Slctn_L    0.631    0.019   33.428    0.000    0.631    0.765
    Mngmnt_f_F_R_L   -0.039    0.015   -2.638    0.008   -0.039   -0.056
    Mngmnt_f_M_R_L    0.003    0.016    0.199    0.842    0.003    0.005
    Mngmnt_f_P_R_L   -0.001    0.011   -0.099    0.921   -0.001   -0.002
    Scl_Prcptvns_L   -0.034    0.008   -4.574    0.000   -0.034   -0.065
    Coordinatn_Lvl   -0.017    0.010   -1.741    0.082   -0.017   -0.042
    Persuasion_Lvl   -0.006    0.005   -1.385    0.166   -0.006   -0.011
    Negotiatin_Lvl   -0.003    0.005   -0.692    0.489   -0.003   -0.006
    Srvc_Ornttn_Lv   -0.048    0.009   -5.389    0.000   -0.048   -0.094
    Tim_Mngmnt_Lvl    0.019    0.008    2.544    0.011    0.019    0.047

Covariances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  F1 ~~
    F2               -0.281    0.031   -9.093    0.000   -0.281   -0.281
    F3                0.767    0.085    9.057    0.000    0.767    0.767
    F4               -0.343    0.034  -10.062    0.000   -0.343   -0.343
  F2 ~~
    F3               -0.019    0.302   -0.062    0.951   -0.019   -0.019
    F4                0.645    0.033   19.311    0.000    0.645    0.645
  F3 ~~
    F4               -0.220    0.238   -0.923    0.356   -0.220   -0.220

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
   .Rdng_Cmprhns_L    0.027    0.001   22.620    0.000    0.027    0.057
   .Actv_Lstnng_Lv    0.030    0.001   28.610    0.000    0.030    0.107
   .Writing_Level     0.037    0.001   26.270    0.000    0.037    0.073
   .Speaking_Level    0.028    0.001   29.508    0.000    0.028    0.075
   .Science_Level     0.360    0.011   33.114    0.000    0.360    0.311
   .Crtcl_Thnkng_L    0.027    0.001   31.714    0.000    0.027    0.099
   .Actv_Lrnng_Lvl    0.033    0.001   34.789    0.000    0.033    0.082
   .Lrnng_Strtgs_L    0.110    0.004   30.461    0.000    0.110    0.249
   .Instructng_Lvl    0.114    0.004   26.826    0.000    0.114    0.283
   .Cmplx_Prbl_S_L    0.032    0.001   24.919    0.000    0.032    0.116
   .Jdgmnt_n_D_M_L    0.032    0.001   29.850    0.000    0.032    0.117
   .Systms_Anlys_L    0.067    0.003   26.555    0.000    0.067    0.157
   .Systms_Evltn_L    0.060    0.002   26.128    0.000    0.060    0.129
   .Installatn_Lvl    0.194    0.008   23.882    0.000    0.194    0.539
   .Oprtns_Mntrn_L    0.077    0.006   12.965    0.000    0.077    0.114
   .Oprtn_nd_Cnt_L    0.175    0.010   18.096    0.000    0.175    0.175
   .Eqpmnt_Mntnn_L    0.027    0.002   11.270    0.000    0.027    0.027
   .Troblshtng_Lvl    0.065    0.003   25.554    0.000    0.065    0.076
   .Repairing_Levl    0.008    0.003    3.027    0.002    0.008    0.008
   .Qlty_Cntrl_A_L    0.104    0.005   20.059    0.000    0.104    0.165
   .Eqpmnt_Slctn_L    0.087    0.003   27.521    0.000    0.087    0.128
   .Mngmnt_f_F_R_L    0.225    0.009   25.709    0.000    0.225    0.451
   .Mngmnt_f_M_R_L    0.176    0.007   26.610    0.000    0.176    0.426
   .Mngmnt_f_P_R_L    0.067    0.003   21.784    0.000    0.067    0.217
   .Scl_Prcptvns_L    0.065    0.003   24.353    0.000    0.065    0.228
   .Coordinatn_Lvl    0.050    0.002   28.366    0.000    0.050    0.297
   .Persuasion_Lvl    0.043    0.003   14.827    0.000    0.043    0.135
   .Negotiatin_Lvl    0.045    0.003   13.096    0.000    0.045    0.145
   .Srvc_Ornttn_Lv    0.091    0.003   29.600    0.000    0.091    0.342
   .Tim_Mngmnt_Lvl    0.034    0.001   30.090    0.000    0.034    0.201
    F1                1.000                               1.000    1.000
    F2                1.000                               1.000    1.000
    F3                1.000                               1.000    1.000
    F4                1.000                               1.000    1.000

In [65]:
fitMeasures(
  fit_esem,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     19606.210        321.000          0.000          0.876          0.832
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.140          0.139          0.142          0.028

In [66]:
inspect(
  fit_esem,
  "std"
)$lambda

                                        F1           F2
Reading_Comprehension_Level              1.129271220 -0.0171510509
Active_Listening_Level                   0.846794445 -0.2173368762
Writing_Level                            1.013385308 -0.1418385203
Speaking_Level                           0.864043199 -0.2353741481
Science_Level                            1.230684589  0.4712555711
Critical_Thinking_Level                  0.933461780 -0.0481349855
Active_Learning_Level                    0.985554522 -0.0055729446
Learning_Strategies_Level                0.782750349 -0.0631291375
Instructing_Level                        0.743287741 -0.0400152172
Complex_Problem_Solving_Level            0.940132826  0.0814790773
Judgment_and_Decision_Making_Level       0.847957421  0.0043247187
Systems_Analysis_Level                   0.775451948  0.0833851303
Systems_Evaluation_Level                 0.734407299  0.0598556114
Installation_Level                       0.025045403 -0.0692119639
Operations_Monitoring_Level              0.014898314  0.7626733135
Operation_and_Control_Level             -0.149347982  0.6185906698
Equipment_Maintenance_Level             -0.058769837  0.0693857830
Troubleshooting_Level                   -0.020405602  0.4993146527
Repairing_Level                         -0.065421708  0.0005339123
Quality_Control_Analysis_Level           0.145519413  0.7535844982
Equipment_Selection_Level                0.015357540  0.2366654432
Management_of_Financial_Resources_Level -0.080033699  0.0705541103
Management_of_Material_Resources_Level  -0.004798811  0.2084370390
Management_of_Personnel_Resources_Level  0.187029547  0.0434840819
Social_Perceptiveness_Level              0.283613888 -0.3127457685
Coordination_Level                       0.013247454 -0.0279151093
Persuasion_Level                         0.104416803 -0.3376354224
Negotiation_Level                       -0.001672309 -0.3690527316
Service_Orientation_Level                0.010802825 -0.3588992129
Time_Management_Level                    0.425714304 -0.0390953614
                                        F3            F4
Reading_Comprehension_Level             -0.2484941777 -0.035205879
Active_Listening_Level                   0.0090525476 -0.015015608
Writing_Level                           -0.1411432487  0.001114581
Speaking_Level                          -0.0047094188 -0.015950715
Science_Level                           -0.5432321721 -0.008663131
Critical_Thinking_Level                  0.0195702664  0.039620722
Active_Learning_Level                   -0.0288384457  0.020712780
Learning_Strategies_Level                0.1051087218  0.050924915
Instructing_Level                        0.1460728456  0.075391678
Complex_Problem_Solving_Level            0.0555402884  0.098675349
Judgment_and_Decision_Making_Level       0.1350430714  0.048045234
Systems_Analysis_Level                   0.2223124874  0.100061277
Systems_Evaluation_Level                 0.2861389338  0.115515028
Installation_Level                       0.0149235440  0.732335627
Operations_Monitoring_Level              0.0127150610  0.254270535
Operation_and_Control_Level              0.0080039315  0.307300279
Equipment_Maintenance_Level             -0.0287381778  0.910771659
Troubleshooting_Level                   -0.0090534565  0.550673787
Repairing_Level                          0.0127295464  0.974826130
Quality_Control_Analysis_Level          -0.0007069332  0.269557643
Equipment_Selection_Level               -0.0207044800  0.764861249
Management_of_Financial_Resources_Level  0.7867171359 -0.055591422
Management_of_Material_Resources_Level   0.7355447543  0.004808350
Management_of_Personnel_Resources_Level  0.7351764034 -0.001947819
Social_Perceptiveness_Level              0.5092632257 -0.064536840
Coordination_Level                       0.8161783925 -0.041914916
Persuasion_Level                         0.7610941858 -0.011092525
Negotiation_Level                        0.8395260343 -0.005737408
Service_Orientation_Level                0.6539813259 -0.093717595
Time_Management_Level                    0.5321966174  0.046875055

### Modelo ESEM 3 Fatores

In [67]:
model_esem3 <- '

efa("block1")*F1 +
efa("block1")*F2 +
efa("block1")*F3 =~

Reading_Comprehension_Level +
Active_Listening_Level +
Writing_Level +
Speaking_Level +
Science_Level +
Critical_Thinking_Level +
Active_Learning_Level +
Learning_Strategies_Level +
Instructing_Level +
Complex_Problem_Solving_Level +
Judgment_and_Decision_Making_Level +
Systems_Analysis_Level +
Systems_Evaluation_Level +
Installation_Level +
Operations_Monitoring_Level +
Operation_and_Control_Level +
Equipment_Maintenance_Level +
Troubleshooting_Level +
Repairing_Level +
Quality_Control_Analysis_Level +
Equipment_Selection_Level +
Management_of_Financial_Resources_Level +
Management_of_Material_Resources_Level +
Management_of_Personnel_Resources_Level +
Social_Perceptiveness_Level +
Coordination_Level +
Persuasion_Level +
Negotiation_Level +
Service_Orientation_Level +
Time_Management_Level

'

In [68]:
fit_esem3 <- sem(
  model_esem3,
  data = efa_global,
  estimator = "MLR",
  rotation = "geomin",
  std.lv = TRUE
)

In [69]:
fitMeasures(
  fit_esem3,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     28221.871        348.000          0.000          0.821          0.776
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.162          0.160          0.164          0.034

### Modelos Hierarquico

In [70]:
model_hier <- '

################################################
# PRIMEIRA ORDEM
################################################

Cognitive =~
Reading_Comprehension_Level +
Active_Listening_Level +
Writing_Level +
Speaking_Level +
Science_Level +
Critical_Thinking_Level +
Active_Learning_Level +
Learning_Strategies_Level +
Instructing_Level +
Complex_Problem_Solving_Level +
Judgment_and_Decision_Making_Level +
Systems_Analysis_Level +
Systems_Evaluation_Level

Operations =~
Operations_Monitoring_Level +
Operation_and_Control_Level +
Quality_Control_Analysis_Level +
Troubleshooting_Level

ManagerialSocial =~
Management_of_Financial_Resources_Level +
Management_of_Material_Resources_Level +
Management_of_Personnel_Resources_Level +
Social_Perceptiveness_Level +
Coordination_Level +
Persuasion_Level +
Negotiation_Level +
Service_Orientation_Level +
Time_Management_Level

Technical =~
Installation_Level +
Equipment_Maintenance_Level +
Repairing_Level +
Equipment_Selection_Level

################################################
# SEGUNDA ORDEM
################################################

GeneralSkill =~
Cognitive +
Operations +
ManagerialSocial +
Technical

'

In [71]:
fit_hier <- cfa(
  model_hier,
  data = efa_global,
  estimator = "MLR",
  std.lv = TRUE
)

In [72]:
summary(
  fit_hier,
  fit.measures = TRUE,
  standardized = TRUE
)

lavaan 0.6-21 ended normally after 214 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        64

  Number of observations                          3050

Model Test User Model:
                                               Standard      Scaled
  Test Statistic                              37010.564   34828.941
  Degrees of freedom                                401         401
  P-value (Chi-square)                            0.000       0.000
  Scaling correction factor                                   1.063
    Yuan-Bentler correction (Mplus variant)

Model Test Baseline Model:

  Test statistic                            155969.003  139091.859
  Degrees of freedom                               435         435
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.121

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.765       0.752
  Tucker-Lewis Index (TLI)                       0.745       0.731

  Robust Comparative Fit Index (CFI)                         0.765
  Robust Tucker-Lewis Index (TLI)                            0.745

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -31874.615  -31874.615
  Scaling correction factor                                  1.395
      for the MLR correction
  Loglikelihood unrestricted model (H1)     -13369.333  -13369.333
  Scaling correction factor                                  1.108
      for the MLR correction

  Akaike (AIC)                               63877.229   63877.229
  Bayesian (BIC)                             64262.695   64262.695
  Sample-size adjusted Bayesian (SABIC)      64059.341   64059.341

Root Mean Square Error of Approximation:

  RMSEA                                          0.173       0.168
  90 Percent confidence interval - lower         0.172       0.166
  90 Percent confidence interval - upper         0.175       0.169
  P-value H_0: RMSEA <= 0.050                    0.000       0.000
  P-value H_0: RMSEA >= 0.080                    1.000       1.000

  Robust RMSEA                                               0.173
  90 Percent confidence interval - lower                     0.171
  90 Percent confidence interval - upper                     0.174
  P-value H_0: Robust RMSEA <= 0.050                         0.000
  P-value H_0: Robust RMSEA >= 0.080                         1.000

Standardized Root Mean Square Residual:

  SRMR                                           0.260       0.260

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                      Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  Cognitive =~
    Rdng_Cmprhns_L       0.591    0.008   75.129    0.000    0.658    0.953
    Actv_Lstnng_Lv       0.440    0.006   77.891    0.000    0.490    0.921
    Writing_Level        0.604    0.008   79.226    0.000    0.673    0.945
    Speaking_Level       0.509    0.006   86.604    0.000    0.566    0.934
    Science_Level        0.650    0.018   35.604    0.000    0.724    0.673
    Crtcl_Thnkng_L       0.441    0.007   67.758    0.000    0.492    0.950
    Actv_Lrnng_Lvl       0.547    0.008   70.507    0.000    0.610    0.961
    Lrnng_Strtgs_L       0.518    0.009   56.656    0.000    0.576    0.866
    Instructng_Lvl       0.479    0.009   53.876    0.000    0.533    0.840
    Cmplx_Prbl_S_L       0.436    0.007   58.966    0.000    0.486    0.923
    Jdgmnt_n_D_M_L       0.440    0.007   66.405    0.000    0.490    0.934
    Systms_Anlys_L       0.518    0.009   56.625    0.000    0.577    0.882
    Systms_Evltn_L       0.546    0.010   57.178    0.000    0.608    0.891
  Operations =~
    Oprtns_Mntrn_L       0.319    0.013   23.787    0.000    0.763    0.929
    Oprtn_nd_Cnt_L       0.378    0.015   24.837    0.000    0.905    0.904
    Qlty_Cntrl_A_L       0.291    0.012   24.452    0.000    0.697    0.878
    Troblshtng_Lvl       0.375    0.014   27.727    0.000    0.898    0.969
  ManagerialSocial =~
    Mngmnt_f_F_R_L       0.393    0.015   26.825    0.000    0.455    0.643
    Mngmnt_f_M_R_L       0.325    0.013   24.235    0.000    0.376    0.585
    Mngmnt_f_P_R_L       0.390    0.010   38.312    0.000    0.451    0.810
    Scl_Prcptvns_L       0.399    0.006   66.966    0.000    0.462    0.864
    Coordinatn_Lvl       0.280    0.007   40.392    0.000    0.324    0.794
    Persuasion_Lvl       0.463    0.007   69.551    0.000    0.536    0.945
    Negotiatin_Lvl       0.449    0.007   65.681    0.000    0.519    0.936
    Srvc_Ornttn_Lv       0.361    0.006   56.137    0.000    0.418    0.810
    Tim_Mngmnt_Lvl       0.294    0.006   45.418    0.000    0.340    0.831
  Technical =~
    Installatn_Lvl       0.104    0.009   11.941    0.000    0.397    0.661
    Eqpmnt_Mntnn_L       0.261    0.021   12.706    0.000    1.001    0.991
    Repairing_Levl       0.264    0.021   12.723    0.000    1.010    0.989
    Eqpmnt_Slctn_L       0.199    0.016   12.683    0.000    0.762    0.923
  GeneralSkill =~
    Cognitive            0.490    0.023   21.654    0.000    0.440    0.440
    Operations          -2.174    0.102  -21.270    0.000   -0.908   -0.908
    ManagerialSocl       0.583    0.023   24.956    0.000    0.503    0.503
    Technical           -3.694    0.315  -11.745    0.000   -0.965   -0.965

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
   .Rdng_Cmprhns_L    0.044    0.002   22.785    0.000    0.044    0.092
   .Actv_Lstnng_Lv    0.043    0.002   28.025    0.000    0.043    0.151
   .Writing_Level     0.054    0.003   21.555    0.000    0.054    0.107
   .Speaking_Level    0.047    0.002   29.698    0.000    0.047    0.127
   .Science_Level     0.635    0.015   42.484    0.000    0.635    0.548
   .Crtcl_Thnkng_L    0.026    0.001   32.202    0.000    0.026    0.097
   .Actv_Lrnng_Lvl    0.030    0.001   32.175    0.000    0.030    0.076
   .Lrnng_Strtgs_L    0.111    0.004   29.580    0.000    0.111    0.251
   .Instructng_Lvl    0.118    0.004   26.515    0.000    0.118    0.294
   .Cmplx_Prbl_S_L    0.041    0.001   28.055    0.000    0.041    0.149
   .Jdgmnt_n_D_M_L    0.035    0.001   27.834    0.000    0.035    0.128
   .Systms_Anlys_L    0.096    0.003   31.391    0.000    0.096    0.223
   .Systms_Evltn_L    0.096    0.003   33.853    0.000    0.096    0.206
   .Oprtns_Mntrn_L    0.093    0.005   18.832    0.000    0.093    0.137
   .Oprtn_nd_Cnt_L    0.183    0.010   17.515    0.000    0.183    0.182
   .Qlty_Cntrl_A_L    0.145    0.005   29.536    0.000    0.145    0.230
   .Troblshtng_Lvl    0.052    0.005   10.599    0.000    0.052    0.060
   .Mngmnt_f_F_R_L    0.293    0.009   33.017    0.000    0.293    0.586
   .Mngmnt_f_M_R_L    0.272    0.008   34.981    0.000    0.272    0.658
   .Mngmnt_f_P_R_L    0.107    0.005   21.698    0.000    0.107    0.344
   .Scl_Prcptvns_L    0.073    0.003   24.611    0.000    0.073    0.254
   .Coordinatn_Lvl    0.062    0.002   31.762    0.000    0.062    0.370
   .Persuasion_Lvl    0.034    0.002   16.969    0.000    0.034    0.107
   .Negotiatin_Lvl    0.038    0.002   16.197    0.000    0.038    0.123
   .Srvc_Ornttn_Lv    0.092    0.003   32.963    0.000    0.092    0.345
   .Tim_Mngmnt_Lvl    0.052    0.002   28.426    0.000    0.052    0.309
   .Installatn_Lvl    0.203    0.009   23.543    0.000    0.203    0.564
   .Eqpmnt_Mntnn_L    0.017    0.001   12.320    0.000    0.017    0.017
   .Repairing_Levl    0.022    0.002   14.115    0.000    0.022    0.021
   .Eqpmnt_Slctn_L    0.101    0.004   23.116    0.000    0.101    0.148
   .Cognitive         1.000                               0.806    0.806
   .Operations        1.000                               0.175    0.175
   .ManagerialSocl    1.000                               0.747    0.747
   .Technical         1.000                               0.068    0.068
    GeneralSkill      1.000                               1.000    1.000

In [73]:
fitMeasures(
  fit_hier,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     37010.564        401.000          0.000          0.765          0.745
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.173          0.172          0.175          0.260

### Modelo Bifactor

In [74]:
library(lavaan)

model_bifactor <- '

#################################################
# GENERAL
#################################################

G =~

Reading_Comprehension_Level +
Active_Listening_Level +
Writing_Level +
Speaking_Level +
Science_Level +
Critical_Thinking_Level +
Active_Learning_Level +
Learning_Strategies_Level +
Instructing_Level +
Complex_Problem_Solving_Level +
Judgment_and_Decision_Making_Level +
Systems_Analysis_Level +
Systems_Evaluation_Level +

Installation_Level +
Operations_Monitoring_Level +
Operation_and_Control_Level +
Equipment_Maintenance_Level +
Troubleshooting_Level +
Repairing_Level +
Quality_Control_Analysis_Level +
Equipment_Selection_Level +

Management_of_Financial_Resources_Level +
Management_of_Material_Resources_Level +
Management_of_Personnel_Resources_Level +

Social_Perceptiveness_Level +
Coordination_Level +
Persuasion_Level +
Negotiation_Level +
Service_Orientation_Level +
Time_Management_Level

#################################################
# SPECIFIC FACTORS
#################################################

Cognitive =~
Reading_Comprehension_Level +
Active_Listening_Level +
Writing_Level +
Speaking_Level +
Science_Level +
Critical_Thinking_Level +
Active_Learning_Level +
Learning_Strategies_Level +
Instructing_Level +
Complex_Problem_Solving_Level +
Judgment_and_Decision_Making_Level +
Systems_Analysis_Level +
Systems_Evaluation_Level

Operations =~
Operations_Monitoring_Level +
Operation_and_Control_Level +
Quality_Control_Analysis_Level +
Troubleshooting_Level

Technical =~
Installation_Level +
Equipment_Maintenance_Level +
Repairing_Level +
Equipment_Selection_Level

ManagerialSocial =~
Management_of_Financial_Resources_Level +
Management_of_Material_Resources_Level +
Management_of_Personnel_Resources_Level +
Social_Perceptiveness_Level +
Coordination_Level +
Persuasion_Level +
Negotiation_Level +
Service_Orientation_Level +
Time_Management_Level

#################################################
# ORTHOGONALITY
#################################################

G ~~ 0*Cognitive
G ~~ 0*Operations
G ~~ 0*Technical
G ~~ 0*ManagerialSocial

Cognitive ~~ 0*Operations
Cognitive ~~ 0*Technical
Cognitive ~~ 0*ManagerialSocial

Operations ~~ 0*Technical
Operations ~~ 0*ManagerialSocial

Technical ~~ 0*ManagerialSocial

'

In [76]:
fit_bi <- cfa(
    model_bifactor,
    data = efa_global,
    estimator = "MLR",
    std.lv = TRUE
)

In [77]:
fitMeasures(
  fit_bi,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     27064.815        375.000          0.000          0.828          0.801
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.153          0.151          0.154          0.244

### Modelo SEM 6 Fatores

In [95]:
model_esem6 <- '

efa("block1")*F1 +
efa("block1")*F2 +
efa("block1")*F3 +
efa("block1")*F4 +
efa("block1")*F5 +
efa("block1")*F6 =~

Science_Level +                        
Programming_Level +                      
Mathematical_Reasoning_Level +                   
Reading_Comprehension_Level +                  
Complex_Problem_Solving_Level +                
Operations_Analysis_Level +                      
Technology_Design_Level +          
Critical_Thinking_Level +                
Active_Learning_Level +                      
Writing_Level +                       
Systems_Analysis_Level +                    
Judgment_and_Decision_Making_Level +                 
Systems_Evaluation_Level +                
Speaking_Level +                 
Persuasion_Level +                
Negotiation_Level +                
Social_Perceptiveness_Level +                 
Service_Orientation_Level +                  
Coordination_Level +                 
Time_Management_Level +                
Management_of_Personnel_Resources_Level +    
Active_Listening_Level +                 
Monitoring_Level +               
Repairing_Level +          
Equipment_Maintenance_Level +            
Troubleshooting_Level +          
Equipment_Selection_Level +           
Operations_Monitoring_Level +           
Operation_and_Control_Level +          
Quality_Control_Analysis_Level +           
Installation_Level +           
Management_of_Financial_Resources_Level +   
Management_of_Material_Resources_Level +     
Instructing_Level +
Learning_Strategies_Level 

'

In [98]:
fit_esem6 <- cfa(
    model_esem6,
    data = efa_global,
    estimator = "MLR",
    std.lv = TRUE
)

In [99]:
fitMeasures(
  fit_esem6,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     14573.634        400.000          0.000          0.919          0.879
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.108          0.106          0.109          0.018

In [106]:
loadings <- parameterEstimates(fit_esem6)

loadings %>%
  filter(op == "=~") %>%
  as.data.frame() %>%
  print()

    lhs op                                     rhs    efa           est
1    F1 =~                           Science_Level block1  0.9155832762
2    F1 =~                       Programming_Level block1  0.3082853823
3    F1 =~            Mathematical_Reasoning_Level block1  0.4286083758
4    F1 =~             Reading_Comprehension_Level block1  0.6704738178
5    F1 =~           Complex_Problem_Solving_Level block1  0.4897167564
6    F1 =~               Operations_Analysis_Level block1  0.5266143507
7    F1 =~                 Technology_Design_Level block1  0.2385754840
8    F1 =~                 Critical_Thinking_Level block1  0.5026298278
9    F1 =~                   Active_Learning_Level block1  0.5772118171
10   F1 =~                           Writing_Level block1  0.6512240210
11   F1 =~                  Systems_Analysis_Level block1  0.5293197932
12   F1 =~      Judgment_and_Decision_Making_Level block1  0.4686032452
13   F1 =~                Systems_Evaluation_Level block1  0.5545999613
14   F1 =~                          Speaking_Level block1  0.5398877340
15   F1 =~                        Persuasion_Level block1  0.3378331799
16   F1 =~                       Negotiation_Level block1  0.2973988998
17   F1 =~             Social_Perceptiveness_Level block1  0.3409794346
18   F1 =~               Service_Orientation_Level block1  0.2287126092
19   F1 =~                      Coordination_Level block1  0.1784811318
20   F1 =~                   Time_Management_Level block1  0.2624503070
21   F1 =~ Management_of_Personnel_Resources_Level block1  0.2494042285
22   F1 =~                  Active_Listening_Level block1  0.4939830271
23   F1 =~                        Monitoring_Level block1  0.3557008854
24   F1 =~                         Repairing_Level block1 -0.0005060269
25   F1 =~             Equipment_Maintenance_Level block1 -0.0202263302
26   F1 =~                   Troubleshooting_Level block1 -0.0239948052
27   F1 =~               Equipment_Selection_Level block1 -0.0001992608
28   F1 =~             Operations_Monitoring_Level block1  0.0106883032
29   F1 =~             Operation_and_Control_Level block1 -0.1201320390
30   F1 =~          Quality_Control_Analysis_Level block1  0.0319641505
31   F1 =~                      Installation_Level block1  0.0442466641
32   F1 =~ Management_of_Financial_Resources_Level block1 -0.0100899414
33   F1 =~  Management_of_Material_Resources_Level block1  0.0117903175
34   F1 =~                       Instructing_Level block1  0.4787040121
35   F1 =~               Learning_Strategies_Level block1  0.4891275664
36   F2 =~                           Science_Level block1 -0.4397487385
37   F2 =~                       Programming_Level block1 -0.1144999766
38   F2 =~            Mathematical_Reasoning_Level block1 -0.0773726654
39   F2 =~             Reading_Comprehension_Level block1 -0.1163169300
40   F2 =~           Complex_Problem_Solving_Level block1  0.0060373407
41   F2 =~               Operations_Analysis_Level block1  0.0312834997
42   F2 =~                 Technology_Design_Level block1 -0.0085046386
43   F2 =~                 Critical_Thinking_Level block1  0.0023648105
44   F2 =~                   Active_Learning_Level block1 -0.0293711222
45   F2 =~                           Writing_Level block1 -0.0701826725
46   F2 =~                  Systems_Analysis_Level block1  0.0751288010
47   F2 =~      Judgment_and_Decision_Making_Level block1  0.0405746280
48   F2 =~                Systems_Evaluation_Level block1  0.1065669252
49   F2 =~                          Speaking_Level block1 -0.0041480962
50   F2 =~                        Persuasion_Level block1  0.3064463765
51   F2 =~                       Negotiation_Level block1  0.3348581298
52   F2 =~             Social_Perceptiveness_Level block1  0.1807362770
53   F2 =~               Service_Orientation_Level block1  0.2337347882
54   F2 =~                      Coordination_Level block1  0.2138123062
55   F2 =~                   Time_Management_Level block1  0.1478471733
56   F2 =~ Management_of_Personnel_Resources_Level block1  0.2756321858
57   F2 =~                  Active_Listening_Level block1  0.0061737818
58   F2 =~                        Monitoring_Level block1  0.0699505731
59   F2 =~                         Repairing_Level block1  0.0194969598
60   F2 =~             Equipment_Maintenance_Level block1 -0.0118217012
61   F2 =~                   Troubleshooting_Level block1 -0.0070983483
62   F2 =~               Equipment_Selection_Level block1 -0.0065819256
63   F2 =~             Operations_Monitoring_Level block1 -0.0041903406
64   F2 =~             Operation_and_Control_Level block1  0.0090128937
65   F2 =~          Quality_Control_Analysis_Level block1  0.0005307146
66   F2 =~                      Installation_Level block1 -0.0033367660
67   F2 =~ Management_of_Financial_Resources_Level block1  0.4904259964
68   F2 =~  Management_of_Material_Resources_Level block1  0.4059867589
69   F2 =~                       Instructing_Level block1  0.0074098977
70   F2 =~               Learning_Strategies_Level block1 -0.0071318730
71   F3 =~                           Science_Level block1 -0.1266850424
72   F3 =~                       Programming_Level block1 -0.0119973404
73   F3 =~            Mathematical_Reasoning_Level block1 -0.0572830449
74   F3 =~             Reading_Comprehension_Level block1 -0.0241828922
75   F3 =~           Complex_Problem_Solving_Level block1  0.0112535225
76   F3 =~               Operations_Analysis_Level block1 -0.0635615182
77   F3 =~                 Technology_Design_Level block1  0.0174309971
78   F3 =~                 Critical_Thinking_Level block1  0.0026537865
79   F3 =~                   Active_Learning_Level block1 -0.0012127275
80   F3 =~                           Writing_Level block1  0.0104669517
81   F3 =~                  Systems_Analysis_Level block1  0.0162109295
82   F3 =~      Judgment_and_Decision_Making_Level block1  0.0030947033
83   F3 =~                Systems_Evaluation_Level block1  0.0233121485
84   F3 =~                          Speaking_Level block1  0.0052643955
85   F3 =~                        Persuasion_Level block1  0.0116472746
86   F3 =~                       Negotiation_Level block1  0.0137329836
87   F3 =~             Social_Perceptiveness_Level block1 -0.0160457947
88   F3 =~               Service_Orientation_Level block1 -0.0124057615
89   F3 =~                      Coordination_Level block1 -0.0316277794
90   F3 =~                   Time_Management_Level block1  0.0024142212
91   F3 =~ Management_of_Personnel_Resources_Level block1 -0.0258455323
92   F3 =~                  Active_Listening_Level block1 -0.0009098263
93   F3 =~                        Monitoring_Level block1 -0.0470806776
94   F3 =~                         Repairing_Level block1  0.6019632982
95   F3 =~             Equipment_Maintenance_Level block1  0.5348151307
96   F3 =~                   Troubleshooting_Level block1  0.1935243259
97   F3 =~               Equipment_Selection_Level block1  0.3423384104
98   F3 =~             Operations_Monitoring_Level block1 -0.0676377627
99   F3 =~             Operation_and_Control_Level block1 -0.0057642375
100  F3 =~          Quality_Control_Analysis_Level block1 -0.0040207096
101  F3 =~                      Installation_Level block1  0.2878484396
102  F3 =~ Management_of_Financial_Resources_Level block1  0.0020093138
103  F3 =~  Management_of_Material_Resources_Level block1 -0.0022536015
104  F3 =~                       Instructing_Level block1  0.0052537358
105  F3 =~               Learning_Strategies_Level block1  0.0109039798
106  F4 =~                           Science_Level block1  0.1425371175
107  F4 =~                       Programming_Level block1  0.0026005164
108  F4 =~            Mathematical_Reasoning_Level block1 -0.0244841161
109  F4 =~             Reading_Comprehension_Level block1 -0.1303275834
110  F4 =~           Complex_Problem_Solving_Level block1  0.0298368443
111  F4 =~               Operations_Analysis_Level block1  0.0016033765
112  F4 =~                 Technology_Design_Level block1  0.1676852418
113  F4 =~                 Critical_Thinking_Level block1 -0.0069561934
114  F4 =~                   Active_Learning_Level block1 -0.1049925132
115  F4 =~                           Writing_Level block1 -0.1929219536
116  F4 =~                  Systems_Analysis_Level block1  0.0178550472
117  F4 =~      Judgment_and_Decision_Making_Level block1 -0.0060257497
118  F4 =~                Systems_Evaluation_Level block1  0.0273509005
119  F4 =~                          Speaking_Level block1 -0.1620145356
120  F4 =~                        Persuasion_Level block1 -0.0135678242
121  F4 =~                       Negotiation_Level block1 -0.0045712172
122  F4 =~             Social_Perceptiveness_Level block1 -0.0905912829
123  F4 =~               Service_Orientation_Level block1 -0.0858242985
124  F4 =~                      Coordination_Level block1  0.0325372753
125  F4 =~                   Time_Management_Level block1  0.0001259585
126  F4 =~ Management_of_Personnel_Resources_Level block1  0.0011365153
127  F4 =~                  Active_Listening_Level block1 -0.0792048228
128  F4 =~                        Monitoring_Level block1  0.0069493108
129  F4 =~                         Repairing_Level block1  0.8241358940
130  F4 =~             Equipment_Maintenance_Level block1  0.8228676252
131  F4 =~                   Troubleshooting_Level block1  0.8566187494
132  F4 =~               Equipment_Selection_Level block1  0.6594868788
133  F4 =~             Operations_Monitoring_Level block1  0.8200700413
134  F4 =~             Operation_and_Control_Level block1  0.9480840973
135  F4 =~          Quality_Control_Analysis_Level block1  0.6660391154
136  F4 =~                      Installation_Level block1  0.2989317749
137  F4 =~ Management_of_Financial_Resources_Level block1 -0.0660998069
138  F4 =~  Management_of_Material_Resources_Level block1  0.0083303543
139  F4 =~                       Instructing_Level block1 -0.1481018324
140  F4 =~               Learning_Strategies_Level block1 -0.2245700333
141  F5 =~                           Science_Level block1  0.0205340338
142  F5 =~                       Programming_Level block1  0.1410335110
143  F5 =~            Mathematical_Reasoning_Level block1  0.2927125690
144  F5 =~             Reading_Comprehension_Level block1 -0.0056951105
145  F5 =~           Complex_Problem_Solving_Level block1  0.0512712004
146  F5 =~               Operations_Analysis_Level block1  0.2665499497
147  F5 =~                 Technology_Design_Level block1  0.1348776397
148  F5 =~                 Critical_Thinking_Level block1 -0.0021218752
149  F5 =~                   Active_Learning_Level block1  0.0411108851
150  F5 =~                           Writing_Level block1 -0.0061803018
151  F5 =~                  Systems_Analysis_Level block1  0.1221408832
152  F5 =~      Judgment_and_Decision_Making_Level block1  0.0412227268
153  F5 =~                Systems_Evaluation_Level block1  0.1137578694
154  F5 =~                          Speaking_Level block1 -0.0476096559
155  F5 =~                        Persuasion_Level block1 -0.0032924795
156  F5 =~                       Negotiation_Level block1 -0.0023370130
157  F5 =~             Social_Perceptiveness_Level block1 -0.0859342091
158  F5 =~               Service_Orientation_Level block1 -0.0474684652
159  F5 =~                      Coordination_Level block1  0.0093130072
160  F5 =~                   Time_Management_Level block1  0.0540866643
161  F5 =~ Management_of_Personnel_Resources_Level block1  0.1103552523
162  F5 =~                  Active_Listening_Level block1 -0.0628893740
163  F5 =~                        Monitoring_Level block1 -0.0054530200
164  F5 =~                         Repairing_Level block1 -0.0038697069
165  F5 =~             Equipment_Maintenance_Level block1 -0.0270739177
166  F5 =~                   Troubleshooting_Level block1 -0.0171232018
167  F5 =~               Equipment_Selection_Level block1  0.0560189994
168  F5 =~             Operations_Monitoring_Level block1 -0.0612691774
169  F5 =~             Operation_and_Control_Level block1 -0.1230739153
170  F5 =~          Quality_Control_Analysis_Level block1  0.1038094893
171  F5 =~                      Installation_Level block1  0.0293158165
172  F5 =~ Management_of_Financial_Resources_Level block1  0.5769859282
173  F5 =~  Management_of_Material_Resources_Level block1  0.4824386517
174  F5 =~                       Instructing_Level block1 -0.0534595507
175  F5 =~               Learning_Strategies_Level block1  0.0007568735
176  F6 =~                           Science_Level block1  0.0422110666
177  F6 =~                       Programming_Level block1 -0.0617753934
178  F6 =~            Mathematical_Reasoning_Level block1  0.0010512700
179  F6 =~             Reading_Comprehension_Level block1 -0.0417052128
180  F6 =~           Complex_Problem_Solving_Level block1 -0.0331449694
181  F6 =~               Operations_Analysis_Level block1 -0.0263410580
182  F6 =~                 Technology_Design_Level block1 -0.0317119687
183  F6 =~                 Critical_Thinking_Level block1 -0.0861661993
184  F6 =~                   Active_Learning_Level block1  0.0361252424
185  F6 =~                           Writing_Level block1 -0.0009381392
186  F6 =~                  Systems_Analysis_Level block1  0.0198655218
187  F6 =~      Judgment_and_Decision_Making_Level block1 -0.0372797789
188  F6 =~                Systems_Evaluation_Level block1  0.0306555561
189  F6 =~                          Speaking_Level block1 -0.0215972978
190  F6 =~                        Persuasion_Level block1 -0.1112901410
191  F6 =~                       Negotiation_Level block1 -0.1132013452
192  F6 =~             Social_Perceptiveness_Level block1  0.0038511072
193  F6 =~               Service_Orientation_Level block1 -0.0313302490
194  F6 =~                      Coordination_Level block1  0.0466171308
195  F6 =~                   Time_Management_Level block1  0.0281306822
196  F6 =~ Management_of_Personnel_Resources_Level block1  0.1304397829
197  F6 =~                  Active_Listening_Level block1 -0.0921053560
198  F6 =~                        Monitoring_Level block1  0.0776153651
199  F6 =~                         Repairing_Level block1 -0.0026941645
200  F6 =~             Equipment_Maintenance_Level block1  0.0089489882
201  F6 =~                   Troubleshooting_Level block1  0.0112084631
202  F6 =~               Equipment_Selection_Level block1  0.0136344314
203  F6 =~             Operations_Monitoring_Level block1 -0.0069885740
204  F6 =~             Operation_and_Control_Level block1 -0.0229805764
205  F6 =~          Quality_Control_Analysis_Level block1  0.0297315562
206  F6 =~                      Installation_Level block1 -0.0082115686
207  F6 =~ Management_of_Financial_Resources_Level block1 -0.0041345459
208  F6 =~  Management_of_Material_Resources_Level block1  0.0902351169
209  F6 =~                       Instructing_Level block1  0.2883551078
210  F6 =~               Learning_Strategies_Level block1  0.3091474475
             se            z       pvalue      ci.lower      ci.upper
1   0.026511210  34.53570308 0.000000e+00  0.8636222594  0.9675442930
2   0.014863238  20.74146829 0.000000e+00  0.2791539709  0.3374167937
3   0.020697316  20.70840366 0.000000e+00  0.3880423818  0.4691743699
4   0.010260636  65.34427584 0.000000e+00  0.6503633411  0.6905842945
5   0.007900961  61.98192289 0.000000e+00  0.4742311573  0.5052023554
6   0.016904754  31.15184852 0.000000e+00  0.4934816407  0.5597470606
7   0.011499070  20.74737244 0.000000e+00  0.2160377213  0.2611132466
8   0.007981876  62.97139087 0.000000e+00  0.4869856385  0.5182740171
9   0.008627824  66.90120295 0.000000e+00  0.5603015925  0.5941220418
10  0.009418075  69.14619053 0.000000e+00  0.6327649328  0.6696831092
11  0.009790614  54.06400118 0.000000e+00  0.5101305414  0.5485090449
12  0.007102352  65.97859882 0.000000e+00  0.4546828907  0.4825235997
13  0.010141838  54.68436361 0.000000e+00  0.5347223239  0.5744775987
14  0.008349398  64.66187706 0.000000e+00  0.5235232150  0.5562522530
15  0.016212643  20.83763711 0.000000e+00  0.3060569827  0.3696093771
16  0.017311464  17.17930413 0.000000e+00  0.2634690544  0.3313287451
17  0.015657507  21.77737655 0.000000e+00  0.3102912840  0.3716675852
18  0.016817401  13.59975983 0.000000e+00  0.1957511097  0.2616741087
19  0.012862244  13.87636012 0.000000e+00  0.1532715965  0.2036906671
20  0.007551577  34.75437127 0.000000e+00  0.2476494883  0.2772511258
21  0.012227106  20.39765048 0.000000e+00  0.2254395417  0.2733689153
22  0.009753840  50.64498127 0.000000e+00  0.4748658527  0.5131002016
23  0.007500273  47.42506090 0.000000e+00  0.3410006212  0.3704011496
24  0.003809988  -0.13281588 8.943390e-01 -0.0079734654  0.0069614117
25  0.005092639  -3.97167986 7.136759e-05 -0.0302077184 -0.0102449419
26  0.007004501  -3.42562649 6.133833e-04 -0.0377233754 -0.0102662349
27  0.004500875  -0.04427157 9.646879e-01 -0.0090208128  0.0086222912
28  0.004728354   2.26047002 2.379210e-02  0.0014208990  0.0199557075
29  0.012574172  -9.55387239 0.000000e+00 -0.1447769641 -0.0954871139
30  0.011343598   2.81781415 4.835179e-03  0.0097311073  0.0541971936
31  0.009904086   4.46751599 7.913310e-06  0.0248350116  0.0636583166
32  0.003041437  -3.31749142 9.082971e-04 -0.0160510486 -0.0041288343
33  0.003807044   3.09697455 1.955067e-03  0.0043286489  0.0192519861
34  0.015856872  30.18905705 0.000000e+00  0.4476251141  0.5097829100
35  0.016646312  29.38353997 0.000000e+00  0.4565013949  0.5217537379
36  0.018285733 -24.04873482 0.000000e+00 -0.4755881161 -0.4039093608
37  0.011981112  -9.55670700 0.000000e+00 -0.1379825246 -0.0910174287
38  0.020372047  -3.79798184 1.458790e-04 -0.1173011443 -0.0374441865
39  0.005879250 -19.78431375 0.000000e+00 -0.1278400486 -0.1047938114
40  0.007389888   0.81697329 4.139437e-01 -0.0084465727  0.0205212541
41  0.017240432   1.81454268 6.959422e-02 -0.0025071261  0.0650741255
42  0.005000537  -1.70074515 8.899085e-02 -0.0183055105  0.0012962333
43  0.004342380   0.54458853 5.860365e-01 -0.0061460986  0.0108757196
44  0.006291675  -4.66825183 3.037734e-06 -0.0417025781 -0.0170396663
45  0.006482090 -10.82716797 0.000000e+00 -0.0828873346 -0.0574780104
46  0.011059098   6.79339319 1.095257e-11  0.0534533672  0.0968042348
47  0.007811465   5.19424027 2.055575e-07  0.0252644372  0.0558848188
48  0.010572842  10.07930770 0.000000e+00  0.0858445362  0.1272893142
49  0.003617565  -1.14665424 2.515246e-01 -0.0112383931  0.0029422008
50  0.010503486  29.17568338 0.000000e+00  0.2858599226  0.3270328304
51  0.011098689  30.17096308 0.000000e+00  0.3131050995  0.3566111601
52  0.008395672  21.52731590 0.000000e+00  0.1642810628  0.1971914911
53  0.010923348  21.39772485 0.000000e+00  0.2123254201  0.2551441562
54  0.008040972  26.59035582 0.000000e+00  0.1980522907  0.2295723217
55  0.008132811  18.17909824 0.000000e+00  0.1319071563  0.1637871903
56  0.013304362  20.71742942 0.000000e+00  0.2495561150  0.3017082566
57  0.002998399   2.05902637 3.949171e-02  0.0002970285  0.0120505351
58  0.007509316   9.31517275 0.000000e+00  0.0552325848  0.0846685615
59  0.004860607   4.01121929 6.040597e-05  0.0099703455  0.0290235741
60  0.004736331  -2.49596193 1.256161e-02 -0.0211047389 -0.0025386635
61  0.005997339  -1.18358296 2.365782e-01 -0.0188529168  0.0046562202
62  0.005983851  -1.09994808 2.713547e-01 -0.0183100585  0.0051462072
63  0.004991416  -0.83950944 4.011835e-01 -0.0139733358  0.0055926545
64  0.007486544   1.20387901 2.286363e-01 -0.0056604637  0.0236862510
65  0.008333022   0.06368813 9.492186e-01 -0.0158017087  0.0168631379
66  0.004953852  -0.67356998 5.005847e-01 -0.0130461373  0.0063726054
67  0.034464899  14.22972397 0.000000e+00  0.4228760361  0.5579759568

### Modelo SEM 5 Fatores

In [101]:
model_esem5 <- '

efa("block1")*F1 +
efa("block1")*F2 +
efa("block1")*F3 +
efa("block1")*F4 +
efa("block1")*F5 =~

Science_Level +                        
Programming_Level +                      
Mathematical_Reasoning_Level +                   
Reading_Comprehension_Level +                  
Complex_Problem_Solving_Level +                
Operations_Analysis_Level +                      
Technology_Design_Level +          
Critical_Thinking_Level +                
Active_Learning_Level +                      
Writing_Level +                       
Systems_Analysis_Level +                    
Judgment_and_Decision_Making_Level +                 
Systems_Evaluation_Level +                
Speaking_Level +                 
Persuasion_Level +                
Negotiation_Level +                
Social_Perceptiveness_Level +                 
Service_Orientation_Level +                  
Coordination_Level +                 
Time_Management_Level +                
Management_of_Personnel_Resources_Level +    
Active_Listening_Level +                 
Monitoring_Level +               
Repairing_Level +          
Equipment_Maintenance_Level +            
Troubleshooting_Level +          
Equipment_Selection_Level +           
Operations_Monitoring_Level +           
Operation_and_Control_Level +          
Quality_Control_Analysis_Level +           
Installation_Level +           
Management_of_Financial_Resources_Level +   
Management_of_Material_Resources_Level +     
Instructing_Level +
Learning_Strategies_Level 

'

In [102]:
fit_esem5 <- cfa(
    model_esem5,
    data = efa_global,
    estimator = "MLR",
    std.lv = TRUE
)

In [103]:
fitMeasures(
  fit_esem5,
  c("chisq","df","pvalue","cfi","tli","rmsea","rmsea.ci.lower","rmsea.ci.upper","srmr")
)

         chisq             df         pvalue            cfi            tli
     19381.933        430.000          0.000          0.891          0.850
         rmsea rmsea.ci.lower rmsea.ci.upper           srmr
         0.120          0.119          0.122          0.022

### Modelo ESEM Completo Residuos

In [93]:
resid(fit_esem, type = "cor")

$type
[1] "cor.bollen"

$cov
                                        Rd_C_L Actv_Ls_L Wrtn_L Spkn_L Scnc_L
Reading_Comprehension_Level              0.000
Active_Listening_Level                   0.017     0.000
Writing_Level                            0.017    -0.001  0.000
Speaking_Level                           0.008     0.027  0.009  0.000
Science_Level                           -0.001    -0.011 -0.007 -0.007  0.000
Critical_Thinking_Level                  0.002     0.022 -0.012  0.006 -0.009
Active_Learning_Level                   -0.008    -0.016 -0.004 -0.009  0.012
Learning_Strategies_Level               -0.015    -0.040  0.008  0.006  0.001
Instructing_Level                       -0.012    -0.035  0.012  0.018  0.012
Complex_Problem_Solving_Level           -0.010    -0.012 -0.012 -0.019  0.015
Judgment_and_Decision_Making_Level      -0.016    -0.006 -0.017 -0.015  0.005
Systems_Analysis_Level                  -0.008    -0.022 -0.010 -0.027  0.006
Systems_Evaluation_Level                -0.015    -0.022 -0.011 -0.021  0.004
Installation_Level                      -0.003    -0.020 -0.008 -0.016 -0.021
Operations_Monitoring_Level              0.006     0.026  0.002  0.013 -0.003
Operation_and_Control_Level              0.004     0.028  0.000  0.020 -0.015
Equipment_Maintenance_Level              0.001     0.002  0.001  0.002  0.000
Troubleshooting_Level                    0.003     0.011  0.000  0.010  0.006
Repairing_Level                          0.000    -0.001  0.000 -0.001  0.000
Quality_Control_Analysis_Level           0.014    -0.003  0.009  0.001 -0.009
Equipment_Selection_Level               -0.001     0.000 -0.007 -0.002  0.017
Management_of_Financial_Resources_Level  0.014    -0.030  0.008 -0.018 -0.011
Management_of_Material_Resources_Level   0.010    -0.034  0.012 -0.007  0.010
Management_of_Personnel_Resources_Level -0.002    -0.020  0.016  0.002  0.005
Social_Perceptiveness_Level              0.004     0.038 -0.008  0.023  0.038
Coordination_Level                      -0.008     0.000 -0.012  0.001 -0.001
Persuasion_Level                         0.004     0.012 -0.001  0.009  0.001
Negotiation_Level                        0.007     0.026  0.009  0.008 -0.019
Service_Orientation_Level                0.007     0.035 -0.012  0.013  0.041
Time_Management_Level                    0.004    -0.008  0.020 -0.001 -0.042
                                        Cr_T_L Actv_Lr_L Lr_S_L Instr_L C_P_S_
Reading_Comprehension_Level
Active_Listening_Level
Writing_Level
Speaking_Level
Science_Level
Critical_Thinking_Level                  0.000
Active_Learning_Level                    0.002     0.000
Learning_Strategies_Level               -0.045     0.037  0.000
Instructing_Level                       -0.043     0.022  0.183   0.000
Complex_Problem_Solving_Level            0.014     0.010 -0.022  -0.026  0.000
Judgment_and_Decision_Making_Level       0.019     0.018 -0.026  -0.026  0.043
Systems_Analysis_Level                  -0.003    -0.002  0.013  -0.008  0.025
Systems_Evaluation_Level                -0.003     0.004  0.023   0.000  0.022
Installation_Level                       0.010     0.002  0.003  -0.008  0.017
Operations_Monitoring_Level              0.006    -0.012 -0.015  -0.001 -0.011
Operation_and_Control_Level              0.008    -0.009 -0.020  -0.002 -0.011
Equipment_Maintenance_Level             -0.002    -0.002  0.002   0.004 -0.003
Troubleshooting_Level                    0.004    -0.004 -0.003   0.004 -0.009
Repairing_Level                          0.000     0.000  0.000  -0.001  0.001
Quality_Control_Analysis_Level           0.007    -0.004 -0.007  -0.017 -0.014
Equipment_Selection_Level               -0.002     0.014  0.000  -0.002  0.006
Management_of_Financial_Resources_Level -0.006     0.011 -0.044  -0.085  0.007
Management_of_Material_Resources_Level  -0.022     0.018  0.009  -0.028 -0.004
Management_of_Personnel_Resources_Level -0.027    -0.010  0.062   0.084 -0.011
Social_Perceptiveness_Level             -0.014    -0.006  0.033   0.021 -0.027
Coordination_Level                      -0.005     0.002  0.030   0.055  0.004
Persuasion_Level                         0.018    -0.002 -0.040  -0.033  0.005
Negotiation_Level                        0.016    -0.010 -0.048  -0.028 -0.010
Service_Orientation_Level                0.007    -0.004  0.017   0.013 -0.024
Time_Management_Level                   -0.014    -0.003  0.009   0.013 -0.001
                                        J__D_M Sy_A_L Sy_E_L Instl_L Op_M_L
Reading_Comprehension_Level
Active_Listening_Level
Writing_Level
Speaking_Level
Science_Level
Critical_Thinking_Level
Active_Learning_Level
Learning_Strategies_Level
Instructing_Level
Complex_Problem_Solving_Level
Judgment_and_Decision_Making_Level       0.000
Systems_Analysis_Level                   0.013  0.000
Systems_Evaluation_Level                 0.020  0.098  0.000
Installation_Level                      -0.002  0.037  0.025   0.000
Operations_Monitoring_Level             -0.010 -0.014 -0.013  -0.043  0.000
Operation_and_Control_Level              0.000 -0.028 -0.029  -0.048  0.067
Equipment_Maintenance_Level             -0.002 -0.002 -0.002  -0.017  0.004
Troubleshooting_Level                   -0.012 -0.015 -0.013   0.037  0.013
Repairing_Level                          0.001  0.001  0.001   0.003 -0.001
Quality_Control_Analysis_Level          -0.015 -0.014 -0.007   0.025 -0.003
Equipment_Selection_Level                0.001 -0.014 -0.011  -0.001 -0.015
Management_of_Financial_Resources_Level  0.013  0.029  0.018  -0.002 -0.049
Management_of_Material_Resources_Level  -0.012  0.017  0.006  -0.012 -0.048
Management_of_Personnel_Resources_Level -0.015 -0.001  0.000  -0.029 -0.007
Social_Perceptiveness_Level             -0.016 -0.034 -0.025  -0.015  0.023
Coordination_Level                       0.004 -0.014 -0.010   0.010  0.003
Persuasion_Level                         0.001 -0.017 -0.012   0.002  0.013
Negotiation_Level                       -0.004 -0.017 -0.017  -0.018  0.026
Service_Orientation_Level               -0.043 -0.026 -0.018   0.018  0.014
Time_Management_Level                    0.008 -0.005 -0.009   0.002 -0.008
                                        O__C_L Eq_M_L Trbl_L Rprn_L Q_C_A_
Reading_Comprehension_Level
Active_Listening_Level
Writing_Level
Speaking_Level
Science_Level
Critical_Thinking_Level
Active_Learning_Level
Learning_Strategies_Level
Instructing_Level
Complex_Problem_Solving_Level
Judgment_and_Decision_Making_Level
Systems_Analysis_Level
Systems_Evaluation_Level
Installation_Level
Operations_Monitoring_Level
Operation_and_Control_Level              0.000
Equipment_Maintenance_Level              0.011  0.000
Troubleshooting_Level                    0.002  0.000  0.000
Repairing_Level                         -0.002  0.000  0.000  0.000
Quality_Control_Analysis_Level          -0.028 -0.010  0.027  0.001  0.000
Equipment_Selection_Level               -0.007  0.002 -0.001  0.000  0.019
Management_of_Financial_Resources_Level -0.055 -0.004 -0.028  0.003  0.018
Management_of_Material_Resources_Level  -0.047 -0.005 -0.019  0.002  0.022
Management_of_Personnel_Resources_Level -0.011  0.004 -0.013  0.001 -0.005
Social_Perceptiveness_Level              0.025  0.005  0.014 -0.002 -0.009
Coordination_Level                       0.011  0.003 -0.007 -0.001 -0.005
Persuasion_Level                         0.016 -0.001  0.017 -0.001  0.010
Negotiation_Level                        0.025 -0.001  0.012  0.000  0.003
Service_Orientation_Level                0.008  0.000  0.035 -0.002  0.010
Time_Management_Level                   -0.002  0.003 -0.011  0.000  0.006
                                        Eq_S_L M__F_R M__M_R M__P_R Sc_P_L
Reading_Comprehension_Level
Active_Listening_Level
Writing_Level
Speaking_Level
Science_Level
Critical_Thinking_Level
Active_Learning_Level
Learning_Strategies_Level
Instructing_Level
Complex_Problem_Solving_Level
Judgment_and_Decision_Making_Level
Systems_Analysis_Level
Systems_Evaluation_Level
Installation_Level
Operations_Monitoring_Level
Operation_and_Control_Level
Equipment_Maintenance_Level
Troubleshooting_Level
Repairing_Level
Quality_Control_Analysis_Level
Equipment_Selection_Level                0.000
Management_of_Financial_Resources_Level  0.015  0.000
Management_of_Material_Resources_Level   0.031  0.343  0.000
Management_of_Personnel_Resources_Level -0.007  0.038  0.046  0.000
Social_Perceptiveness_Level              0.003 -0.085 -0.059  0.009  0.000
Coordination_Level                       0.000 -0.063 -0.037  0.044  0.051
Persuasion_Level                         0.007 -0.027 -0.041 -0.042  0.009
Negotiation_Level                       -0.006 -0.021 -0.036 -0.025 -0.006
Service_Orientation_Level                0.009 -0.056 -0.029 -0.039  0.125
Time_Management_Level                   -0.007  0.019  0.023  0.060  0.004
                                        Crdn_L Prss_L Ngtt_L Sr_O_L Tm_M_L
Reading_Comprehension_Level
Active_Listening_Level
Writing_Level
Speaking_Level
Science_Level
Critical_Thinking_Level
Active_Learning_Level
Learning_Strategies_Level
Instructing_Level
Complex_Problem_Solving_Level
Judgment_and_Decision_Making_Level
Systems_Analysis_Level
Systems_Evaluation_Level
Installation_Level
Operations_Monitoring_Level
Operation_and_Control_Level
Equipment_Maintenance_Level
Troubleshooting_Level
Repairing_Level
Quality_Control_Analysis_Level
Equipment_Selection_Level
Management_of_Financial_Resources_Level
Management_of_Material_Resources_Level
Management_of_Personnel_Resources_Level
Social_Perceptiveness_Level
Coordination_Level                       0.000
Persuasion_Level                        -0.016  0.000
Negotiation_Level                       -0.027  0.069  0.000
Service_Orientation_Level                0.000  0.039  0.018  0.000
Time_Management_Level                    0.033 -0.037 -0.015 -0.045  0.000

### Identificar Fatores

In [109]:
cargas <- parameterEstimates(fit_esem6, standardized = TRUE)

names(cargas)

 [1] "lhs"      "op"       "rhs"      "efa"      "est"      "se"
 [7] "z"        "pvalue"   "ci.lower" "ci.upper" "std.lv"   "std.all"

In [110]:
argas <- parameterEstimates(fit_esem6, standardized = TRUE)

cargas_fatores <- cargas %>%
  filter(op == "=~") %>%
  select(Fator = lhs,
         Variavel = rhs,
         Carga = std.all)

head(cargas_fatores)

  Fator Variavel                      Carga
1 F1    Science_Level                 0.8504900
2 F1    Programming_Level             0.6187006
3 F1    Mathematical_Reasoning_Level  0.5982104
4 F1    Reading_Comprehension_Level   0.9706158
5 F1    Complex_Problem_Solving_Level 0.9304523
6 F1    Operations_Analysis_Level     0.6123778

In [111]:
cargas_fatores %>%
  filter(abs(Carga) >= .30) %>%
  arrange(Fator, desc(abs(Carga)))

   Fator Variavel                                Carga
1  F1    Critical_Thinking_Level                  0.9716527
2  F1    Reading_Comprehension_Level              0.9706158
3  F1    Complex_Problem_Solving_Level            0.9304523
4  F1    Active_Listening_Level                   0.9289107
5  F1    Writing_Level                            0.9141151
6  F1    Active_Learning_Level                    0.9102025
7  F1    Judgment_and_Decision_Making_Level       0.8927170
8  F1    Speaking_Level                           0.8904334
9  F1    Science_Level                            0.8504900
10 F1    Systems_Evaluation_Level                 0.8120655
11 F1    Systems_Analysis_Level                   0.8084444
12 F1    Monitoring_Level                         0.7746937
13 F1    Instructing_Level                        0.7545420
14 F1    Learning_Strategies_Level                0.7346012
15 F1    Time_Management_Level                    0.6405501
16 F1    Social_Perceptiveness_Level              0.6379330
17 F1    Programming_Level                        0.6187006
18 F1    Operations_Analysis_Level                0.6123778
19 F1    Mathematical_Reasoning_Level             0.5982104
20 F1    Persuasion_Level                         0.5955907
21 F1    Negotiation_Level                        0.5361076
22 F1    Technology_Design_Level                  0.4753706
23 F1    Management_of_Personnel_Resources_Level  0.4477253
24 F1    Service_Orientation_Level                0.4431741
25 F1    Coordination_Level                       0.4365772
26 F2    Management_of_Financial_Resources_Level  0.6939872
27 F2    Management_of_Material_Resources_Level   0.6318143
28 F2    Negotiation_Level                        0.6036337
29 F2    Persuasion_Level                         0.5402566
30 F2    Coordination_Level                       0.5229997
31 F2    Management_of_Personnel_Resources_Level  0.4948092
32 F2    Service_Orientation_Level                0.4529055
33 F2    Science_Level                           -0.4084848
34 F2    Time_Management_Level                    0.3608437
35 F2    Social_Perceptiveness_Level              0.3381366
36 F3    Repairing_Level                          0.5898146
37 F3    Equipment_Maintenance_Level              0.5298569
38 F3    Installation_Level                       0.4793818
39 F3    Equipment_Selection_Level                0.4149161
40 F4    Operations_Monitoring_Level              0.9981387
41 F4    Operation_and_Control_Level              0.9472758
42 F4    Troubleshooting_Level                    0.9248453
43 F4    Quality_Control_Analysis_Level           0.8390966
44 F4    Equipment_Maintenance_Level              0.8152390
45 F4    Repairing_Level                          0.8075034
46 F4    Equipment_Selection_Level                0.7993018
47 F4    Installation_Level                       0.4978399
48 F4    Learning_Strategies_Level               -0.3372728
49 F4    Technology_Design_Level                  0.3341191
50 F5    Management_of_Financial_Resources_Level  0.8164755
51 F5    Management_of_Material_Resources_Level   0.7507920
52 F5    Mathematical_Reasoning_Level             0.4085401
53 F5    Operations_Analysis_Level                0.3099598
54 F6    Learning_Strategies_Level                0.4642963
55 F6    Instructing_Level                        0.4545106

In [112]:
matriz <- cargas_fatores %>%
  pivot_wider(
    names_from = Fator,
    values_from = Carga
  )

View(matriz)

   Variavel                                F1            F2
1  Science_Level                            0.8504899553 -0.4084848366
2  Programming_Level                        0.6187005913 -0.2297909902
3  Mathematical_Reasoning_Level             0.5982104418 -0.1079893417
4  Reading_Comprehension_Level              0.9706158307 -0.1683869684
5  Complex_Problem_Solving_Level            0.9304522982  0.0114708298
6  Operations_Analysis_Level                0.6123777726  0.0363782716
7  Technology_Design_Level                  0.4753705820 -0.0169458107
8  Critical_Thinking_Level                  0.9716527069  0.0045715045
9  Active_Learning_Level                    0.9102025433 -0.0463151816
10 Writing_Level                            0.9141151230 -0.0985145514
11 Systems_Analysis_Level                   0.8084443590  0.1147462388
12 Judgment_and_Decision_Making_Level       0.8927170116  0.0772970759
13 Systems_Evaluation_Level                 0.8120655394  0.1560391879
14 Speaking_Level                           0.8904333836 -0.0068414284
15 Persuasion_Level                         0.5955907051  0.5402566247
16 Negotiation_Level                        0.5361076270  0.6036336970
17 Social_Perceptiveness_Level              0.6379330371  0.3381366451
18 Service_Orientation_Level                0.4431740857  0.4529055106
19 Coordination_Level                       0.4365772407  0.5229997464
20 Time_Management_Level                    0.6405501467  0.3608436568
21 Management_of_Personnel_Resources_Level  0.4477253216  0.4948092090
22 Active_Listening_Level                   0.9289107338  0.0116094924
23 Monitoring_Level                         0.7746937277  0.1523478644
24 Repairing_Level                         -0.0004958144  0.0191034771
25 Equipment_Maintenance_Level             -0.0200388151 -0.0117121041
26 Troubleshooting_Level                   -0.0259059033 -0.0076637057
27 Equipment_Selection_Level               -0.0002415052 -0.0079773305
28 Operations_Monitoring_Level              0.0130091433 -0.0051002241
29 Operation_and_Control_Level             -0.1200296243  0.0090052100
30 Quality_Control_Analysis_Level           0.0402694195  0.0006686106
31 Installation_Level                       0.0736882349 -0.0055570380
32 Management_of_Financial_Resources_Level -0.0142779742  0.6939871516
33 Management_of_Material_Resources_Level   0.0183486058  0.6318142822
34 Instructing_Level                        0.7545420361  0.0116796165
35 Learning_Strategies_Level                0.7346012298 -0.0107110762
   F3           F4            F5           F6
1  -0.117678379  0.1324034523  0.019074168  0.039210074
2  -0.024077566  0.0052189989  0.283041369 -0.123977570
3  -0.079950177 -0.0341725798  0.408540115  0.001467262
4  -0.035008523 -0.1886695830 -0.008244564 -0.060374826
5   0.021381474  0.0566894229  0.097414282 -0.062974796
6  -0.073913027  0.0018644994  0.309959773 -0.030630913
7   0.034731914  0.3341191209  0.268748746 -0.063187285
8   0.005130135 -0.0134472803 -0.004101877 -0.166571135
9  -0.001912344 -0.1655621900  0.064827557  0.056965721
10  0.014692331 -0.2708021659 -0.008675213 -0.001316854
11  0.024759389  0.0272704939  0.186549057  0.030341146
12  0.005895594 -0.0114794111  0.078531743 -0.071020193
13  0.034134500  0.0400481885  0.166568431  0.044886986
14  0.008682534 -0.2672095365 -0.078522301 -0.035620285
15  0.020533828 -0.0239197050 -0.005804552 -0.196201491
16  0.024755832 -0.0082403277 -0.004212828 -0.204062976
17 -0.030019824 -0.1694857998 -0.160772954  0.007204976
18 -0.024038517 -0.1663008663 -0.091979160 -0.060708303
19 -0.077363745  0.0795884345  0.022780262  0.114028739
20  0.005892276  0.0003074209  0.132006783  0.068657236
21 -0.046397366  0.0020402489  0.198107470  0.234162805
22 -0.001710884 -0.1489407653 -0.118260368 -0.173199582
23 -0.102538698  0.0151351535 -0.011876328  0.169041290
24  0.589814628  0.8075033932 -0.003791609 -0.002639792
25  0.529856946  0.8152389529 -0.026822920  0.008866024
26  0.208937828  0.9248452877 -0.018487002  0.012101176
27  0.414916057  0.7993017642  0.067895339  0.016525007
28 -0.082324512  0.9981386648 -0.074573063 -0.008506061
29 -0.005759323  0.9472758387 -0.122968993 -0.022960985
30 -0.005065414  0.8390965550  0.130782386  0.037456729
31  0.479381754  0.4978399007  0.048822455 -0.013675517
32  0.002843320 -0.0935358588  0.816475521 -0.005850672
33 -0.003507153  0.0129640604  0.750792049  0.140427820
34  0.008281035 -0.2334408222 -0.084263923  0.454510605
35  0.016376253 -0.3372727975  0.001136718  0.464296251